### ISSUE TITLE
input autosave does not work correctly

### ISSUE THREAD

**Issue by dshitik** [reactioncommerce/reaction#1682] opened 2017-01-04 02:05 UTC
RC forms have problem like this https://github.com/aldeed/meteor-autoform/issues/1188

**Comment by zenweasel** [comment] 2017-01-04 02:21
@dshitik Can you please fill out the issue form completely? An example of where this is manifested in RC so we could look at it would be really helpful. Thanks.

### Expected behavior

### Actual Behavior

### Steps to Reproduce the Behavior

**Comment by dshitik** [comment] 2017-01-04 09:42
**Expected behavior:**
autosave fields in description variantProducts(quantity, price, label ....).

 **Actual Behavior:**
D ata fields not saved if changed field is identic.

**Steps to Reproduce the Behavior**
This problem actual when I follow the next algorithm:
1. Create simpleProduct.
2. Create several variants of product and write data in fileds.
3. Click - publish
4. Select first productVariant and change quantity field to  "5" .
5. Select second productVariant and change quantity field to  "14" .
6. Select three productVariant and change quantity field to  "55"" .
7. Check second and three productVariant. (data not saved)

**Comment by dshitik** [comment] 2017-01-06 19:01
@zenweasel do you see this problem?

**Comment by kieckhafer** [comment] 2017-01-19 06:01
@dshitik, I am unable to reproduce this issue, using the `development` branch. Is this the same branch you were using?

**Comment by kieckhafer** [comment] 2017-01-19 18:25
Cannot reproduce. Closing this ticket. Will re-open if able to reproduce in the future.

**Closed by kieckhafer** 2017-01-19 18:25 UTC
Labels: cannot-reproduce, in progress, UIX
