### ISSUE TITLE
API fails to start on Windows

### ISSUE THREAD

**Issue by 0l6** [reactioncommerce/reaction#4787] opened 2018-11-01 02:58 UTC
Microsoft Windows [Version 10.0.17134.345]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\WailA>cd js

C:\Users\WailA\js>cd reaction

C:\Users\WailA\js\reaction>reaction
INFO: Could not find files for the given pattern(s).
Setting up plugin imports...

Setting up style imports...

Provisioning assets...

C:\Users\WailA\AppData\Local\.meteor\packages\meteor-tool\1.8.0-rc.14\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

RangeError: Maximum call stack size exceeded
{ Error: Command failed: meteor --raw-logs
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at _callee$ (C:\Users\WailA\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:72:43)
    at tryCatch (C:\Users\WailA\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\WailA\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\WailA\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\WailA\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:98:191)
    at C:\Users\WailA\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:98:361
    at process._tickCallback (internal/process/next_tick.js:68:7)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5048,
  stdout: null,
  stderr: null }

Error: App failed to start

C:\Users\WailA\js\reaction>

**Comment by Lebzanwa** [comment] 2018-11-08 17:40
Thats the same outcome I receive also:

Amalia@LAPTOP-AL3OE1SI MINGW64 /g/reaction (master)
$ reaction
INFO: Could not find files for the given pattern(s).
Setting up plugin imports...

Setting up style imports...

Provisioning assets...

[[[[[ ~\G\reaction ]]]]]

=> Started proxy.
=> Meteor 1.8 is available. Update this project with 'meteor update'.
=> Started MongoDB.
app/client/plugins.less: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
app/client/plugins.less: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::factory::NewRawTwoByteString
 5: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
 6: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
 7: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
 8: 0000003303E843C1
{ Error: Command failed: meteor --raw-logs
    at checkExecSyncError (child_process.js:600:11)
    at execSync (child_process.js:637:13)
    at _callee$ (C:\Users\Amalia\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:72:43)
    at tryCatch (C:\Users\Amalia\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Amalia\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Amalia\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Amalia\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:98:191)
    at C:\Users\Amalia\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:98:361
    at process._tickCallback (internal/process/next_tick.js:68:7)
  status: 3,
  signal: null,
  output: [ null, null, null ],
  pid: 4516,
  stdout: null,
  stderr: null }

Error: App failed to start

**Comment by aldeed** [comment] 2018-11-19 22:46
Did you try this? https://docs.reactioncommerce.com/docs/troubleshooting-development#memory-errors-or-errors-about-meteor-rawlogs

**Comment by aldeed** [comment] 2018-11-19 22:48
FYI, developing Reaction 2.0 on a Windows machine is not tested or officially supported.

**Comment by lastpeony** [comment] 2018-12-06 14:33
same.this is a major issue i cant believe how its not fixed yet.In windows reaction 2.0 is just not working.

**Comment by aldeed** [comment] 2018-12-11 00:09
It's unclear from what has been posted here so far whether these errors are on Windows itself or in a Docker container running on a Windows host.
- Reaction 2.0 does not run on Windows and never will
- Developing Reaction 2.0 on Windows _should_ work as long as you are running it and all of the associated services using Docker, but the current tooling around it (e.g., the `make` command in [reaction-platform](https://github.com/reactioncommerce/reaction-platform)) is not designed for Windows, so you'll need to build and spin up all the services manually, and potentially do some manual environment setup for some of the projects. (Someone in the community is more than welcome to create tooling for Windows.)

I am closing this not because it's not an issue, but because it isn't actionable. For the best chance of getting this fixed, please submit a new issue with lots of info about your environment (Windows and Docker versions, Docker memory and CPU settings, total system memory, disk space, and cores, etc.) and specific reproduction steps (what commands are you running in which folders in which order?).

**Closed by aldeed** 2018-12-11 00:09 UTC
