### ISSUE TITLE
Double Scrollbar in Admin with 1.3 

### ISSUE THREAD

**Issue by curranabell** [reactioncommerce/reaction#2494] opened 2017-06-22 21:56 UTC
### Expected behavior
Single Scrollbar in Admin
### Actual Behavior
Producing two scrollbars with this custom theme plugin.
### Steps to Reproduce the Behavior
Create a custom plugin/theme then scrollbars appear. Here is my plugin below
https://github.com/curranabell/nmp
### Versions
(run `reaction -v` from your reaction directory)
1.3
![screen shot 2017-06-22 at 11 53 33 am](https://user-images.githubusercontent.com/16485679/27457822-d52fdd28-5741-11e7-8652-eabad244d6dd.png)

**Comment by curranabell** [comment] 2017-06-23 22:12
The double scroll bar is actually not just evident with a custom theme it also occurs without a custom theme or custom plugins.

**Comment by spencern** [comment] 2017-06-26 20:10
@curranabell I'm not able to reproduce this on development in Chrome. Did you change anything else? If it's just happening on a custom plugin, I'm inclined to blame the plugin. 
![image](https://user-images.githubusercontent.com/1203639/27558076-32a963ae-5a79-11e7-8ef6-be2095c5994b.png)

**Comment by curranabell** [comment] 2017-06-26 20:13
@spencern If you make the screen smaller it should popup. It happens when I open the console. It was happening on my clean install of reaction without any custom plugins as well
![screen shot 2017-06-26 at 10 11 03 am](https://user-images.githubusercontent.com/16485679/27558187-2301b300-5a58-11e7-8b3e-2ff148260d5a.png)

**Comment by zenweasel** [comment] 2017-06-26 22:00
fwiw, I am seeing this as well

**Comment by spencern** [comment] 2017-09-15 20:40
@zenweasel @mikemurray should this issue be closed now? Was it closed by #2653?

**Comment by aaronjudd** [comment] 2017-09-25 15:27
@zenweasel @mikemurray since you have not responded to @spencern request in 10 days... closing this issue.

**Closed by aaronjudd** 2017-09-25 15:27 UTC
Labels: bug, marketplace v1.5.0

**Comment by mikemurray** [comment] 2017-09-25 16:44
Yes, this is fixed.
