### ISSUE TITLE
Tag proptype validation fail `Objects in array must be of type: Schemas.Tag`

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4286] opened 2018-05-31 17:45 UTC
## Issue Description
```
Warning: Failed prop type: Objects in array must be of type: Schemas.Tag
    in Reaction(TagList) (created by TagListContainer)
    in TagListContainer (created by Tracker(TagListContainer))
    in Tracker(TagListContainer) (created by Reaction(TagNav))
    in Reaction(DragDropProvider) (created by Reaction(TagNav))
    in div (created by Reaction(TagNav))
    in div (created by Reaction(TagNav))
    in Reaction(TagNav) (created by TagNavContainer)
    in div (created by TagNavContainer)
    in TagNavContainer (created by Tracker(TagNavContainer))
    in Tracker(TagNavContainer) (created by Reaction(NavBar))
    in header (created by Reaction(NavBar))
    in div (created by Reaction(NavBar))
    in Reaction(NavBar) (created by Tracker(Reaction(NavBar)))
    in Tracker(Reaction(NavBar))
    in div (created by Reaction(coreLayout))
    in Reaction(coreLayout) (created by Route)
    in Route
    in Switch (created by Reaction(App))
    in div (created by Reaction(App))
    in div (created by Reaction(App))
    in div (created by Reaction(App))
    in Reaction(App) (created by Tracker(Reaction(App)))
    in Tracker(Reaction(App))
    in TranslationProvider (created by Tracker(TranslationProvider))
    in Tracker(TranslationProvider)
    in Router (created by BrowserRouter)
    in BrowserRouter
```

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Run the app
2. Open developner console

## Possible Solution

Update the custom Tag proptype to match new schema changes.

### Versions
Node: 9.10.1
NPM: 6.1.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.12.0
Reaction branch: release-1.12.0
Docker: 18.03.1-ce

**Comment by kieckhafer** [comment] 2018-06-29 23:51
I'm unable to reproduce this. I'm on branch `release-1.14.0`, perhaps we fixed this between 1.12 and now.

@spencern thinking of closing this one, we can re-open if someone can reproduce.

**Closed** 2018-07-02 14:30 UTC
Labels: bug
