### ISSUE TITLE
Receive error when enabling Shopify sync

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3502] opened 2018-01-18 05:01 UTC
### Expected behavior
No error

### Actual behavior
Received a "Error setting up shopify sync" when clicking on "Setup Sync" button

### Steps to reproduce the behavior
1. Add Stripe credentials in connector
1. Enable "Update Inventory when new Shopify order is placed"
1. Click on Setup Sync
1. Observe error (no error in server console)

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.4
Reaction branch: master
Docker: 17.12.0-ce
```

**Comment by Akarshit** [comment] 2018-01-18 10:19
The cause of this is that [here](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/connectors-shopify/server/methods/webhooks/webhooks.js#L52) we get the current domain and send that to Shopify as the inbound address.
But when running locally, the address is `localhost:3000`. Address with domain `localhost` are not allowed by Shopify and we get `address not valid` error.
@zenweasel suggested it would be best to take the URL as a configuration parameter,
@spencern What do you think?

**Comment by spencern** [comment] 2018-01-22 15:33
The best solution here is to use a tunnelling tool such as ngrok.
https://ngrok.com/
This makes it trivial to expose your localhost:3000 to the internet with a domain that you can put in the Shopify settings.

**Comment by zenweasel** [comment] 2018-01-22 21:55
I think the point would be that it's a common use case to have the server that would receive webhooks be different from the one that you would be running the admin on. For example almost everywhere I have worked things like the admin tool are run within a VPC whereas things which need to be exposed to the internet are run in a different cluster with different addressing. Or if you use a service like RunScope (an API proxy). The key being that there are a lot of different configurations here and I think we should allow for them. If we are worried that people won't know what that is (hopefully not if they are configuring webhooks?) we could prepopulate that field with the current domain?

That's why I think this should be a user-specified option rather than just grabbing the URL of the server you happen to be on at the moment.

**Comment by Akarshit** [comment] 2018-02-09 18:52
@zenweasel Just found another reason that this was not working. The `topic` being passed to the Shopify API is incorrect. 
It was working for me because I was testing on branch of a old master(before the code responsible was introduced.)
Working to fix it.

**Comment by Akarshit** [comment] 2018-02-14 05:00
Both the reason for this issue were fixed in the PR.

**Closed by Akarshit** 2018-02-14 05:00 UTC
Labels: bug, impact-major
