### ISSUE TITLE
"Sold out" message shows on products after 20+ products upload

### ISSUE THREAD

**Issue by vigyano** [reactioncommerce/reaction#2029] opened 2017-03-22 19:14 UTC
### Expected behavior
"sold out" tag should appear only when the quantity is less the available quantity or warn quanity

### Actual Behavior
"sold out" tag appear random on products that has still available quantity above 1

### Steps to Reproduce the Behavior
The issue appears random and most of the time it occurs after uploading 20 product items. `But sometimes it appears even in less than 20 products`

Scenario :
1. Create custom plugin under /imports/plugin/custom
1. configure predefined shop and product data  in private/data :
     1. shop.json
     2. empty products.json
     3. default 2 level tags in private/data
         * Level 1 : Root-Category
         * Level 2: Category1, Category2, Category3, Category4

2. Upload one products at a time and tag the product to show in one of the level-2 category and also in level-1 root-category. Make sure to publish and make it visible.

3. After 20+ products, the "sold out" message appears in random products.

**Comment by zenweasel** [comment] 2017-03-23 01:09
@vigyano Do you have a `Products.json` that you can share with us that would help us replicate this?

**Comment by vigyano** [comment] 2017-03-23 17:26
Sure,
1. We have uploaded sample products and even disabled custom plugin and same issue. 
2. When the products are created, the sold out issue appeared after 24 product uploads.
3. On mongoexport and imported through private/data fixtures, "sold out" tag issue appeared in many other products. 

Here are the files and two screenshot running local. Exported Tags.json as well since we have 2 level of tags to which the products are tagged both in parent and child. 

1. private.zip : contains Products.json and Tags.json in private/data 

[private.zip](https://github.com/reactioncommerce/reaction/files/865576/private.zip)

2. screenshots : 
  1. sold-out issue at 25th product
![sold-out issue through private-data-fixtures](https://cloud.githubusercontent.com/assets/12378687/24260848/602a1b64-0fb2-11e7-95c1-01936fc28ae1.png)

  2. sold-out issue on other products imported through private/data fixtures
![sold-out issue after creation](https://cloud.githubusercontent.com/assets/12378687/24260849/6043350e-0fb2-11e7-94a3-b69ba64537bf.png)

Let me know if you need more information.

This issue is a blocker for us to migrate existing product gallery into reaction.

I appreciate any help on this.

**Comment by spencern** [comment] 2017-03-23 17:33
@vigyano - do you have Meteor Dev Tools installed? There's a default limit of 24 products that are loaded on a page at a time, I'm curious if maybe the inventory or some other collection isn't getting subscribed or published correctly in your case.

You might also be able to change (temporarily) the ITEM_INCREMENT value here
https://github.com/reactioncommerce/reaction/blob/master/client/config/defaults.js#L22 and see if that causes this to happen any earlier or later.

**Comment by vigyano** [comment] 2017-03-23 22:38
Yes you are right, when I change the ITEM_INCREMENT to 100 and restart reaction, the sold out tag is gone. Any reason for this?

**Comment by vigyano** [comment] 2017-03-24 06:38
I am able to reproduce the same issues with existing reaction example plugin ( https://github.com/reactioncommerce/reaction-example-plugin) with more than 24 products through private/data.

![image](https://cloud.githubusercontent.com/assets/12378687/24283234/c90fb854-1021-11e7-967b-ec7e61662a8c.png)

**Comment by spencern** [comment] 2017-03-24 15:34
Can you share your private/data file that you are using to recreate this? 

I'm not sure exactly what it means that changing ITEM_INCREMENT changes where it happens, but I suspect that it's pub/sub related.

**Comment by vigyano** [comment] 2017-03-24 23:30
I have already shared the private/data in private.zip above. Here is the link again : https://github.com/reactioncommerce/reaction/files/865576/private.zip

I imported this into reaction example plugin and captured the screenshot I posted in previous comment - https://github.com/reactioncommerce/reaction-example-plugin.git

**Comment by zenweasel** [comment] 2017-03-24 23:42
I've also asked @kieha to looks at this to see if this might be related to our eliminating the Inventory publication/subscription

**Comment by kieha** [comment] 2017-03-27 19:04
@zenweasel I've subscribed to the Inventory publication and tried reproducing the error with the data in private/data provided here: https://github.com/reactioncommerce/reaction/files/865576/private.zip
but the `Sold Out` label still shows for some records with a quantity of 1 with no `warn @`.
It seems to happen randomly because some products with a quantity of 1 don't have the `Sold Out` label, while some with the exact same specs do.

Also, I tried changing the value of `ITEM_INCREMENT` and the label disappears.

I don't think the removal of the Inventory subscription caused this.

**Comment by zenweasel** [comment] 2017-03-29 02:38
Error seems to have to do with this query returning no products, which also somehow has to do with admin permissions as they don't seem to show as **Sold Out** when you are logged in as admin.

```
  getTopVariants(id) {
    return Products.find({
      ancestors: [id],
      type: "variant"
    }).map(this.getPublishedOrRevision);
  }
```

**Comment by zenweasel** [comment] 2017-03-29 03:10
The publication is for 24 products but that is only top-level products but not the descendent variants, so when you go to query for those descendents to get inventory, it can't find them. Which is why increasing the limit makes this work. So we need to do a "join" to include 24 parents and all their children

**Comment by zenweasel** [comment] 2017-03-30 11:36
Closed via #2063

**Closed by zenweasel** 2017-03-30 11:36 UTC
Labels: inventory, review

**Comment by vigyano** [comment] 2017-03-31 07:36
You guys rock! Tested in development branch and bug is fixed. No more "sold out", ah! Thanks.

**Comment by hrath2015** [comment] 2017-03-31 07:41
@vigyano  I observed one thing in your data file.  Please donot keep same `title` for Top Product and Variant.  Import will override and keep only variant making Product structure broken in DB. Like art11 and art17. Thanks
