### ISSUE TITLE
Can overwrite user account from Marketplace store setup

### ISSUE THREAD

**Issue by nathanaherne** [reactioncommerce/reaction#4062] opened 2018-03-26 03:25 UTC
I am using the Official Reaction Commerce Docker container built a few days ago. I am testing some of the marketplace features and I noticed that when I setup a marketplace store, I was able to overwrite my own account (which was the sole administrator account for the entire marketplace). This has resulted in me being unable to administer anything other than the marketplace store. This is obviously undesirable behavior as it (seemingly) allows anyone to override the authentication settings for anyone.

The outcome I was expecting was the ability to manage both the entire Marketplace and each store individually (switching between them) as necessary.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Setup Reaction using official docker image
2. Setup marketplace following these steps - https://www.youtube.com/watch?v=Y-p7ZrIBZCQ
3. Invite new store owner using email address of marketplace administrator
4. Receive invite email
5. Click get started (or go link in get started button) link in email invite
6. Change password on reaction site (as per new store setup)
7. Password of admin user is now updated and they are no longer able to admin Marketplace only the marketplace store they were just invited to.

**Comment by zenweasel** [comment] 2018-03-26 03:43
@nathanaherne could you fill out the issue template so we have reproduction steps, etc?

**Comment by nathanaherne** [comment] 2018-04-02 04:40
Based on the issue above, does this mean that each user account can only manage a single store at once, multiple stores per person (account) is not possible at the moment?

**Comment by ajporlante** [comment] 2018-06-01 07:28
I don't think there is an issue here. We should be able to invite new and existing users, including the admin, to be a shop owner. And it just makes sense that a user should be able to reset his own password because they are supposed to have access to their own e-mail.

**Comment by nathanaherne** [comment] 2018-06-04 00:52
> I don't think there is an issue here. We should be able to invite new and existing users, including the admin, to be a shop owner. And it just makes sense that a user should be able to reset his own password because they are supposed to have access to their own e-mail. <

I am not sure I understand why you think there isn't an issue? If you go through the steps above, you should see that by inviting a marketplace admin to be a store owner, the marketplace admin is no longer able to admin the marketplace, they can only admin the individual store.

**Comment by ajporlante** [comment] 2018-06-04 01:15
There is a dropdown on the upper left (beside the edit mode toggle) where you can select shop. If you choose the main shop, then you are still able to perform admin functions.

**Comment by nathanaherne** [comment] 2018-06-04 03:12
> There is a dropdown on the upper left (beside the edit mode toggle) where you can select shop. If you choose the main shop, then you are still able to perform admin functions.<

Thank you for pointing that out, I had not seen that in my testing. I still believe there is an issue with asking the user to change password when clicking on the "get started button" in the email link. It isn't apparent that this is not necessary for someone who is already a previously logged in user of the system.

**Comment by ajporlante** [comment] 2018-06-04 05:57
Agreed. I have created a new issue on that matter #4294 and will close this one.

**Closed by ajporlante** 2018-06-04 05:57 UTC
Labels: bug, impact-minor
