### ISSUE TITLE
Receive error when attempting to process credit card via Authorize.net

### ISSUE THREAD

**Issue by cooperstevenson** [reactioncommerce/reaction#1954] opened 2017-03-10 17:18 UTC
### Expected behavior
Credit card transaction goes through

### Actual Behavior
Client Recieves a 'Match failed [400]' error.

The server reports the following:

```
Exception while invoking method 'authnetSubmit' Error: Match error: Failed Match.Where validation in field cardNumber
    at exports.check (packages/check.js:57:15)
    at [object Object].Meteor.methods.authnetSubmit (imports/plugins/included/payments-authnet/server/methods/authnet.js:44:5)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:717:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: Match failed [400]
```

### Steps to Reproduce the Behavior

# Enable Authorize.net payments in 'Live - Production Mode'

![auth](https://cloud.githubusercontent.com/assets/852480/23805204/c89c133c-0571-11e7-95c3-9f5adcbf8aed.jpg)

# Enter correct card information

# Observe Error message

![card](https://cloud.githubusercontent.com/assets/852480/23805315/415f13be-0572-11e7-8d55-717c7616c220.jpg)

I understand clearly that this seems like a simple mis-entered card. I have entered this card across multiple browsers on multiple machines. The system returns the ```Error: Match failed [400]``` error every time.

This happens regardless of firewall (or lack of) settings on the server.

P.S. I checked with the Authorize.net to ensure that the company account is in good standing. Both times I checked Authorize.net assured me that, "there is no reason why the transactions should not go through."

**Comment by zenweasel** [comment] 2017-03-14 11:06
Note that I have tested this multiple times with multiple cards and have not been able to recreate this issue in either Sandbox or Live mode

**Comment by zenweasel** [comment] 2017-03-14 11:09
@cooperstevenson Can you tell us what type of card you are testing with and possibly the first four digits (which I guess would also tell us what kind of card it is)

**Comment by cooperstevenson** [comment] 2017-03-14 15:33
Hi Zen,

"Of course." I provided you this information off-channel via email.

Sandbox works every time, either with a 'live' card or several other numbers. For some reason, however, simply switching from "Sandbox" to "Live" mode gives trouble.

**Comment by cooperstevenson** [comment] 2017-03-14 18:37
By the way, if it is helpful for you I tried the credit card without spaces in the entry field and received a sanitized '500' (Internal Server) error.

Here is the log entry:

```
Exception while invoking method 'authnetSubmit' TypeError: Cannot read property '0' of undefined
    at /opt/reaction/dist/bundle/programs/server/npm/node_modules/@reactioncommerce/authorize-net/lib/AuthorizeNetGateway.js:107:94
    at /opt/reaction/dist/bundle/programs/server/npm/node_modules/@reactioncommerce/authorize-net/lib/AuthorizeNetGateway.js:86:16
    at tryCatcher (/opt/reaction/dist/bundle/programs/server/npm/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/reaction/dist/bundle/programs/server/npm/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/reaction/dist/bundle/programs/server/npm/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/opt/reaction/dist/bundle/programs/server/npm/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/opt/reaction/dist/bundle/programs/server/npm/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/opt/reaction/dist/bundle/programs/server/npm/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/reaction/dist/bundle/programs/server/npm/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
 => awaited here:
    at Function.Promise.await (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
    at [object Object].Meteor.methods.authnetSubmit (imports/plugins/included/payments-authnet/server/methods/authnet.js:80:29)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:717:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by cooperstevenson** [comment] 2017-03-14 21:21
I sent Brent the URL to the site for testing. I will refund funds to the account if the payment works.

**Comment by zenweasel** [comment] 2017-03-15 09:14
I tested against your site and I do not see the `Match` error, but I do see the 500 error which I assume must be the same error you have above? That seems like it could be a legit problem I will need to look into more.

**Comment by zenweasel** [comment] 2017-03-21 00:58
I cannot reproduce this error even in Live mode with a real card.

**Comment by zenweasel** [comment] 2017-03-21 01:30
@cooperstevenson Is it possible to give me access to your code and I can pull it locally and see if I can replicate it doing that?

**Comment by cooperstevenson** [comment] 2017-03-21 15:02
@zenweasel Sure thing! I sent them over.

Thanks!

**Comment by zenweasel** [comment] 2017-03-21 19:40
I will try those as well, but I actually meant access to your repo so I could run your version of Reaction locally.

**Comment by cooperstevenson** [comment] 2017-03-24 15:53
Thanks, Brent! I will have this information for you soon; I really appreciate it!

**Comment by zenweasel** [comment] 2017-04-05 02:22
Good news everyone! I was able to replicate your issue by using your credentials (in Live Mode) on my local machine. 🤔

**Comment by zenweasel** [comment] 2017-04-05 02:37
So the error you are seeing is from improperly parsing the error but the raw response looks like this below:, so it looks like there may be a problem with your credentials.

```
createTransactionResponse {
    "$": {
        "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "xmlns:xsd": "http://www.w3.org/2001/XMLSchema",
        "xmlns": "AnetApi/xml/v1/schema/AnetApiSchema.xsd"
    },
    "messages": [
        {
            "resultCode": [
                "Error"
            ],
            "message": [
                {
                    "code": [
                        "E00007"
                    ],
                    "text": [
                        "User authentication failed due to invalid authentication values."
                    ]
                }
            ]
        }
    ],
    "transactionResponse": [
        ""
    ]
}
```

**Comment by zenweasel** [comment] 2017-04-05 03:15
I created a PR to fix this (the error parsing) in the original library. https://github.com/ongoworks/node-authorize-net/pull/2

**Comment by zenweasel** [comment] 2017-04-07 01:13
Closing as this appears to be a configuration issue.

**Closed by zenweasel** 2017-04-07 01:13 UTC
Labels: in progress
