### ISSUE TITLE
Firefox order layout broken

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#750] opened 2016-02-01 18:44 UTC
![firefox_developer_edition_and_main_js_ __users_aaronjudd_ongoworks_reaction](https://cloud.githubusercontent.com/assets/439959/12727180/91cd9e54-c8d0-11e5-8619-438aa26de86f.png)

**Comment by mikemurray** [comment] 2016-02-01 18:48
duplicate of: https://github.com/reactioncommerce/reaction/issues/728
And heres the PR: https://github.com/reactioncommerce/reaction/pull/735

Closing.

**Closed by mikemurray** 2016-02-01 18:48 UTC
Labels: bug, needs-to-be-reproduced, ready, UIX
