### ISSUE TITLE
Receive no shipping options when checking out for the second time

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4677] opened 2018-09-25 02:33 UTC
## Issue Description
If you place an order and return to try and place another order the shipping options don't appear until you edit and save your address

## Steps to Reproduce
1. Place something in the cart as an anonymous user
1. In the checkout screen select "Register" and create a new user
1. Complete checkout
1. Add another item to the cart
1. Proceed to checkout
1. Observe that the shipping options are not displayed and you can't complete checkout unless you edit and resave your address (or in another way trigger a cart recalc)

### Versions
Reaction: 2.0.0-rc1

**Comment by zenweasel** [comment] 2018-10-22 20:39
@willmoss1000 Yeah, this issue might just be a dupe (it's essentially the same issue it seems).

I don't know exactly what it is except that the stage for shipping options needs to be triggered by another event and I think when you have an existing address (so that addressbook SAVE is **not** triggered) it's not triggering that event. So probably a check needs to be put in somewhere in the addressbook code that if you have an existing address, also trigger that event.

**Comment by willmoss1000** [comment] 2018-10-22 23:09
It looks to me like the billing address and shipping address aren't being added to the cart. Were hooks not run previously after the `addToCart` method to do this? i.e. `updateShipmentQuotes`.

**Comment by willmoss1000** [comment] 2018-10-23 10:11
@zenweasel adding `Hooks.Events.run("afterCartUpdate", cart._id);` at the bottom of the `cart/createCart` method seems to do the trick for me (in 1.4.1).  However, I've also turned off guest checkout, as I was experiencing a lot of issues there.

**Comment by willmoss1000** [comment] 2018-10-23 12:15
@zenweasel It looks like this is because the billing address isn't being set. 

Currently: I've added to the `afterCartUpdate` hook to add a billing address if it's missing which works.

If this seems like a good approach I'd be happy to submit a PR - however I feel it's likely something isn't working. How was the billing address set before the move to graphQL?

**Comment by janus-reith** [comment] 2018-12-15 13:10
@zenweasel You're probably right. I have to deal with a similiar issue in a v1.13 version, some orders are created and visible in the dashboard panel, but lack billing address.

Therefore, the email job for sending order confirmations also failed to send due to missing fields.

This happened several times, and I were unable to figure out the circumstances yet that lead to that error.

As this really is an issue for a release considered stable, I'm in the process of moving to 2.x as I hoped that the new order schema would not include these issues anymore.

**Comment by janus-reith** [comment] 2018-12-15 13:12
@willmoss1000 Would you mind sharing the code that gets executed in that hook?
This could probably save me some time. ;)

**Comment by willmoss1000** [comment] 2018-12-15 20:53
@janus-reith - it's a dirty quick fix, but it's working for me. I would recommend reverting to 1.12 if you can? - loads of errors came in when the schemas were changed to use `accountId`.

For this issue I actually just updated the `updateShipmentMethods` function to:
``` 
 if (cart) {
    if (!cart.shipping || cart.shipping.length === 0) {
      addAddresses(cart);
      cart = Cart.findOne({ _id: cartId });
    }
    if (!cart.billing || !cart.billing.length || !cart.billing[0].address) {
      updateBillingAddress(cart);
      cart = Cart.findOne({ _id: cartId });
    }
    const rates = Meteor.call("shipping/getShippingRates", cart);
    updateShippingRecordByShop(cart, rates);
  }
```
and, added a function called `updateBillingAddress`:
```
/**
 * @name updateBillingAddress
 * @param  {Object} cart [description]
 * @return {Object} address
 * @private
 */
function updateBillingAddress(cart) {
  const address = getBillingAddress(cart);

  if (address) {
    const billing = { cart };
    billing.address = address;

    Cart.update(
      { _id: cart._id },
      { $set: { "billing.0": billing } }
    );
  }
}
```

**Comment by mpaktiti** [comment] 2019-07-15 08:43
@zenweasel Can't reproduce this issue with current version.
Every time I place a new order I get a prompt to enter my address.

![image](https://user-images.githubusercontent.com/11715799/61204278-74e6ec80-a6f5-11e9-944b-3507460564f3.png)

I actually get this prompt even if I have saved addresses in my Address Book so I registered this issue https://github.com/reactioncommerce/reaction/issues/5322. I'm closing this one.

**Closed by mpaktiti** 2019-07-15 08:43 UTC
Labels: bug, impact-major
