### ISSUE TITLE
When logged out, cart completed shows "Order Processing"

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1638] opened 2016-12-17 03:06 UTC
### Expected behavior

When logged out, cart completed page should show a login page.
ie:
`http://localhost:3000/reaction/cart/completed?_id=cE4EBEeYFBXFPqjhG`
should display login/access denied.  

### Actual Behavior
Displays "Order Processing". 

### Steps to Reproduce the Behavior

Open a valid cart/completed url in an incognito window. 
![cart_completed_and_cart_completed_and_your_order_is_confirmed_-_6dd9ge4mwvqwqb42p_-_testing_reactioncommerce_com_-_reaction_commerce_mail](https://cloud.githubusercontent.com/assets/439959/21283976/c05c6258-c3c2-11e6-9a7b-abbbaf438b72.png)

**Comment by andela-aatanda** [comment] 2017-05-03 16:22
There's a PR open for this [here](https://github.com/reactioncommerce/reaction/pull/2201)

**Comment by zenweasel** [comment] 2017-05-08 04:29
Closed via #2201

**Comment by zenweasel** [comment] 2017-05-10 10:17
When you checkout now as an anonymous user with Paypal Express you get a login screen rather than the completed screen. Confirmed that this doesn't happen in `master`. Most likely it is related to the fix for this issue.

**Comment by impactmass** [comment] 2017-05-10 15:17
@andela-aatanda asked me if the new issue here might have been caused by my permissions PR.... but I've confirmed it's not.

I created a branch with permissions issue fixed (but without React router)... and the checkout worked and I see cart completion page. This _might_ be related/caused by React router.

**Comment by hrath2015** [comment] 2017-05-10 19:32
@zenweasel  are u able to  do it on latest dev.  Because I am not able to see any payment options listed for guest user due to issue# 2231

**Closed** 2017-05-24 23:47 UTC
Labels: bug
