### ISSUE TITLE
cannot start reaction in red-hat 

### ISSUE THREAD

**Issue by thanhtungka91** [reactioncommerce/reaction#2428] opened 2017-06-13 14:03 UTC
### Expected behavior
start reaction normally
### Actual Behavior
cannot start reaction ... 
Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

/tmp/shelljs_2813822e20fc7998b0eb:10
    fs.writeFileSync(fname, err.code.toString());
                                    ^

TypeError: Cannot read property 'toString' of null
    at /tmp/shelljs_2813822e20fc7998b0eb:10:37
    at ChildProcess.exithandler (child_process.js:259:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
exec: internal error

### Steps to Reproduce the Behavior
1. install nvm 
2. install node
3. install reaction 
4. start reaction
### Versions
(run `reaction -v` from your reaction directory)
Node: 8.1.0
NPM: 5.0.3
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.9.3
Reaction: 1.2.0
Reaction branch: master

**Comment by spencern** [comment] 2017-06-13 16:51
Hi @thanhtungka91 

A few questions:
  * What version of RedHat?
  * How much RAM?
  * Have you run Reaction successfully before?

We've seen this `cannot read property 'toString' of null` before in #1590 (and it still bugs most of us on a fairly consistent basis), but I don't recall having seen it during startup of reaction.

Is this a bug you're getting that is preventing you from starting Reaction at all or is it happening after the app has started?

**Comment by thanhtungka91** [comment] 2017-06-14 13:50
Hi @spencern 

- What version of RedHat?
 Red Hat Enterprise Linux 7.3 (HVM), SSD Volume Type (run on AWS EC2)
- How much RAM?
 1G
- Have you run Reaction successfully before?
 Yep, reaction has been installed successful 
- Reaction never start ... from the first, OS is fresh.. i just install for test on AWS.

**Comment by spencern** [comment] 2017-06-14 14:00
A few notes:

* 1G is probably not quite enough RAM for a production instance of Reaction. It's definitely too little RAM for a development instance
* If you're using `reaction run` you're running a development instance of Reaction. While you can do this on AWS or other cloud providers, we recommend developing locally.
* If you are trying to test a deployment of Reaction, you can follow our deployment docs here: https://docs.reactioncommerce.com/reaction-docs/master/deploying - Let me stress again that `reaction run` is _not_ suitable for deployment.

**Comment by jshimko** [comment] 2017-06-14 14:36
I also don't see "install build tools" anywhere in your steps.  That part isn't optional either.  But if your clone of Reaction got through the `reaction init` step, that means it ran `npm install` in successfully.

As Spencer said, 1GB of RAM is probably your problem.  A development build is a very resource intensive process - especially the first time it happens.  I recommend developing/building locally and then deploying your built image.

Just to confirm, I went through the setup on CentOS (because Red Hat appears to require a license to enable some repo sources. It's otherwise essentially the same though).

```sh
# hop into a fresh CentOS 7 image
docker -it --rm centos:7 bash

# install dependencies
curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
yum install -y gcc-c++ make git nodejs

# get Reaction
npm i -g reaction-cli
reaction init
cd reaction

# since we're root inside the container...
export METEOR_ALLOW_SUPERUSER=true

# start the app
reaction
```
...and we're up and running.

**Comment by spencern** [comment] 2017-06-15 00:12
Closing this because I think it's a problem with the amount of RAM on your machine.
If you can reproduce this with 4G+ RAM and it's different than the issue in #1590 please reopen

**Closed by spencern** 2017-06-15 00:12 UTC
Labels: cannot-reproduce, needs-to-be-reproduced
