### ISSUE TITLE
[release-1.14.0] Error when starting Release 14

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4434] opened 2018-07-16 06:42 UTC
## Issue Description
Receiving the following error in the server console when starting release 14
```
06:27:53.974Z ERROR Reaction: [product._id is not allowed by the schema]
  Error: [product._id is not allowed by the schema]
      at Function.SimpleSchema.defineValidationErrorTransform.error [as validationErrorTransform] (imports/plugins/core/core/server/startup/index.js:20:20)
      at /Users/brenthoover/Projects/js/reaction/node_modules/simpl-schema/dist/SimpleSchema.js:757:30
      at Array.forEach (<anonymous>)
      at SimpleSchema.validate (/Users/brenthoover/Projects/js/reaction/node_modules/simpl-schema/dist/SimpleSchema.js:730:15)
      at Promise.asyncApply (imports/plugins/core/catalog/server/no-meteor/utils/publishProductToCatalog.js:36:21)
      at /Users/brenthoover/.meteor/packages/promise/.0.11.1.tdo4r7.5gbr++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

## Steps to Reproduce
1. Reset data
1. Start the app on release 14

### Versions
In case it's not clear: Release 14

**Comment by stunjiturner** [comment] 2018-07-16 08:13
I just left a new issue, when I run locally without docker, using the reaction command line, this error shows up when I click publish for changes, but the app still runs, ????

**Comment by spencern** [comment] 2018-07-16 18:36
@zenweasel I'm unable to reproduce this using release-1.14.0 starting using our docker-compose file.

Where are you seeing this error? Client? Server? 
Are you able to reproduce this in a containerized environment or just using `reaction run`?

**Comment by stunjiturner** [comment] 2018-07-16 18:48
client in the console. I am doing a clean install

**Comment by zenweasel** [comment] 2018-07-16 22:44
@spencern Updated the description to be more clear. Running it locally (not in a container) from a fresh db. It does _seem_ to be from a migration but I didn't want to make that assumption

**Comment by spencern** [comment] 2018-07-16 23:24
To be clear, you're talking about release-1.14.0?

**Comment by spencern** [comment] 2018-07-16 23:49
I was just able to reproduce within a container and it appears to be coming from https://github.com/reactioncommerce/reaction/pull/4421/files#diff-26cb9114bdc2db419e69afe92a2dad35R31

**Comment by kieckhafer** [comment] 2018-07-19 23:07
Fixed by @aldeed: https://github.com/reactioncommerce/reaction/commit/56179363176587f23983582bcb14a3a9541c68d6

**Closed by kieckhafer** 2018-07-19 23:07 UTC
Labels: bug, release-blocker
