### ISSUE TITLE
Reaction randomly crashes

### ISSUE THREAD

**Issue by Stat1c14** [reactioncommerce/reaction#2158] opened 2017-04-23 21:00 UTC
After running Reaction, after a seemly random amount of time the app will crash will the same error.

### Expected behavior

```
Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ ~/McEw/reaction-store ]]]]]

=> Started proxy.
=> Started MongoDB.
20:14:17.162Z  INFO Reaction: Load default data from /private/data/
20:14:17.418Z  INFO Reaction: JobServer started
20:14:17.429Z  WARN Reaction: Skipped loading settings from reaction.json.
20:14:17.429Z  INFO Reaction: Loaded "/private/settings/reaction.json" for registry fixture import
20:14:21.714Z  INFO Reaction: Reaction Version: 1.1.1
20:14:21.771Z  WARN Reaction: OpenExchangeRates API not configured. Not adding fetchRates job
20:14:21.777Z  WARN Reaction: OpenExchangeRates API not configured. Not adding flushRates job
20:14:21.782Z  WARN Reaction: No cart cleanup schedule
20:14:21.986Z  INFO Reaction: Reaction initialization finished.
=> Started your app.

=> App running at: http://localhost:3000/
```

### Actual Behavior

```
Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ ~/McEw/reaction-store ]]]]]

=> Started proxy.
=> Started MongoDB.
20:14:17.162Z  INFO Reaction: Load default data from /private/data/
20:14:17.418Z  INFO Reaction: JobServer started
20:14:17.429Z  WARN Reaction: Skipped loading settings from reaction.json.
20:14:17.429Z  INFO Reaction: Loaded "/private/settings/reaction.json" for registry fixture import
20:14:21.714Z  INFO Reaction: Reaction Version: 1.1.1
20:14:21.771Z  WARN Reaction: OpenExchangeRates API not configured. Not adding fetchRates job
20:14:21.777Z  WARN Reaction: OpenExchangeRates API not configured. Not adding flushRates job
20:14:21.782Z  WARN Reaction: No cart cleanup schedule
20:14:21.986Z  INFO Reaction: Reaction initialization finished.
=> Started your app.

=> App running at: http://localhost:3000/
/private/var/folders/mz/sw699hns5ts01h9py8gx8mfh0000gn/T/shelljs_f29e657754bb75c4d20e:10
    fs.writeFileSync(fname, err.code.toString());
                                    ^

TypeError: Cannot read property 'toString' of null
    at /private/var/folders/mz/sw699hns5ts01h9py8gx8mfh0000gn/T/shelljs_f29e657754bb75c4d20e:10:37
    at ChildProcess.exithandler (child_process.js:214:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
exec: internal error
```

### Steps to Reproduce the Behavior

Just run `reaction` and wait.

### Versions

OSX Sierra 10.12.1
Node: 6.2.2
NPM: 4.0.5
Docker: 17.03.1-ce
Reaction CLI: 0.8.0
Reaction: 1.1.1
Reaction Branch: master

**Comment by carlos-olivera** [comment] 2017-04-23 21:14
I got the same error, I use Mac only for development, it is not so frequent, I just get used to live with it.

In production (Linux) never happened.

**Comment by Stat1c14** [comment] 2017-04-23 21:21
Good to know I'm not the only one. I tried to run Reaction inside a Vagrant box because I figured Linux would be better supported for Reaction, but Reaction wouldn't work then either (see #2127).

I've run into a lot of these obscure, strange issues working with the platform so far. Is this a Mac-only issue, or is Reaction this unstable everywhere?

**Comment by zenweasel** [comment] 2017-04-23 22:33
Closed as duplicate of https://github.com/reactioncommerce/reaction/issues/1590

**Closed by zenweasel** 2017-04-23 22:33 UTC
