### ISSUE TITLE
Email Settings: Invalid prop `noDataText` supplied to `ReactTable`

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3280] opened 2017-11-10 21:24 UTC
### Expected behavior
No console warnings or errors.

### Actual behavior
```
modules.js:85606 Warning: Failed prop type: Invalid prop `noDataText` supplied to `ReactTable`, expected a ReactNode.
    in ReactTable (created by Reaction(SortableTable))
    in Reaction(SortableTable) (created by Reaction(EmailLogs))
    in div (created by Reaction(CardBody))
    in VelocityTransitionGroupChild (created by TransitionGroup)
    in span (created by TransitionGroup)
    in TransitionGroup (created by VelocityTransitionGroup)
    in VelocityTransitionGroup (created by Reaction(CardBody))
    in Reaction(CardBody) (created by Reaction(EmailLogs))
    in div (created by Reaction(Card))
    in Reaction(Card) (created by Reaction(EmailLogs))
    in div (created by Reaction(CardGroup))
    in Reaction(CardGroup) (created by Reaction(EmailLogs))
    in Reaction(EmailLogs) (created by withProps(EmailLogs))
    in withProps(EmailLogs) (created by Tracker(withProps(EmailLogs)))
    in Tracker(withProps(EmailLogs))
printWarning @ modules.js:85606
```
### Steps to reproduce the behavior
Open browser console, open email settings.

### Versions
(run `reaction -v` from your reaction directory)
```
Node: 6.11.1
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.21.2
Reaction: 1.5.8
Reaction branch: master
Docker: 17.09.0-ce
```
Also exists in Meteor 1.6 branch.

**Comment by Akarshit** [comment] 2017-11-13 13:54
@aaronjudd Duplicate of #3219.

**Comment by zenweasel** [comment] 2017-11-14 06:09
Closing duplicate

**Closed by zenweasel** 2017-11-14 06:09 UTC
Labels: bug
