### ISSUE TITLE
Cannot change address on checkout page

### ISSUE THREAD

**Issue by Badyl1g** [reactioncommerce/reaction#5467] opened 2019-08-19 07:55 UTC
## Issue Description
After entering the shipping address, saving it and changing I can't save the changes.
The "Save and continue" button is disabled, no matter how many inputs I change.
To save the changes I had to manually enable the button through React Devtools.

## Steps to Reproduce
1. Add an item to cart
2. Go to checkout page
3. Enter an address and save it
4. Click on the "Change" button in "Shipping address" section
5. Make any changes to the address
6. Try to save the changes 

## Possible Solution
There's probably an issue with tracking the state of address form. After changing at least one input the button should be enabled.

### Versions
2.1.0

**Comment by janus-reith** [comment] 2019-08-20 06:22
I believe this is a duplicate of https://github.com/reactioncommerce/example-storefront/issues/494
The fix is here: https://github.com/reactioncommerce/reaction-component-library/pull/417

Release 0.66.0 should include this fix.

Therefore, running `yarn add @reactioncommerce/components@0.66.0` might fix your issue.

Note that you need to recreate the `node_modules` volume and rebuild, as per default the example-storefront is keeping a separate node_volumes from the host's source.

**Comment by Badyl1g** [comment] 2019-08-20 09:20
I installed new version of that package and run `docker-compose up -d --build` in example-storefront directory.

Now when I click on "Change" button I get `ReferenceError: _objectSpread is not defined` error.

![image](https://user-images.githubusercontent.com/27491471/63334536-ebea5300-c33b-11e9-86dc-3595729e7507.png)

The error also throws with new checkout, on a newly created user.

What do you mean by "recreate node_modules volume"?

**Comment by janus-reith** [comment] 2019-08-21 07:37
By recreating I mean running `docker volume ls` and then delete relevant volumes:
`docker volume rm reaction-next-starterkit_empty_node_modules reaction-next-starterkit_node_modules reaction-next-starterkit_web-yarn`

Regarding the `ReferenceError`, I was about to give a bit longer instructions on how to get it working with your storefront code, but it seems like this was addressed in 0.67.1 already :
https://github.com/reactioncommerce/reaction-component-library/pull/433

See if updating fixes your issue.

**Comment by willopez** [comment] 2019-09-26 22:30
resolved in https://github.com/reactioncommerce/example-storefront/pull/588

**Closed by willopez** 2019-09-26 22:30 UTC
