### ISSUE TITLE
[Checkout] Show cart items on checkout page

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#807] opened 2016-02-23 00:24 UTC
As a user, I want to be able to see a summary of items in my cart during the checkout process..

**Comment by aaronjudd** [comment] 2016-02-23 00:54
Duplicate of #287 ?

**Comment by mikemurray** [comment] 2016-02-23 00:58
Yes, seems mislabeled as part of the order workflow, instead of cart workflow?

**Closed** 2016-03-22 01:12 UTC
Labels: enhancement
