### ISSUE TITLE
Npm is tried to rename plugin inside docker container

### ISSUE THREAD

**Issue by OlehObodin** [reactioncommerce/reaction#6428] opened 2022-03-20 21:46 UTC
## Issue Description

After rerun the container npm is tried to rename plugin name. But it has not permission. And should it have to do it at all?
## Steps to Reproduce

1. make init-dev
2. clone api-example-plugin to api-plugins folder in reaction-platform
3. Change setting json for your plugin for example name `@orgname/api-example-plugin`
4. `npm link` in api-example-plugin folder
5. `npm link @orgname/api-example-plugin`
6. `bin/package-link @orgname/api-example-plugin`
7. make stop
8. make start

```
npm ERR! code EACCES
api_1    | npm ERR! syscall rename
api_1    | npm ERR! path /usr/local/src/app/node_modules/@itleadopencommerce/api-plugin-products-volume
api_1    | npm ERR! dest /usr/local/src/app/node_modules/@itleadopencommerce/.api-plugin-products-volume-cxbdezTS
api_1    | npm ERR! errno -13
api_1    | npm ERR! Error: EACCES: permission denied, rename '/usr/local/src/app/node_modules/@itleadopencommerce/api-plugin-products-volume' -> '/usr/local/src/app/node_modules/@itleadopencommerce/.api-plugin-products-volume-cxbdezTS'
api_1    | npm ERR!  [Error: EACCES: permission denied, rename '/usr/local/src/app/node_modules/@itleadopencommerce/api-plugin-products-volume' -> '/usr/local/src/app/node_modules/@itleadopencommerce/.api-plugin-products-volume-cxbdezTS'] {
api_1    | npm ERR!   errno: -13,
api_1    | npm ERR!   code: 'EACCES',
api_1    | npm ERR!   syscall: 'rename',
api_1    | npm ERR!   path: '/usr/local/src/app/node_modules/@itleadopencommerce/api-plugin-products-volume',
api_1    | npm ERR!   dest: '/usr/local/src/app/node_modules/@itleadopencommerce/.api-plugin-products-volume-cxbdezTS'
api_1    | npm ERR! }
api_1    | npm ERR! 
api_1    | npm ERR! The operation was rejected by your operating system.
api_1    | npm ERR! It is likely you do not have the permissions to access this file as the current user
api_1    | npm ERR! 
api_1    | npm ERR! If you believe this might be a permissions issue, please double-check the
api_1    | npm ERR! permissions of the file and its containing directories, or try running
api_1    | npm ERR! the command again as root/Administrator.
api_1    | 
api_1    | npm ERR! A complete log of this run can be found in:
api_1    | npm ERR!     /home/node/.npm/_logs/2022-03-20T21_19_37_542Z-debug-0.log
```
## Possible Solution

Change folder permissions, but not very good idea, because in npm registry we have normal name

### Versions

4.1.5

**Comment by brent-hoover** [comment] 2022-03-26 18:45
Hi @OlehObodin Can you give me a little more specific instructions rather than just "link plugin" so I can try and reproduce?

**Comment by OlehObodin** [comment] 2022-03-26 19:39
@zenweasel , Hi, I have edited steps to reproduce in description above. It is strange, but seems to work now, but I have built images for new customization, may be point was in there.

**Comment by brent-hoover** [comment] 2022-03-28 23:42
@OlehObodin Are you saying the problem is not occurring anymore? Can we close this?

**Closed as completed** 2022-03-29 11:50 UTC
Labels: bug, needs triage
