### ISSUE TITLE
Cardholder name must include both first and last name - even i create cardholder name

### ISSUE THREAD

**Issue by vivekmore89** [reactioncommerce/reaction#2461] opened 2017-06-19 12:22 UTC
![screenshot from 2017-06-19 17-47-13](https://user-images.githubusercontent.com/6220344/27284827-ed079f48-5517-11e7-9087-dc1269d7e515.png)

**Comment by aaronjudd** [comment] 2017-06-19 20:25
Can you provide `reaction -v` output, so we know what branch you are testing and also which payment package were you testing?

**Comment by spencern** [comment] 2017-06-20 01:31
I was able to reproduce this using Auth.net.
I had the discount codes enabled as well.

@vivekmore89 can you confirm what payment provider you saw this with?

**Comment by zenweasel** [comment] 2017-06-20 02:11
I'm not able to reproduce this using Auth.net and discount codes enabled.

**Comment by vivekmore89** [comment] 2017-06-20 04:52
@aaronjudd   
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.9.3
Reaction: 1.2.0
Reaction branch: master

**Comment by spencern** [comment] 2017-06-20 05:12
Got another confirmed reproduction

Steps:
1. Reset db / new Reaction instance
2. enable free shipping
3. enable discount codes
4. create new discount code "test", 10, discount, 1, 1
5. enable auth.net (test - sandbox mode)
6. from non-logged in window (~incognito) visit app
7. add product to cart.
8. proceed to checkout
9. guest mode
10. use the following for both default addresses:
name: `asdf`
address: `sadf sadf`
postal: `asdf`
city: `sadf`
state: `sadf`
country: 'American Samoa` / AS
phone: `1122332322`
11. proceed to payment
12. use the following for payment:
name: `asdf asdfsadf`
card: `1212121212121212`
expiry: 03/2018
cvv: `112`

**Comment by zenweasel** [comment] 2017-06-20 05:23
Verified that Auth.net has regex that forces the name to start with a capital letter (but doesn't enforce that there be two names). Probably best to remove that

**Comment by hrath2015** [comment] 2017-06-20 05:28
Paypal Flow forces 2 names:
![image](https://user-images.githubusercontent.com/14071646/27317945-49f80906-55a7-11e7-80db-cf90a9805b77.png)

**Comment by zenweasel** [comment] 2017-06-20 05:30
It actually doesn't. It enforces that it starts with a capital letter. Add a second name and it still won't work.
```
regEx: /[A-Z][a-zA-Z]*/
```

**Comment by zenweasel** [comment] 2017-06-20 05:30
Braintree does enforce two names (and only two)
```
regEx: /^\w+\s\w+$/
```

**Comment by hrath2015** [comment] 2017-06-20 05:38
yes that is right. thanks.
 Payment Options need some revamp (in case of multiple options).  If there is validation error  spinner remains.  Only option is to go back and start checkout again.  Once you land on checkout page again,  error remains in red color.  Ideally error should be triggered based on the payment option selected.

**Comment by vivekmore89** [comment] 2017-06-20 07:02
thanks... it's work now..

**Comment by zenweasel** [comment] 2017-06-21 00:06
Closed via #2471

**Closed by zenweasel** 2017-06-21 00:06 UTC
Labels: bug, critical impact

**Comment by Contrary-jerald** [comment] 2025-02-03 06:20
> Can you provide `reaction -v` output, so we know what branch you are testing and also which payment package were you testing?





https://stylesheets.space/questions/revealing-the-specific-row-and-column-of-the-selected-element-in-each-table-when-hovering-over-it
