### ISSUE TITLE
Deleting a discount code doesn't work

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3378] opened 2017-12-07 22:26 UTC
### Expected behavior
After clicking on "Delete" and confirming delete for a discount code the code should be deleted

### Actual behavior
The discount code is not deleted

### Steps to reproduce the behavior
1. Login as an admin
1. Create a discount
1. Select the discount code and select "delete"
1. Observe that nothing happens

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.8.1
Meteor NPM: 5.4.2
Reaction CLI: 0.24.2
Reaction: 1.6.0
Reaction branch: master
Docker: 17.09.0-ce
```

**Comment by zenweasel** [comment] 2017-12-08 01:18
This may be related to #3379. Reconfirm after that is fixed.

**Comment by Akarshit** [comment] 2017-12-11 10:21
This is working(atleast for me) after pulling #3379

**Comment by codejockie** [comment] 2017-12-12 15:06
I just tried reproducing on `master` and I was able to delete the discount code I created. It's verified. Fixed.

**Comment by kieckhafer** [comment] 2017-12-12 20:41
Works for me after #3379, closing out.

**Closed by kieckhafer** 2017-12-12 20:41 UTC
Labels: bug, impact-minor
