### ISSUE TITLE
Weird behavior on checkout login/signup

### ISSUE THREAD

**Issue by kieha** [reactioncommerce/reaction#2328] opened 2017-05-22 20:27 UTC
This happens when logging in/signing up on the checkout panel.

#### Scenario A

When logging in/signing up and I have entered the wrong credentials, an error message should pop up on the form.

#### Scenario B

When logging in/signing up and I have the correct credentials, I should be redirected back to the checkout panel immediately to continue filling out the checkout steps.

#### Scenario A

When logging in/signing up and I have entered the wrong credentials, the `Unauthorized` page pops up for a moment, then redirects back to the checkout page without displaying the error message on the form.

#### Scenario B

When logging in/signing up and I have the correct credentials, the `Unauthorized` page pops up for a moment, then the `Your cart is empty` page displays, then finally it redirects back to the checkout page.

### Steps to Reproduce the Behavior

* Add product to cart while not logged in
* Proceed to checkout while still not logged in
* Enter the wrong credentials on either signup/login to observe actual behavior in Scenario A
* Enter correct credentials on either signup/login to observe actual behavior in Scenario B

### Versions
Node: 6.2.2
NPM: 3.10.9
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.3
Reaction: 1.2.0
Reaction branch: development
Docker: 1.13.0

**Comment by aaronjudd** [comment] 2017-05-24 23:33
@mikemurray sounds like react router? however, we've had a similar behavior when the guest logins in the past as well...  where you see "oops your cart is empty" right after login, and then the cart loads..

**Comment by mikemurray** [comment] 2017-05-25 17:22
@aaronjudd @kieha The part about there being no error on wrong credentials was happening before React Router.

The second part is most likely React Router. When signing in the routes are re-rendered with updated permissions, and there's a moment where you have no permissions until the subscription is updated.

This update on login is how it used to work with Flow Router. We may have to think of a better approach for React Router.

**Comment by aaronjudd** [comment] 2017-06-20 01:06
@mikemurray @kieha is this still a valid issue in 1.3.0?

**Comment by kieha** [comment] 2017-06-20 16:36
@aaronjudd I've just tried reproducing it on 1.3.0 and it still happens, but the `unauthorized` page no longer shows up.

**Comment by awadesmoline** [comment] 2017-08-08 08:27
*Update*
I found this to be cause by the login component [here](https://github.com/reactioncommerce/reaction/blob/development/client/modules/accounts/templates/login/loginForm.js#L4) being re-mounted when the sign in button is clicked. So when you click with the wrong credentials it tries to set the state with form errors when the component has already unmounted, and by the time it has mounted again, the form errors are no more in state to set.  Not sure what exactly is causing it to be unmounted and mounted again.
I am pausing on this to finish up my other task on foray.

**Comment by aaronjudd** [comment] 2017-08-30 14:23
@awadesmoline is this in progress?

**Comment by awadesmoline** [comment] 2017-08-30 14:41
Yeah @aaronjudd, got stumped, but I'm getting back on it now since I finished up other tasks.

**Comment by rymorgan** [comment] 2017-09-22 20:20
This is very much still happening. In fact, I can't register as a new user at all. 

Might be related to: https://github.com/reactioncommerce/reaction/issues/2931

![register user](https://user-images.githubusercontent.com/20409254/30762886-a963a20c-9f98-11e7-8702-f8d1c27de12d.gif)

**Comment by aaronjudd** [comment] 2018-02-01 16:28
@zenweasel this should be reviewed, and prioritized in for @reactioncommerce/community

**Comment by prinzdezibel** [comment] 2018-02-08 10:46
Can't reproduce scenario B.  Works as expected when signing in or registering as new user. During user creation/login, the screen gets white for a couple of seconds, but aside from that, it works ok.

**Comment by prinzdezibel** [comment] 2018-02-08 11:09
Bug description for scenario A still holds true partially. When entering wrong credentials, unauthorized page is not shown any longer, but there's still no error message displayed.

**Comment by prinzdezibel** [comment] 2018-02-12 16:48
Approved via : https://github.com/reactioncommerce/reaction/pull/3664

**Comment by prinzdezibel** [comment] 2018-02-20 07:37
Was merged. Going to close.

**Closed by prinzdezibel** 2018-02-20 07:37 UTC
Labels: bug, impact-major, verified-reproducible
