### ISSUE TITLE
shop/currency reset to default on every Meteor rerun

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#548] opened 2015-12-06 09:59 UTC
Hello,
@tdecaluwe, this happens inside `ReactionImport.flush()` I suppose.

**Comment by tdecaluwe** [comment] 2015-12-07 23:22
The `ReactionImport.flush()` method just sends all the queries to mongodb. The query is still constructed in the `ReactionImport.shop()` method.

The problem is that for regular imports we want to overwrite data (concerning the same object) already in the database. To avoid this, the `ReactionImport.fixture()` method can be used which tells `ReactionImport` to use the `$setOnInsert` modifier when talking to the database.

**Comment by newsiberian** [comment] 2016-03-28 13:02
I have to re-open this issue, because shop currency still resetting after shop rerun. Even with turned off `reaction-sample-data` package.

**Comment by zenweasel** [comment] 2016-04-13 04:02
I am seeing this problem with shipping methods. Every time meteor restarts the shipping methods are reimported and assigned new _ids, which makes debugging issues with shipping methods nay impossible. Also a super bummer if you have changed any of the shipping values while developing.

Also this doesn't trigger a client reload so it allows the client and server to go out of sync.

**Comment by newsiberian** [comment] 2016-04-13 04:10
Confirmed. After I update `shipping.provider.enabled` to `false` (for testing purpose). Its revert back to `true` after reload.

**Comment by prinzdezibel** [comment] 2016-05-09 08:48
And also affects defaultPaymentMethod

**Comment by prinzdezibel** [comment] 2016-05-09 20:18
Has to do with the shop layout import in combination with the Shops schema. See screen:
![screenshot_09_05_16_22_13](https://cloud.githubusercontent.com/assets/1733229/15126782/fe0e346a-1633-11e6-8f06-b3632c34e3ee.jpg)

**Comment by prinzdezibel** [comment] 2016-05-09 20:20
A solution to the specific problem of this ticket is to omit the clean step. 

Comment out the following line in reaction-core/server/import.js :

>    //collection.simpleSchema(importObject).clean(importObject);

does fix the problem. But I don't know if this has any other unwanted side effects.

**Comment by tdecaluwe** [comment] 2016-05-09 20:53
I think omitting the clean step does have unwanted side effects since we do no longer ensure compliance with the schema. Also, we want the import to act like regular queries executed directly on the respective collections. I think we should be looking at how the cleaning mechanism interacts with the mongo `$setOnInsert` operator.

In the following line in `load.js` the `fixture()` method makes sure (or should make sure) the `$setOnInsert` operator is used:
```javascript
ReactionImport.fixture().process(..., ["name"], ReactionImport.shop);
```

The `name` field is used as a key to find the document to be upserted. 

I don't have time right now, but a good place to start might be to print the query that's being used when `ReactionImport.flush()` is being called? Then we could see which fields are being altered by the `SimpleSchema.clean()` method as well.

**Comment by zenweasel** [comment] 2016-05-17 01:46
Closed by https://github.com/reactioncommerce/reaction/commit/44fa8fa46e815b254d4448cdde3d70201a08b286

**Closed by zenweasel** 2016-05-17 01:46 UTC
Labels: in progress
