### ISSUE TITLE
Labels Missing in the Latest Version

### ISSUE THREAD

**Issue by newdesignideas** [reactioncommerce/reaction#1913] opened 2017-02-28 09:04 UTC
A copy of the issue highlighted in the forum post from here: https://forums.reactioncommerce.com/t/labels-not-showing-after-reaction-update/292 

Versions:

- Node:  6.9.5
- NPM: 3.10.10
- Docker: 1.13.1
- Reaction-Cli: 0.6.21

### Expected behavior

Install or update to the latest version of Reaction Commerce. Use "reaction" to start. Navigate around the site.

### Actual Behavior

The labels (text next to icons in various menus) are missing. See the screenshots below:

![First Screenshot](https://cloud.githubusercontent.com/assets/12444266/23398412/22691998-fda5-11e6-9182-602184734103.png)

![Second Screenshot](https://cloud.githubusercontent.com/assets/12444266/23398439/3dc188c4-fda5-11e6-80bc-4db8994ffcff.png)

### Steps to Reproduce the Behavior

Install or update to the latest version of Reaction Commerce. Use "reaction" to start. See that the labels are missing.

**Comment by zenweasel** [comment] 2017-02-28 09:08
@newdesignideas I answered your forum post with how to workaround this issue until we come up with a long-term fix.

Duplicate of #1908. Closing

**Closed by zenweasel** 2017-02-28 09:08 UTC
