### ISSUE TITLE
Research + present on running Kadira

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#3237] opened 2017-11-03 20:21 UTC
## Part of 
https://github.com/reactioncommerce/reaction/issues/3233

## Goal
- Write docs so anyone can run Kadira

**Comment by impactmass** [comment] 2017-11-15 17:40
While doing some testing on a fresh install with ~4k products, there's some lag that happens when as an admin a product is clicked on the product grid. It takes about 5 - 7 secs from the time the product is clicked to the time the admin sidebar opens up. 
Is part of the the things Kadira can give hints about?

**Comment by spencern** [comment] 2017-11-15 18:26
@impactmass yes, once we get Kadira setup it should be able to tell us what's going on on the server / db and the timing of all methods and db calls.

I don't think it reports on react components or client side timing (but maybe it does now?), so if the the lag is caused by an issue on the client, it may not point to the exact cause, but it should at the least be able to give us a place to start investigating.

**Comment by aaronjudd** [comment] 2018-01-12 19:05
Closing, removing from product roadmap.

**Closed by aaronjudd** 2018-01-12 19:05 UTC
Labels: performance
