### ISSUE TITLE
Translation missing on email connection failed message

### ISSUE THREAD

**Issue by sophiehe** [reactioncommerce/reaction#3697] opened 2018-02-09 01:38 UTC
### Expected behavior
Buttons should display translation, eg. 'Save' and 'Cancel.' 

### Actual behavior
![image](https://user-images.githubusercontent.com/20484811/36007224-633143f4-0cf6-11e8-8b96-85689754a665.png)

### Steps to reproduce the behavior
1. Click on Email.
2. Click on 'Mail Provider' settings icon.
3. Enter incorrect credentials into 'Edit Settings' fields.
4. Click 'Save.'

### Versions
Node: 6.5.0
NPM: 3.10.3
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.19.0
Reaction: 1.8.0
Reaction branch: release-1.8.0

**Comment by prinzdezibel** [comment] 2018-02-12 18:26
This is most probably a duplicate of: https://github.com/reactioncommerce/reaction/issues/3694

**Comment by zenweasel** [comment] 2018-02-12 22:51
I defer to however @spencern wants to handle it but I prefer keeping these in separate tickets and disagree they are "duplicates" since they talk about different parts of the app.

**Comment by prinzdezibel** [comment] 2018-02-13 12:31
Agree to keep them in separate tickets. I just mentioned it because it can possibly save some time if one would check that first.

**Comment by spencern** [comment] 2018-03-09 03:15
@prinzdezibel Is this still an issue?

**Comment by zenweasel** [comment] 2018-03-09 04:19
I just confirmed that this is no longer happening. Closing

**Closed by zenweasel** 2018-03-09 04:19 UTC
Labels: bug, i18n + l10n, impact-minor
