### ISSUE TITLE
product details page bad rendered on mobile divice

### ISSUE THREAD

**Issue by gpgmbh** [reactioncommerce/reaction#1679] opened 2016-12-30 20:39 UTC
product details page bad rendered on mobile divice, tested with develop branch.

**Comment by gpgmbh** [comment] 2016-12-30 22:45
the page redered right with iphone simulation of google developer tools. but redered bad with my iphone 6.

**Comment by gpmall** [comment] 2017-01-08 21:42
tested with safari on ios 8.3.

**Comment by gpmall** [comment] 2017-01-08 21:46
after update ios to 10.2. the issue is as https://github.com/reactioncommerce/reaction/issues/1695

Summary:

bad render of product details page with safari on ios 8.3.
safari flex-wrap not working with iso 10.2

**Comment by kieckhafer** [comment] 2017-01-18 00:05
We are closing this in favor of #1695.

**Closed** 2017-01-18 00:05 UTC
Labels: needs-to-be-reproduced, UIX
