### ISSUE TITLE
Checkout as Guest

### ISSUE THREAD

**Issue by faiizow** [reactioncommerce/reaction#183] opened 2014-10-16 19:18 UTC
Currently, a customer is required to be registered to purchase. Purchasing items as a guest is also a common feature of other e-commerce systems. I predict that this might be have to be implemented in core though, as opposed to a package.

**Comment by aaronjudd** [comment] 2015-01-18 22:29
@prinzdezibel since you mentioned you are working on a guest checkout, and volunteered - I'm assigning to you.

**Comment by prinzdezibel** [comment] 2015-01-18 22:38
I propose to integrate it into the core package, but hide the functionality behind a settings.json flag.

**Comment by aaronjudd** [comment] 2015-01-18 22:40
I agree,  I think that makes the most sense. I think it would be useful to enabled/disable in the shop settings UI as well.

**Comment by prinzdezibel** [comment] 2015-01-18 22:42
That would be even better as next improvement. Then the settings should go to a fixture data file (we talked about that already..)

**Comment by prinzdezibel** [comment] 2015-01-21 20:16
https://github.com/reactioncommerce/reaction-core/pull/76
https://github.com/reactioncommerce/reaction-core-theme/pull/5

**Comment by prinzdezibel** [comment] 2015-01-21 20:52
Would be happy to get some feedback. Please tell me if there are things that you guys want to have done in a different way. Thanks.

**Comment by aaronjudd** [comment] 2015-01-21 21:03
I'll wait for you to publish your accounts-guest package, OR you could add to the packages directory and I can fork the repo and take responsibility for publishing. 

The workflow is that a user must supply an email for the order, and that creates a Meteor user record? if so, maybe https://github.com/splendido/meteor-accounts-meld would help with that workflow.

**Comment by prinzdezibel** [comment] 2015-01-21 21:06
> The workflow is that a user must supply an email for the order, and that creates a Meteor user record?

That's correct.

>  if so, maybe https://github.com/splendido/meteor-accounts-meld would help with that workflow.

I'll have a look into it.

**Comment by aaronjudd** [comment] 2015-01-21 21:18
@aldeed I'm sort of wondering if this even needs the accounts-guest package, wouldn't it be just as easy to create a new temporary user when we create the reaction sessions? Also not sure how this is going to play with the session merging?

**Comment by prinzdezibel** [comment] 2015-01-21 21:50
@aaronjudd Package is published.

**Comment by aaronjudd** [comment] 2015-01-22 19:10
See #271 for discussion on guest account security.

**Comment by aaronjudd** [comment] 2015-01-22 20:44
Updated in branch so that canCheckoutAsGuest is a variable returned by app.coffee (ReactionCore.init), and moved into the `shops` schema, as well as added to admin 'shop settings' template.  Updated shops.json, and removed as public.settings variable.

**Comment by aaronjudd** [comment] 2015-02-26 20:02
work in progress with the following approach:

**Session management**

    if there is neither a sessionCart nor a userCart, create a sessionCart
    if sessionCart is a not a userCart return sessionCart
    if sessionCart just authenticated, add userId + email
       then copy existing userCart(s) into sessionCart and remove userCart(s)
    if sessionCart just logged out, remove sessionId from sessionCart and create new sessionCart
    

**Cart**

    add email as identifier
    auto insert/update userId, email if authenticated

**Checkout**

    change default step to guest checkout or login:
    store email for order
    add option to set password "create account" on order completion

**Accounts**

    use new Accounts collection (previously: customers)
    on account creation / login  with password, 
      if confirmed account creation email 
        create a customer collection record with this userId
        update all orders with matching email to match this userId
        copy all order addresses into Accounts.profile.addressBook
        copy all social / email info to Accounts.
        users collection locked down, nothing exposed to client, used for authentication only

      else
        if there are more orders with this email
        display on order view "Confirm email to link orders..."


**Order view**

    add message for confirmation of email
    authenticated user can see all orders where userId in list view
    userAccountsDropdown icon for orders

Related issues @aldeed @prinzdezibel

reactioncommerce/reaction#271
reactioncommerce/reaction#16
reactioncommerce/reaction#318
reactioncommerce/reaction#76

Remove packages introduced in reactioncommerce/reaction-core#76

**Comment by aldeed** [comment] 2015-02-27 21:11
> if sessionCart just logged out, remove sessionId from sessionCart and create new sessionCart

Wouldn't you want to delete the `sessionCart` and create a new blank one?

**Comment by aaronjudd** [comment] 2015-02-27 22:18
Yes, correct. that's what I've ended up doing.

**Closed** 2015-03-16 01:27 UTC
