### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory?

### ISSUE THREAD

**Issue by nsrtky** [reactioncommerce/reaction#3183] opened 2017-10-27 14:17 UTC
![image](https://user-images.githubusercontent.com/12385044/32108524-a86287ca-bb3a-11e7-9af1-e5dd51fbb459.png)

OS: Windowns 10 Enterprise 64 bits

reaction -v

Node: 6.11.4
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.19.1
Reaction: 1.5.4
Reaction branch: master

### Expected behavior
normal start app at 3000 port

### Actual behavior
fatal error

### Steps to reproduce the behavior
windows 10 enterprise 
1.install meteor
2.install reaction-cli
3.reaction init
4.reaction run.

**Comment by nsrtky** [comment] 2017-10-27 14:31
I have entered reaction directory and run meteor -v comment so app started run but show nothing.
here log file for your acknowledgment.

=> Started proxy.
Local package version is up-to-date: abernix:minifier-js@2.1.0
Local package version is up-to-date: abernix:standard-minifier-js@2.1.0
Local package version is up-to-date: accounts-base@1.3.6
Local package version is up-to-date: accounts-facebook@1.2.1
Local package version is up-to-date: accounts-google@1.2.0
Local package version is up-to-date: accounts-oauth@1.1.15
Local package version is up-to-date: accounts-password@1.4.2
Local package version is up-to-date: accounts-twitter@1.3.0
Local package version is up-to-date: alanning:roles@1.2.16
Local package version is up-to-date: aldeed:autoform@5.8.1
Local package version is up-to-date: aldeed:browser-tests@0.1.1
Local package version is up-to-date: aldeed:collection2@2.10.0
Local package version is up-to-date: aldeed:collection2-core@1.2.0
Local package version is up-to-date: aldeed:schema-deny@1.1.0
Local package version is up-to-date: aldeed:schema-index@1.1.1
Local package version is up-to-date: aldeed:simple-schema@1.5.3
Local package version is up-to-date: aldeed:template-extension@4.1.0
Local package version is up-to-date: allow-deny@1.0.9
Local package version is up-to-date: audit-argument-checks@1.0.7
Local package version is up-to-date: autoupdate@1.3.12
Local package version is up-to-date: babel-compiler@6.20.0
Local package version is up-to-date: babel-runtime@1.0.1
Local package version is up-to-date: base64@1.0.10
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.3.2
Local package version is up-to-date: blaze-html-templates@1.1.2
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.2.0
Local package version is up-to-date: bozhao:accounts-instagram@0.2.2
Local package version is up-to-date: browser-policy@1.1.0
Local package version is up-to-date: browser-policy-common@1.0.11
Local package version is up-to-date: browser-policy-content@1.1.0
Local package version is up-to-date: browser-policy-framing@1.1.0
Local package version is up-to-date: caching-compiler@1.1.9
Local package version is up-to-date: caching-html-compiler@1.1.2
Local package version is up-to-date: callback-hook@1.0.10
Local package version is up-to-date: cfs:access-point@0.1.49
Local package version is up-to-date: cfs:base-package@0.0.30
Local package version is up-to-date: cfs:collection@0.5.5
Local package version is up-to-date: cfs:collection-filters@0.2.4
Local package version is up-to-date: cfs:data-man@0.0.6
Local package version is up-to-date: cfs:file@0.1.17
Local package version is up-to-date: cfs:filesystem@0.1.2
Local package version is up-to-date: cfs:graphicsmagick@0.0.18
Local package version is up-to-date: cfs:http-methods@0.0.32
Local package version is up-to-date: cfs:http-publish@0.0.13
Local package version is up-to-date: cfs:power-queue@0.9.11
Local package version is up-to-date: cfs:reactive-list@0.0.9
Local package version is up-to-date: cfs:reactive-property@0.0.4
Local package version is up-to-date: cfs:standard-packages@0.5.9
Local package version is up-to-date: cfs:storage-adapter@0.2.3
Local package version is up-to-date: cfs:ui@0.1.3
Local package version is up-to-date: cfs:upload-http@0.0.20
Local package version is up-to-date: check@1.2.5
Local package version is up-to-date: coffeescript@1.12.7_3
Local package version is up-to-date: coffeescript-compiler@1.12.7_3
Local package version is up-to-date: dburles:factory@1.1.0
Local package version is up-to-date: ddp@1.3.1
Local package version is up-to-date: ddp-client@2.1.3
Local package version is up-to-date: ddp-common@1.2.9
Local package version is up-to-date: ddp-rate-limiter@1.0.7
Local package version is up-to-date: ddp-server@2.0.2
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.0.7
Local package version is up-to-date: dispatch:mocha@0.4.1
Local package version is up-to-date: dispatch:run-as-user@1.1.1
Local package version is up-to-date: dynamic-import@0.1.3
Local package version is up-to-date: ecmascript@0.8.3
Local package version is up-to-date: ecmascript-runtime@0.4.1
Local package version is up-to-date: ecmascript-runtime-client@0.4.3
Local package version is up-to-date: ecmascript-runtime-server@0.4.1
Local package version is up-to-date: ejson@1.0.14
Local package version is up-to-date: email@1.2.3
Local package version is up-to-date: es5-shim@4.6.15
Local package version is up-to-date: facebook-config-ui@1.0.0
Local package version is up-to-date: facebook-oauth@1.3.2
Local package version is up-to-date: gadicc:blaze-react-component@1.4.0
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: google-config-ui@1.0.0
Local package version is up-to-date: google-oauth@1.2.4
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.2.12
Local package version is up-to-date: id-map@1.0.9
Local package version is up-to-date:
johanbrook:publication-collector@1.0.10
Local package version is up-to-date: jparker:crypto-core@0.1.0
Local package version is up-to-date: jparker:crypto-md5@0.1.1
Local package version is up-to-date: jparker:gravatar@0.5.1
Local package version is up-to-date: jquery@1.11.10
Local package version is up-to-date: juliancwirko:postcss@1.2.0
Local package version is up-to-date: juliancwirko:s-alert@3.2.0
Local package version is up-to-date: juliancwirko:s-alert-stackslide@3.1.3
Local package version is up-to-date: kadira:dochead@1.5.0
Local package version is up-to-date: launch-screen@1.1.1
Local package version is up-to-date: less@2.7.9
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: localstorage@1.1.1
Local package version is up-to-date: logging@1.1.19
Local package version is up-to-date: matb33:collection-hooks@0.8.4
Local package version is up-to-date: mdg:validated-method@1.1.0
Local package version is up-to-date: mdg:validation-error@0.5.1
Local package version is up-to-date: meteor@1.7.2
Local package version is up-to-date: meteor-base@1.1.0
Local package version is up-to-date: meteorhacks:ssr@2.2.0
Local package version is up-to-date: meteorhacks:subs-manager@1.6.4
Local package version is up-to-date: minifier-css@1.2.16
Local package version is up-to-date: minimongo@1.3.3
Local package version is up-to-date: mobile-experience@1.0.5
Local package version is up-to-date: mobile-status-bar@1.0.14
Local package version is up-to-date: modules@0.10.0
Local package version is up-to-date: modules-runtime@0.8.0
Local package version is up-to-date: momentjs:moment@2.18.1
Local package version is up-to-date: mongo@1.2.2
Local package version is up-to-date: mongo-dev-server@1.0.1
Local package version is up-to-date: mongo-id@1.0.6
Local package version is up-to-date: mongo-livedata@1.0.12
Local package version is up-to-date: mrt:later@1.6.1
Local package version is up-to-date: natestrauser:select2@4.0.3
Local package version is up-to-date: npm-bcrypt@0.9.3
Local package version is up-to-date: npm-mongo@2.2.33
Local package version is up-to-date: oauth@1.1.13
Local package version is up-to-date: oauth-encryption@1.2.1
Local package version is up-to-date: oauth1@1.1.11
Local package version is up-to-date: oauth2@1.1.11
Local package version is up-to-date: observe-sequence@1.0.16
Local package version is up-to-date: ongoworks:security@2.1.0
Local package version is up-to-date: ordered-dict@1.0.9
Local package version is up-to-date: percolate:migrations@0.9.8
Local package version is up-to-date: practicalmeteor:chai@2.1.0_1
Local package version is up-to-date: practicalmeteor:mocha-core@1.0.1
Local package version is up-to-date: practicalmeteor:sinon@1.14.1_2
Local package version is up-to-date: promise@0.9.0
Local package version is up-to-date: raix:eventemitter@0.1.3
Local package version is up-to-date: raix:ui-dropped-event@0.0.7
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: rate-limit@1.0.8
Local package version is up-to-date: react-meteor-data@0.2.9
Local package version is up-to-date: reactive-dict@1.1.9
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.1.11
Local package version is up-to-date: retry@1.0.9
Local package version is up-to-date: routepolicy@1.0.12
Local package version is up-to-date: service-configuration@1.0.11
Local package version is up-to-date: session@1.1.7
Local package version is up-to-date: sha@1.0.9
Local package version is up-to-date: shell-server@0.2.4
Local package version is up-to-date: spacebars@1.0.15
Local package version is up-to-date: spacebars-compiler@1.1.3
Local package version is up-to-date: srp@1.0.10
Local package version is up-to-date: templating@1.3.2
Local package version is up-to-date: templating-compiler@1.3.3
Local package version is up-to-date: templating-runtime@1.3.2
Local package version is up-to-date: templating-tools@1.1.2
Local package version is up-to-date: tmeasday:check-npm-versions@0.3.1
Local package version is up-to-date: tmeasday:publish-counts@0.8.0
Local package version is up-to-date: tracker@1.1.3
Local package version is up-to-date: twitter-config-ui@1.0.0
Local package version is up-to-date: twitter-oauth@1.2.0
Local package version is up-to-date: ui@1.0.13
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.1.0
Local package version is up-to-date: vsivsi:job-collection@1.4.0
Local package version is up-to-date: webapp@1.3.19
Local package version is up-to-date: webapp-hashing@1.0.9
=> Started MongoDB.
[34mW20171027-17:28:33.871(3)? (STDERR) [39m[35mNote: you are using a pure-JavaScript implementation of bcrypt.[39m
[34mW20171027-17:28:33.960(3)? (STDERR) [39m[35mWhile this implementation will work correctly, it is known to be[39m
[34mW20171027-17:28:33.961(3)? (STDERR) [39m[35mapproximately three times slower than the native implementation.[39m
[34mW20171027-17:28:33.962(3)? (STDERR) [39m[35mIn order to use the native implementation instead, run[39m
[34mW20171027-17:28:33.962(3)? (STDERR) [39m[35m[39m
[34mW20171027-17:28:33.963(3)? (STDERR) [39m[35m  meteor npm install --save bcrypt[39m
[34mW20171027-17:28:33.964(3)? (STDERR) [39m[35m[39m
[34mW20171027-17:28:33.964(3)? (STDERR) [39m[35min the root directory of your application.[39m
[34mW20171027-17:28:33.965(3)? (STDERR) [39m[35mWARNING:[39m
[34mW20171027-17:28:33.965(3)? (STDERR) [39m[35mcfs:graphicsmagick could not find "graphicsMagic" or "imageMagic" on the[39m
[34mW20171027-17:28:33.966(3)? (STDERR) [39m[35msystem.[39m
[34mW20171027-17:28:33.967(3)? (STDERR) [39m[35m[39m
[34mW20171027-17:28:33.967(3)? (STDERR) [39m[35mI just checked PATH to see if I could find the GraphicsMagick or ImageMagic[39m
[34mW20171027-17:28:33.968(3)? (STDERR) [39m[35munix/mac os/windows binaries on your system, I failed.[39m
[34mW20171027-17:28:33.968(3)? (STDERR) [39m[35m[39m
[34mW20171027-17:28:33.969(3)? (STDERR) [39m[35mWhy:[39m
[34mW20171027-17:28:33.969(3)? (STDERR) [39m[35m1. I may be blind or naive, help making me smarter[39m
[34mW20171027-17:28:33.970(3)? (STDERR) [39m[35m2. You havent added the path to the binaries[39m
[34mW20171027-17:28:33.971(3)? (STDERR) [39m[35m3. You havent actually installed GraphicsMagick or ImageMagick[39m
[34mW20171027-17:28:33.971(3)? (STDERR) [39m[35m[39m
[34mW20171027-17:28:33.972(3)? (STDERR) [39m[35m*** Make sure "$PATH" environment is configured "PATH:/path/to/binaries" ***[39m
[34mW20171027-17:28:33.972(3)? (STDERR) [39m[35m[39m
[34mW20171027-17:28:33.973(3)? (STDERR) [39m[35mInstallation hints:[39m
[34mW20171027-17:28:33.973(3)? (STDERR) [39m[35m* Mac OS X "brew install graphicsmagick" or "brew install imagemagick"[39m
[34mW20171027-17:28:33.974(3)? (STDERR) [39m[35m* Linux download rpm or use packagemanager[39m
[34mW20171027-17:28:33.975(3)? (STDERR) [39m[35m* Centos "yum install GraphicsMagick"* Windows download the installer and run[39m
[34mI20171027-17:28:33.976(3)? [39m[90m14:28:23.264Z[39m [32m INFO[39m Reaction: [36mLoad default data from /private/data/[39m
[34mI20171027-17:28:33.976(3)? [39m[90m14:28:23.352Z[39m [32m INFO[39m Reaction: [36mJobServer started[39m
[34mI20171027-17:28:33.977(3)? [39m[90m14:28:23.361Z[39m [35m WARN[39m Reaction: [36mSkipped loading settings from reaction.json.[39m
[34mI20171027-17:28:33.977(3)? [39m[90m14:28:23.493Z[39m [32m INFO[39m Reaction: [36mReaction Version: 1.5.4[39m
[34mI20171027-17:28:33.977(3)? [39m[90m14:28:23.518Z[39m [32m INFO[39m Reaction: [36mReaction initialization finished.[39m
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

**Comment by zenweasel** [comment] 2017-10-27 21:13
@nsrtky What OS are you on and can you let me know what the results of `reaction -v` are?

**Comment by nsrtky** [comment] 2017-10-30 07:14
OS: Windowns 10 Enterprise 64 bits

reaction -v 

Node: 6.11.4
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.19.1
Reaction: 1.5.4
Reaction branch: master

**Comment by zsavicreative** [comment] 2017-11-05 14:21
umm, not sure if this helps cause I'm a nub by all counts, but I'm running similar environment to nsrtky and getting the same error.

Win 10 64bit
and reaction -v results:

Node: 6.11.3
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.20.0
Reaction: 1.5.6
Reaction branch: master

**Comment by sellomkantjwa** [comment] 2017-11-06 21:31
Also getting the same issue:
Node: 6.9.1
NPM: 3.10.8
Meteor Node: 8.8.1
Meteor NPM: 5.4.2
Reaction CLI: 0.20.0
Reaction: 1.5.6
Reaction branch: master
Docker: 17.09.0-ce
Memory peaks at about a gig and then the process just crashes

**Comment by jshimko** [comment] 2017-11-07 13:46
This is a duplicate of #3023.  I think we should probably close this and move the conversation there so we can have it all in one place.  

But the short answer is try using the `TOOL_NODE_FLAGS` environment variable to set the amount of RAM the Meteor tool can use for the build.

```sh
# You can try messing with the amount, but FYI, more is not necessarily better
export TOOL_NODE_FLAGS="--max-old-space-size=2048"

# start Reaction
reaction
```

See also...

https://stackoverflow.com/questions/16586705/configuring-v8s-memory-management-to-be-smart-for-a-node-js-process/16591881#16591881

It's a little outdated and the default amounts probably aren't correct anymore, but it has been confirmed to solve the above problem.  The only issue is that it appears to behave differently on different machines or OS's and you need to mess with the amount.

**Closed by jshimko** 2017-11-07 13:46 UTC

**Comment by zsavicreative** [comment] 2017-11-07 14:47
so just to clarify my understanding of that stackoverflow post, does that mean this is mainly due to way reaction has been set up? not splitting single processes into several workers accordingly?  forgive the nub question, I always assume that my understanding of something is wrong before I reach the another conclusion.

**Comment by jshimko** [comment] 2017-11-07 18:35
No, it means that the Reaction build (which is performed by Meteor) is a single process.  And that's not really optional because it has to happen in a specific order.

See my additional updates from earlier today here https://github.com/reactioncommerce/reaction/issues/3023#issuecomment-342510093
