### ISSUE TITLE
Changes to top level products doesn't enable publish button

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3881] opened 2018-03-02 05:02 UTC
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
Changing a top level product, either by updating the grid layout or by changing properties on the product does not enable the "Publish" button. On the grid, the product is shown with a teal icon indicating that there is a change, but the publish button is not enabled preventing the user from publishing the changes.

On the PDP, changing details of the top level product does not enable the publish button, making it impossible to publish details of the product. For some reason, toggling the visibility 3+ times will enable the publish button, permitting publishing of the other changes as well.

<img src="http://g.recordit.co/YwfCa1PGck.gif">

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. As an admin
2. On the PDP, add several images to a product.
3. On the product grid, clone the product several times
4. On the product grid, change the layout used for a particular product. It should now have the revision icon. Note that the publish button stays disabled.
5. Visit the PDP for a different product. Change the title. Notice that the publish button is still disabled.
6. From the PDP, toggle the visibility of this product 3 or more times, the publish button should be enabled now.

## Possible Solution
I think this may end up getting fixed as part of @mikemurray and @nnnnat's work on #3877 and #3662 
Consult with them before starting work on this issue.

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.8.2
Reaction branch: master
Docker: 17.12.0-ce
```

**Comment by zenweasel** [comment] 2018-03-02 05:04
@spencern Could this be a dupe of https://github.com/reactioncommerce/reaction/issues/3851

**Comment by spencern** [comment] 2018-03-02 05:34
@zenweasel it does seem very similar, though this issue also deals with the product grid.

**Comment by zenweasel** [comment] 2018-03-02 05:37
@spencern Can you try it with https://github.com/reactioncommerce/reaction/pull/3857 applied and see if you issue is resolved? If not then edit the issue for just that behavior? I don't really see anything here besides "I can't publish"

**Comment by zenweasel** [comment] 2018-03-02 05:37
Maybe that PR doesn't touch all the places there diffs are being created.

**Comment by Akarshit** [comment] 2018-03-06 18:58
This issue is not reproducible after merging #3857.

**Comment by zenweasel** [comment] 2018-03-08 04:06
I also cannot reproduce this issue on `release-1.9.0`. I'm closing but please reopen if you run into it again.

**Closed by zenweasel** 2018-03-08 04:06 UTC
Labels: bug, impact-major
