### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#105] opened 2014-06-15 18:44 UTC
As a user and as a shop administrator, I want to be able to search for products by tag/keyword across the whole store.

**Comment by ScyDev** [comment] 2016-02-06 15:51
This is ready? It's two years old and breaks with "Uncaught TypeError: ReactionCore.registerPackage is not a function".

**Comment by aaronjudd** [comment] 2016-02-06 18:01
`ready` as in: "the issue is ready to be worked".... in our road map. The existing `reaction-search` package was probably won't work without some upgrades, and probably isn't really in line with how we are going to do it now.  We'll be adding into /reaction/packages by v0.13

**Comment by ramusus** [comment] 2016-02-06 20:49
@ScyDev you may take a look https://github.com/ramusus/reaction-filtration/ it supports simple search by title and filtration functionality. You can integrate with current dev version, using this PR reactioncommerce#743

**Comment by aaronjudd** [comment] 2016-03-11 03:34
Closing in favor of #903 and #277

**Closed by aaronjudd** 2016-03-11 03:34 UTC
Labels: ready
