### ISSUE TITLE
Inventory Tracking Backorders

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#1935] opened 2017-03-03 20:09 UTC
Inventory tracking for backorders only gives the maximum available quantity, not the quantity requested by the user.

### Expected behavior

Expect 20 item in cart, 19 of which should be backordered.

### Actual Behavior

Got 1

### Steps to Reproduce the Behavior

1. Create product
2. Add a top level variant
3. Add 1 quantity
4. Disable `Deny when out of stock`
5. Publish product and variant
6. Purchase 2 or more of that variant
7. Check cart has only one of the amount you ordered

**Comment by zenweasel** [comment] 2017-03-03 22:43
Pretty sure this is a duplicate (or at least a strong overlap) of https://github.com/reactioncommerce/reaction/issues/1928

I think the issue is that when a user place things into the cart they are not "reserved", so the same calculation for available is used every time. Which brings up the question of do we deny someone else to add something to cart because another user has already added it to their cart. Which brings up when do we remove something from a cart if it gets abandoned.

**Comment by joykare** [comment] 2017-03-21 08:38
I get an error everytime I try purchasing variants even after I publish the changes.

**Comment by joykare** [comment] 2017-03-27 19:30
Update: Error was my bad __ Didnt make products visible.

**Comment by tdmoneybanks** [comment] 2017-03-30 15:26
i would suggest doing this similar to amazon: allow both users to add item to their cart and leave it there. When one user checks out and purchases the item, notify the  other user, in  their cart and checkout page, that the item in their cart that was purchased by the other user either has a price change or is now on backorder.

**Comment by zenweasel** [comment] 2017-04-04 22:38
Closed via #2048

**Closed by zenweasel** 2017-04-04 22:38 UTC
Labels: inventory, needs-to-be-reproduced, review
