### ISSUE TITLE
reaction init produces error on Windows 8.1

### ISSUE THREAD

**Issue by LukasNavickas** [reactioncommerce/reaction#3191] opened 2017-10-29 16:25 UTC
### Expected behavior
start "reaction init"
### Actual behavior
error
### Steps to reproduce the behavior
reaction init on Windows

Meteor, Python and Windows Build Tools are installed

```

npm ERR! git clone C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.5.
2_2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncom
merce-transliteration-git-5ec7c7d9 C:\Users\User\AppData\Local\Temp\npm-5160-206
9317c\git-cache-e12d1889\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: Cloning into
'C:\Users\User\AppData\Local\Temp\npm-5160-2069317c\git-cache-e12d1889\699d48cc8
dd9a64f1a2773e1b36b6faa4bbdca2f'...
npm ERR! git clone C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.5.
2_2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncom
merce-transliteration-git-5ec7c7d9 C:\Users\User\AppData\Local\Temp\npm-5160-206
9317c\git-cache-e12d1889\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: error: cannot
 spawn sh: No such file or directory
npm ERR! git clone C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.5.
2_2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncom
merce-transliteration-git-5ec7c7d9 C:\Users\User\AppData\Local\Temp\npm-5160-206
9317c\git-cache-e12d1889\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: fatal: unable
 to fork
npm ERR! git clone C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.5.
2_2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncom
merce-transliteration-git-5ec7c7d9 C:\Users\User\AppData\Local\Temp\npm-5160-206
9317c\git-cache-e12d1889\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f:
npm ERR! git fetch -a origin (https://github.com/reactioncommerce/transliteratio
n.git) fatal: Unable to find remote helper for 'https'
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:200:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:862:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:222:5)
npm WARN addRemoteGit  reactioncommerce/transliteration resetting remote C:\User
s\User\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\d
ev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-
8d5184dd because of error: { [Error: Command failed: git -c core.longpaths=true
config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\User\AppData\Local\.meteor\packages\meteo
r-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\_templates --mi
rror git@github.com:reactioncommerce/transliteration.git C:\Users\User\AppData\L
ocal\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\.npm\_
git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd: Clonin
g into bare repository 'C:\Users\User\AppData\Local\.meteor\packages\meteor-tool
\1.5.2_2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reacti
oncommerce-transliteration-git-8d5184dd'...
npm ERR! git clone --template=C:\Users\User\AppData\Local\.meteor\packages\meteo
r-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\_templates --mi
rror git@github.com:reactioncommerce/transliteration.git C:\Users\User\AppData\L
ocal\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\.npm\_
git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd: error:
 cannot spawn ssh: No such file or directory
npm ERR! git clone --template=C:\Users\User\AppData\Local\.meteor\packages\meteo
r-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\_templates --mi
rror git@github.com:reactioncommerce/transliteration.git C:\Users\User\AppData\L
ocal\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\.npm\_
git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd: fatal:
 unable to fork
npm ERR! code 128
npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Us
er\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_b
undle\.npm\_git-remotes\_templates --mirror git@github.com:reactioncommerce/tran
sliteration.git C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2
\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommer
ce-transliteration-git-8d5184dd
npm ERR! Cloning into bare repository 'C:\Users\User\AppData\Local\.meteor\packa
ges\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-gi
thub-com-reactioncommerce-transliteration-git-8d5184dd'...
npm ERR! error: cannot spawn ssh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt
-os.windows.x86_32\dev_bundle\.npm\_logs\2017-10-29T15_50_53_993Z-debug.log
```

**Comment by jshimko** [comment] 2017-10-29 16:53
Do you have OpenSSH installed?  I'm pretty sure that's a requirement of git.  It looks like all of the errors there are related to ssh commands failing (which is one of the ways a `git clone` pulls down a repo).

**Comment by jshimko** [comment] 2017-10-29 16:56
You can also try using the git command directly to isolate `reaction-cli` from the problem.

```sh
git clone https://github.com/reactioncommerce/reaction.git
```

**Comment by LukasNavickas** [comment] 2017-10-29 17:52
1. Didn't find any tutorials on how to install OpenSSH on Windows 8. Do you know any? 
2. I tried doing "git clone ... " successfully. Then I entered the reaction folder and executed "meteor npm install" successfully. I tried to launch it with "reaction", but it gets stuck at "Started Proxy -> Started MongoDB". Waiting for 10 minutes, nothing happens.

**Comment by jshimko** [comment] 2017-10-29 18:00
1. https://www.google.com/search?q=windows+openssh+install

2. Are you positive there were no errors on the `git clone` or the `meteor npm install`?  Can you share the log output?

**Comment by LukasNavickas** [comment] 2017-10-29 20:15
I could install OpenSSH, restarted my PC and tried to do "reaction init" again. This time, I didn't get the error from above, but the whole process stopped (actually it was running for ages), at:

```
Cloning the master branch of Reaction from Github...
Cloning into 'reaction'...
Checking out files: 100% (2534/2534), done.

Installing NPM packages...
npm WARN prefer global marked@0.3.6 should be installed with -g

> dtrace-provider@0.8.5 install C:\Lukas\Programavimas\reaction\node_modules\dt
ace-provider
> node scripts/install.js


> fibers@2.0.0 install C:\Lukas\Programavimas\reaction\node_modules\fibers
> node build.js || nodejs build.js
```

I have stopped the process, entered the "reaction" folder and executed "reaction". After few minutes I got the messages "Started proxy" and "Started MongoDB". After about 20 more minutes, I got the error "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory". If you can tell me how can I access the full log, I could paste it here too.

```
Using settings file at settings/dev.settings.json

Setting up plugin imports...

Installing dependencies for connectors-shopify...

npm WARN reaction-connectors-shopify@1.0.0 No repository field.
Setting up style imports...

[[[[[ C:\Lukas\Programavimas\reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
cfs:tempstore: updating npm dependencies -- combined-stream...
cfs:gridfs: updating npm dependencies -- mongodb, gridfs-stream...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

**Comment by stoil** [comment] 2017-10-31 14:33
I have the exact same problem like @LukasNavickas . 
Following the installation guide and after everything installed correctly. Running the **reaction run** command on Windows 10 machine, outputs the following:
```
[[[[[ ~\D\Side\B\REACTION\reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
cfs:tempstore: updating npm dependencies -- combined-stream...
cfs:gridfs: updating npm dependencies -- mongodb, gridfs-stream...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```
or in other situations it just freezes on 
```
=> Started proxy.
```
and then outputs the same error as above

```
Node: 6.11.0
NPM: 3.10.10
Meteor Node: 8.8.1
Meteor NPM: 5.4.2
Reaction CLI: 0.19.1
Docker: 17.09.0-ce
```

**Comment by LukasNavickas** [comment] 2017-11-03 18:43
@jshimko any solution to this problem? Many users encounter it as far as I can see.

**Comment by mulianto** [comment] 2017-11-05 11:21
I have the same problem, settings environment variable TOOL_NODE_FLAGS = --max-old-space-size=1024 taking care of the issue with FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory. 

The issue I have now is the client see only empty page when running http://localhost:3000

Here is the server console looks like:

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Installing dependencies for connectors-shopify...

npm WARN reaction-connectors-shopify@1.0.0 No repository field.
Setting up style imports...

[[[[[ c:\Users\Mulianto\reaction ]]]]]

=> Started proxy.
=> Meteor 1.6 is available. Update this project with 'meteor update'.
=> Started MongoDB.
04:03:40.208Z  INFO Reaction: Load default data from /private/data/
04:03:40.347Z  INFO Reaction: JobServer started
04:03:40.358Z  WARN Reaction: Skipped loading settings from reaction.json.
04:03:42.553Z  INFO Reaction: Reaction Version: 1.5.6
04:03:42.647Z  WARN Reaction: OpenExchangeRates API not configured. Not adding fetchRates job
04:03:42.651Z  WARN Reaction: OpenExchangeRates API not configured. Not adding flushRates job
04:03:42.899Z  INFO Reaction: Reaction initialization finished.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

On The client side:
when open up the browser http://localhost:3000/ it return empty page.

Any idea what's going wrong on with my installation?

**Comment by mulianto** [comment] 2017-11-05 11:23
Here is the version I use:

Node: 8.3.0
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.20.0
Reaction: 1.5.6
Reaction branch: master

**Comment by mulianto** [comment] 2017-11-05 12:15
found the issue. Run: "npm install" works, instead of "meteor npm install"

**Comment by jshimko** [comment] 2017-11-07 20:30
Now that we know the OpenSSH issue was the first issue, the rest of this is a duplicate of #3183.  Specifically, take a look at all of the comments from earlier today.  

For the sake of organization, I'm closing this issue in favor of #3183.

**Closed by jshimko** 2017-11-07 20:30 UTC
