### ISSUE TITLE
Address form left in an incorrect state after adding an address

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4650] opened 2018-09-20 22:01 UTC
## Issue Description

Address form is still presented as the "add new address" form after submitting a new address. Refreshing resolved the issue.

![cart_checkout](https://user-images.githubusercontent.com/42217/45848949-28a16a80-bce5-11e8-93fd-b96e3bf34d39.png)

## Steps to Reproduce

1. With a fresh reaction, as an anonymous user
2. Add items to the cart & checkout
3. Continue as guest
4. Enter a valid email address
5. Enter your shipping address
6. Click the `is commercial` checkbox

### Versions

staging - release 2.0.0

**Comment by zenweasel** [comment] 2018-09-20 23:33
I also saw this and see this error in the browser console
```
Error: No Template["examplePaymentForm"] exists.  If this template originates in your app, make sure you have the `templating` package installed (and not, for e.g. `static-html`)
```

**Comment by aldeed** [comment] 2018-09-21 04:04
That error means migration 39 didn't run properly. If that's the cause, there isn't a bug here.

**Comment by zenweasel** [comment] 2018-09-21 04:10
This is happening on Staging and is still happening. I haven't replicated it locally but can do that

**Comment by aldeed** [comment] 2018-09-21 16:32
It would be good to look in the staging logs and see if there's a server error corresponding with this happening. I'm guessing a failure on the server during the workflow push.

**Comment by spencern** [comment] 2018-12-08 02:43
@nnnnat @mikemurray is this an issue in the reference nextjs storefront?

**Comment by aldeed** [comment] 2018-12-13 21:16
This was only in classic UI iirc

**Comment by spencern** [comment] 2018-12-18 02:51
Closing as it's only an issue in the classic UI.

**Closed by spencern** 2018-12-18 02:51 UTC
Labels: bug
