### ISSUE TITLE
Can not change Language on website

### ISSUE THREAD

**Issue by tkdanhpro** [reactioncommerce/reaction#1915] opened 2017-02-28 10:21 UTC
I can not change language on website. can anybody help me please?

**Comment by zenweasel** [comment] 2017-02-28 10:27
You can use the language dropdown here:

![basic_reaction_product](https://cloud.githubusercontent.com/assets/72819/23401647/6741badc-fde3-11e6-8f47-003e4873ac12.png)

Closing

**Closed by zenweasel** 2017-02-28 10:27 UTC

**Comment by tkdanhpro** [comment] 2017-02-28 10:29
I did like that and nothing happened. Only English

**Comment by zenweasel** [comment] 2017-02-28 10:31
Please note that when you change languages, this doesn't change the text that product info is in, just the text for the application itself.

![basic_reaction_product](https://cloud.githubusercontent.com/assets/72819/23401841/185b9eaa-fde4-11e6-965f-6bed9010c82c.png)

**Comment by tkdanhpro** [comment] 2017-02-28 11:32
​I changed language to Espanol then reloaded website. But language was not
change and you see "Select language" instead "Elegir idioma". Many thanks!

2017-02-28 17:31 GMT+07:00 Brent Hoover <notifications@github.com>:

**Comment by zenweasel** [comment] 2017-02-28 11:36
Not sure what could be happening. I can't replicate that error:

![basic_reaction_product](https://cloud.githubusercontent.com/assets/72819/23403846/fbf0f392-fdec-11e6-9727-0656281d8d0e.png)

Where are you running this? Possibly your translations didn't get loaded somehow.

**Comment by tkdanhpro** [comment] 2017-02-28 11:41
I git clone this project from https://github.com/reactioncommerce/reaction
to run and have not changed. Could you show me links of your project sir?
thanks so much

2017-02-28 18:36 GMT+07:00 Brent Hoover <notifications@github.com>:

**Comment by zenweasel** [comment] 2017-02-28 11:42
No, I am running this locally. So are you running this locally or on a server?

**Comment by tkdanhpro** [comment] 2017-02-28 11:46
I'm running in localhost. I have suffered  this problem for 3 days and no
idea to fix it

2017-02-28 18:42 GMT+07:00 Brent Hoover <notifications@github.com>:

**Comment by zenweasel** [comment] 2017-02-28 11:53
Please try doing `reaction reset`

**Comment by tkdanhpro** [comment] 2017-02-28 12:11
Yes I did. I tried to reinstall many times on ubuntu and OSX, but have the
same problem.

2017-02-28 18:53 GMT+07:00 Brent Hoover <notifications@github.com>:

**Comment by zenweasel** [comment] 2017-02-28 12:12
Are the translations loaded in your mongo db?

**Comment by tkdanhpro** [comment] 2017-02-28 13:45
Yes. Translations are in private/data/i18n with 18 languages. But when i
delete file translation en.json in i18n, the website is still display
english.

2017-02-28 19:12 GMT+07:00 Brent Hoover <notifications@github.com>:

**Comment by aaronjudd** [comment] 2017-02-28 14:40
@zenweasel I think this is a duplicate of #1910?

**Comment by tkdanhpro** [comment] 2017-02-28 14:48
OK sir. I will try. Thank for your help! Have a good night! :D

2017-02-28 21:40 GMT+07:00 Aaron Judd <notifications@github.com>:

**Comment by tkdanhpro** [comment] 2017-03-02 06:03
Hello sir,


2017-02-28 21:47 GMT+07:00 T. K.D <tkdanhpro@gmail.com>:

**Comment by tkdanhpro** [comment] 2017-03-02 06:04
Hello sir,
what can i do to show Footer on website? I can't see any html code here.
Sorry but my english is not good.

2017-03-02 13:02 GMT+07:00 T. K.D <tkdanhpro@gmail.com>:

**Comment by zenweasel** [comment] 2017-03-02 06:09
@tkdanhpro It would be better for further support if you went to the Gitter channel, which I believe you are already in.

https://gitter.im/reactioncommerce/reaction

**Comment by tkdanhpro** [comment] 2017-03-02 06:12
yes sir, I am in gitter channel

2017-03-02 13:09 GMT+07:00 Brent Hoover <notifications@github.com>:
