### ISSUE TITLE
Bower jquery.payment not found

### ISSUE THREAD

**Issue by lukefrake** [reactioncommerce/reaction#704] opened 2016-01-15 14:35 UTC
Hey everybody,

I'm sure I'm doing something very stupid here.

I've been following the developer getting started guide, but I'm gettin an error of `Bower:  { [Error: Package jquery.payment not found] stack: [Getter] }` which then makes the build fail.

Is this a me problem? If so, does anybody have an idea of what foolish thing I'm doing wrong?

**Comment by lukefrake** [comment] 2016-01-15 14:37
I have another error message that shows after this of

```
=> Errors prevented startup:                  
   
   While building package reactioncommerce:core:
   packages/bower/plugin/handler.js:209:1: Cannot read property 'name' of undefined
   (compiling lib/bower.json)
   at getDependencies (packages/bower/plugin/handler.js:209:1)
   at packages/bower/plugin/handler.js:220:1
   at Function._.each._.forEach
   (packages/underscore/packages/underscore.js:142:1)
   at getDependencies (packages/bower/plugin/handler.js:219:1)
   at bowerHandler (packages/bower/plugin/handler.js:76:1)
   at Package (packages/bower/plugin/handler.js:262:1)
   
   error: File not found: lib/bower/jquery.ui/ui/core.js
   error: File not found: lib/bower/jquery.ui/ui/widget.js
   error: File not found: lib/bower/jquery.ui/ui/mouse.js
   error: File not found: lib/bower/jquery.ui/ui/position.js
   error: File not found: lib/bower/jquery.ui/ui/autocomplete.js
   error: File not found: lib/bower/jquery.ui/ui/sortable.js
   error: File not found: lib/bower/jquery.ui/ui/draggable.js
   error: File not found: lib/bower/jquery.ui/ui/droppable.js
   error: File not found: lib/bower/jquery.ui/ui/effect.js
   error: File not found: lib/bower/jquery.ui/ui/effect-slide.js
   error: File not found: lib/bower/jquery.ui/ui/menu.js
   error: File not found: lib/bower/autosize/dist/autosize.js
   error: File not found: lib/bower/openexchangerates.accounting/accounting.min.js
   error: File not found: lib/bower/openexchangerates.money/money.js
   error: File not found: lib/bower/jquery.tagsinput/dist/jquery.tagsinput.min.css
```

**Comment by aaronjudd** [comment] 2016-01-15 23:26
@lukefrake  We have some updated docs here that might help: https://docs.reactioncommerce.com/reaction-docs/development/requirements

This error is caused by Bower having not downloaded dependencies - so if you are on Windows you might be missing Git + msysGit.

You might also just try doing `reaction reset && reaction` - that will delete anything already downloaded and restart.

**Comment by aaronjudd** [comment] 2016-01-20 01:23
@lukefrake Hopefully this worked for you, and you were able to install everything. Closing for now.

**Comment by dio007** [comment] 2016-01-20 18:12
i'm having the same problem on ubuntu!

**Comment by zenweasel** [comment] 2016-01-25 09:02
I installed Reaction today on Ubuntu and did not run into this issue. However I was working with a user who did see this error message but it did not stop him from starting Reaction. So I am tending to chalk it up to maybe some flakiness with Bower?

**Closed** 2016-02-18 20:11 UTC
Labels: question
