### ISSUE TITLE
Not able to run tests

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#512] opened 2015-11-04 09:51 UTC
When do meteor --test
getting the error:
failed to subscribe to VelocityTestReports subscription
failed to subscribe to VelocityAggregateReports subscription
failed to subscribe to VelocityMirrors subscription { [Error: Subscription not found [404]]
error: 404,
reason: 'Subscription not found',
details: undefined,
message: 'Subscription not found [404]',
errorType: 'Meteor.Error' }

How to proceed here. Please help.

**Comment by aaronjudd** [comment] 2015-11-05 23:05
From Gitter chat: https://gitter.im/reactioncommerce/reaction?at=563ad1f3a530033014e4631c

@hrath2015 how are you running, starting tests? command line? can paste here?

**Comment by tdecaluwe** [comment] 2015-11-05 23:32
I've been seeing this lately as well. Don't remember why or how. Can you post the output of running `meteor list`?

**Comment by hrath2015** [comment] 2015-11-06 06:03
@aaronjudd 
It is Windows 7. From Command Line, in application directory. Run meteor --test
D:\Devprojects\reaction>meteor --test

@tdecaluwe 
Below is  the output of meteor list. Tried to attach as a file. Could not do becoz of permissions.

accounts-facebook                         1.0.6  Login service for Facebook accounts
audit-argument-checks                     1.0.4  Try to detect inadequate input sanitization
blaze-html-templates                      1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
check                                     1.0.6* Check whether a value matches a pattern
ecmascript                                0.1.5* Compiler plugin that supports ES2015+ in all .js files
ejson                                     1.0.7  Extended and Extensible JSON library
es5-shim                                  4.1.13* Shims and polyfills to improve ECMAScript 5 support
jquery                                    1.11.4  Manipulate the DOM using CSS selectors
less                                      2.5.0_3* Leaner CSS language
logging                                   1.0.8  Logging facility.
meteor-base                               1.0.1  Packages that every Meteor app needs
mobile-experience                         1.0.1  Packages for a great mobile user experience
mongo                                     1.1.2* Adaptor for using MongoDB and Minimongo over DDP
nemo64:bootstrap                          3.3.5_2  Highly configurable bootstrap integration.
random                                    1.0.4* Random number generator and utilities
reactioncommerce:bootstrap-theme          1.7.0+ Reaction Commerce Bootstrap theme builder
reactioncommerce:core                     0.9.2+ Reaction Commerce Core
reactioncommerce:reaction-accounts        1.2.3+ Reaction Accounts - Authentication UI for Reaction Commerce
reactioncommerce:reaction-analytics       1.1.0+ Reaction Analytics - Integrate third-party analytics libraries
reactioncommerce:reaction-analytics-libs  1.1.0+ Reaction Commerce - Analytics Libraries
reactioncommerce:reaction-paypal          1.2.0+ Reaction Paypal - PayPal payments for Reaction Commerce
reactioncommerce:reaction-shipping        0.6.0+ Reaction Shipping - Flat Rate shipping for Reaction Commerce
reactioncommerce:reaction-social          0.4.0+ Reaction Social - Social Sharing Package for Reaction
reactioncommerce:reaction-stripe          2.2.0* Reaction Stripe - Stripe payments for Reaction Commerce
reload                                    1.1.4  Reload the page while preserving application state.
session                                   1.1.1  Session variable
spiderable                                1.0.9  Makes the application crawlable to web spiders
standard-minifiers                        1.0.1* Standard minifiers used with Meteor apps by default.
tracker                                   1.0.9  Dependency tracker to allow reactive callbacks
underscore                                1.0.4  Collection of small helpers: _.map, _.each, ...


* New versions of these packages are available! Run 'meteor update' to try to update those packages to their latest versions. If your packages cannot be updated
  further, try typing `meteor add <package>@<newVersion>` to see more information.

+ These packages are built locally from source.

**Comment by aaronjudd** [comment] 2015-11-06 08:08
@hrath2015 there's only two methods that work for me, regardless of environment. I've tried a lot of different ways that all failed, or didn't produce the expected results.

```bash
# app testing
 VELOCITY_TEST_PACKAGES=1 meteor test-packages 

# package testing
 VELOCITY_TEST_PACKAGES=1 meteor test-packages  reactioncommerce:core
```

or to use the client velocity console, uncomment the testing section in `.meteor/packages`:


```
# Testing packages

velocity:html-reporter
sanjo:jasmine
velocity:helpers
```
and just run with `meteor` (just normal, without --test options).

`meteor --test` is in the [testing doc tips](https://github.com/reactioncommerce/reaction/blob/development/docs/developer/testing.md), but I can confirm that isn't working for me either.

There's a few broken tests that are currently leaving things a bit of a messy state in development branch right now as well, If you're testing with the master branch, then I'd have to say this will need some debugging as I can't confirm if / when `meteor --test` stopped(?) working and/or if it's related to velocity/meteor or reaction.

But since it's not working for me in development, as we work to close the broken tests in development for the next release,  we can keep an eye out for the root cause of this issue.

**Comment by zenweasel** [comment] 2015-12-17 02:35
I wonder if it wouldn't be worth adding a `reaction test` command that runs the tests using command we use for CI?

**Comment by aaronjudd** [comment] 2015-12-17 02:45
great idea, I've added locally and will commit and close this issue.

**Closed** 2015-12-17 07:47 UTC
Labels: help wanted, in progress

**Comment by clemenshelm** [comment] 2016-04-01 12:31
I get the error again when running `velocity test-app --ci` with Meteor 1.3:

```
=> App running at: http://localhost:3000/
failed to subscribe to VelocityTestReports subscription
failed to subscribe to VelocityAggregateReports subscription
failed to subscribe to VelocityMirrors subscription { [Error: Subscription
'VelocityMirrors' not found [404]]
error: 404,
reason: 'Subscription \'VelocityMirrors\' not found',
details: undefined,
message: 'Subscription \'VelocityMirrors\' not found [404]',
errorType: 'Meteor.Error' }
```

**Comment by zenweasel** [comment] 2016-04-01 13:11
@clemenshelm Reaction does not support Meteor 1.3 yet. We expect to support it in our next release.
With 1.3 support we will be removing support for Velocity and moving to using Meteor's native test runner.
