### ISSUE TITLE
TagNavContainer displays a setState(...) warning in browser console

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#3689] opened 2018-02-09 00:15 UTC
### Expected behavior
- No react warning should show in the browser console

### Actual behavior
- setState(..) warning shows in console

### Steps to reproduce the behavior
- While logged in as an admin go to a Product Detail Page and open the browser console
- Toggle edit mode on and off to see the warnings in the browser conole

### Versions
```shell
Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.8.0
Reaction branch: release-1.8.0
```

**Comment by zenweasel** [comment] 2018-02-09 00:36
This is a duplicate of https://github.com/reactioncommerce/reaction/issues/3654

**Closed** 2018-02-09 00:41 UTC
Labels: bug, impact-minor
