### ISSUE TITLE
Ubuntu Fatal Error addMapping with Code

### ISSUE THREAD

**Issue by nsrtky** [reactioncommerce/reaction#3245] opened 2017-11-07 11:28 UTC
![image](https://user-images.githubusercontent.com/12385044/32491299-3c20aab6-c3c7-11e7-8b19-b796cb41847e.png)

Are you looking for help with getting started on Reaction? Please go
to our [Gitter room](https://gitter.im/reactioncommerce/reaction) instead.

### Expected behavior
run and work
### Actual behavior
fatal error due to x86 architecture
### Steps to reproduce the behavior
install ubuntu 17.10 install node install reaction-cli install meteor run reaction init then cd reaction directory and run reaction cmd.
### Versions
(run `reaction -v` from your reaction directory)
![image](https://user-images.githubusercontent.com/12385044/32491367-7f9b1d6c-c3c7-11e7-9c17-cbe04b9caf99.png)

For enhancements or other issues, please describe, in as much detail as
possible, how the app should be changed, and how this would benefit other users and developers. 

We're giving away t-shirts, tote bags, and $500 gift cards to anyone who contributes a feature or fixes a bug. Learn more about the [Reaction Hack-a-bug-a-thon](https://blog.reactioncommerce.com/introducing-the-reaction-hack-a-bug-a-thon/).

**Comment by jshimko** [comment] 2017-11-07 13:32
Thank you for reporting your issue.  It looks like this is a duplicate of #3023 and #3183.  Closing in favor of them, but I recommend you try the `TOOL_NODE_FLAGS` environment variable that Meteor provides.

```sh
# You can try messing with the amount, but FYI, more is not necessarily better
export TOOL_NODE_FLAGS="--max-old-space-size=2048"

# now start Reaction
reaction
```

**Closed by jshimko** 2017-11-07 13:32 UTC
