### ISSUE TITLE
connectors & shopify connectors I18n

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2983] opened 2017-09-29 22:21 UTC
Related to https://github.com/reactioncommerce/reaction/issues/2641

Missing i18n translations for many parts of the `connectors` and `connectors-shopify` packages.

Missing translations on:
- Tooltip on icon toolbar
- Titles on panels
- Form fields related to API key/secret
- Translation file copied from shipping in `connectors` package, needs to be updated with proper namespace and all duplicate keys removed.

**Comment by kieckhafer** [comment] 2017-10-05 22:27
I don't think this is an issue of missing translations, this seems to be a much bigger issue where no translations are working for any old blaze form that's autoform / simpleSchema.

I'm going to start working on converting this specific form to React, but the overall problem is much bigger and I don't think something I can do alone for `marketplace v1.5.0`

**Comment by spencern** [comment] 2017-10-05 22:29
@kieckhafer is there a chance that this is a jQuery related issue?

**Comment by kieckhafer** [comment] 2017-10-05 22:35
is this is the correct way to import:
`import { $ } from "meteor/jquery";`

I just don't even see where the translations would be getting injected into the form. I guess I'm not familiar enough with autoform yet

jQuery import:
https://github.com/reactioncommerce/reaction/blob/ek-issue2983/imports/plugins/included/connectors-shopify/client/settings/shopify.js#L4-L5

Schema it's using (i'm assuming the i18n key is the `settings.apiKey` here?:
https://github.com/reactioncommerce/reaction/blob/ek-issue2983/imports/plugins/included/connectors-shopify/lib/collections/schemas/shopifyConnect.js#L37

Translations (ignore the `zzz`, I just do that so i can see the difference between default and translated): 
https://github.com/reactioncommerce/reaction/blob/ek-issue2983/imports/plugins/included/connectors-shopify/server/i18n/en.json#L38

**Comment by zenweasel** [comment] 2017-10-05 23:01
@kieckhafer I think that code is here: https://github.com/reactioncommerce/reaction/blob/fac086b96523d2b5de0c21940fe4a672fe1df32c/client/modules/i18n/main.js#L37

**Comment by kieckhafer** [comment] 2017-10-05 23:24
still not 100% what exactly is happening, but it looks like not all translations are being loaded on startup. If you look here, you can see via the logs that not all translations are there (look for reaction-connecters-shopify in particular, as that's what this issue initially started as)

https://github.com/reactioncommerce/reaction/blob/ek-issue2983/client/modules/i18n/main.js#L38

Going to keep digging, but wanted to throw this up here in case anyone was familiar and had any thoughts.

**Comment by kieckhafer** [comment] 2017-10-06 00:17
OK. I think I may have figured out the cause of the problem.

It seems that if you register your SimpleSchema locally inside your package, it doesn't get picked up by the i18n initialization. Here's the startup file, as you can see it imports the `Schemas` only from `/lib/collections/schemas`, so any schema you have locally in your package, like `ShopifyConnectPackageConfig` in this case, won't get translated.

The import: https://github.com/reactioncommerce/reaction/blob/ek-issue2983/client/modules/i18n/startup.js#L12

Looping through each: https://github.com/reactioncommerce/reaction/blob/ek-issue2983/client/modules/i18n/startup.js#L115

If this is actually what's happening, what are your thoughts on solutions? @zenweasel @aaronjudd @spencern 

We could force people to register schemas in the lib, but that defeats the purpose of not touching core in your packages.

**Comment by spencern** [comment] 2017-10-06 04:19
@kieckhafer nice work tracking this down.
I agree that forcing schemas to be registered in the lib is not really a good option due to requiring people to touch core.

I've thought before that having a `registerSchema` method similar to registering a react component might be useful, possible that might be a way to solve the problem, but maybe there's a simple solution I'm not thinking of right now.

@jshimko any thoughts on the best way to accomplish this?

**Comment by aaronjudd** [comment] 2017-10-06 16:11
this would most likely be resolved by #2917

**Comment by spencern** [comment] 2017-10-07 01:56
Resolved by #3053

**Closed by spencern** 2017-10-07 01:56 UTC
Labels: marketplace v1.5.0
