### ISSUE TITLE
Can't run default image in Docker for Windows or Linux

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3752] opened 2018-02-15 06:36 UTC
### Expected behavior
Image should start like it does on other platforms

### Actual behavior
Receive this error:
```
C:\Users\Brent\reaction_projects\reaction_build_test>docker run -p 3000:3000 reactioncommerce/reaction:latest

[-] External MONGO_URL not found. Starting local MongoDB...
[-] External MONGO_URL not found. Starting local MongoDB...

=> Starting app on port 3000...

/opt/reaction/dist/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
<snip>
```

### Steps to reproduce the behavior
1. Install Docker for Windows
1. Attempt to start docker image with `docker run -d -p 80:3000 reactioncommerce/reaction:latest`
1. Observe the error

### Versions
```
Node: 8.9.3
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.7.0
Reaction branch: master
Docker: 17.12.0-ce
```

**Comment by zenweasel** [comment] 2018-02-15 06:37
Possibly pilot error but it seems like running the pre-built image should be straight-ahead

**Comment by zenweasel** [comment] 2018-02-19 02:45
Seeing the same error on Linux. Removing the `windows-only` tag

**Comment by jshimko** [comment] 2018-02-23 16:38
I can't seem to reproduce this.  Can you please try running `docker pull` first so we can be sure we're both testing the same image?

```sh
docker pull reactioncommerce/reaction:latest
docker run -d -p 3000:3000 reactioncommerce/reaction:latest
```

That works for me on Mac, Ubuntu, and Windows.  Skipping the `MONGO_URL` triggers Mongo to start up and the app successfully connects to it.

**Comment by aldeed** [comment] 2018-10-25 14:29
Closing assumed fixed

**Closed by aldeed** 2018-10-25 14:29 UTC
Labels: bug, impact-minor
