### ISSUE TITLE
Quantity Adjustment is not working after shipment is completed

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#657] opened 2016-01-06 19:01 UTC
I see no change in available quantity.  Is it because Meteor.call("orders/inventoryAdjust", orderId); commented in Cart.js.  When this will be enabled so to proceed with test.

**Comment by aaronjudd** [comment] 2016-01-20 02:04
@hrath2015 this inventory adjustment should be done by the reaction-inventory package, on a order workflow event - probably on the order start. the "orders/inventoryAdjust" would adjust the variant qty, so maybe this older method should exist if no inventory hooks exist.. (or as a hook in core). For now it's replaced by the inventory package and you can add your own hooks from there.

**Comment by zenweasel** [comment] 2016-04-04 02:20
@aaronjudd So reading your comment, are you saying that by default placing and shipping an order by default does not reduce available quantity?

**Comment by zenweasel** [comment] 2016-04-08 00:38
So to my understanding, this is not a bug per-se but how the system was designed in that the checkout process itself would not make adjustments to inventory but that the `reaction-inventory` package, or another user-created package would manage how inventory is handled (which makes sense). However it's also reasonable to expect that if we are tracking inventory and an item is shipped that "available inventory" record would be decremented barring an explicit override of this. 

So my suggestion is that this ticket be closed but we open a new ticket to "implement simple inventory method in reaction-inventory" so that inventory works out of the box the way one would expect and it be fast-tracked on the roadmap.

**Comment by aaronjudd** [comment] 2016-04-08 07:27
@zenweasel I believe that's correct.

**Comment by zenweasel** [comment] 2016-04-11 02:31
Closing this, added https://github.com/reactioncommerce/reaction/issues/964 to implement decrementing inventory on Shipment.

**Closed by zenweasel** 2016-04-11 02:31 UTC
Labels: bug
