### ISSUE TITLE
Refunds do not work for Stripe: «Method 'stripe/payment/deAuthorize' not found»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [reactioncommerce/reaction#3533] opened 2018-01-20 22:12 UTC
### Expected behavior
Refunds should work for Stripe.

### Actual behavior
Refunds do not work for Stripe: «**Method 'stripe/payment/deAuthorize' not found**».

### Steps to reproduce the behavior
![05](https://user-images.githubusercontent.com/83204/35188548-45141138-fe61-11e7-9954-256136b3fe84.png)

![07](https://user-images.githubusercontent.com/83204/35188549-496b2cb2-fe61-11e7-9803-0638a826516c.png)

### Versions
> Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.4
Reaction branch: master

**Comment by zenweasel** [comment] 2018-01-21 02:21
I cannot reproduce this problem on `master`. Please provide specific reproduction steps.

![2018-01-21_10-19-53](https://user-images.githubusercontent.com/72819/35190104-be592c6c-fe94-11e7-9384-ca453d5d5cc7.png)

**Comment by prinzdezibel** [comment] 2018-01-21 08:52
@dmitry-fedyuk: It seems that you checked off "De-Authorize" checkbox in payment provider's settings. Stripe API doesn't offer "de-authorization" for its transactions (not to be confused with refunds, which do work). A shop owner is not intended to change the checkbox settings (capture, authorize, refund, de-authorize) of an existing plugin. It's rather a setting that is intended to be specified from plugin developers.  @zenweasel When reviewing PR for issue #3373, I was imagine the situation we're facing with this ticket would probably occur quite frequently. When starting to review the PR, I was also thinking, that the checkboxes are intended to be checked off/ unchecked by shop owners. Maybe it would be good to have that settings not editable at all.

**Comment by dmitry-fedyuk** [comment] 2018-01-21 09:42
### 1. 
> It seems that you checked off "De-Authorize" checkbox in payment provider's settings. 

**No**.
![01](https://user-images.githubusercontent.com/83204/35192653-0f3f3e9c-fec1-11e7-8b35-b96e73acc2e4.png)

### 2. 
>Stripe API doesn't offer "de-authorization" for its transactions

You are wrong again, learn the Stripe's documentation:

> If you need to cancel an authorization, you can release it by refunding the relevant Charge object.

[stripe.com/docs/charges#auth-and-capture](https://stripe.com/docs/charges#auth-and-capture)

![02](https://user-images.githubusercontent.com/83204/35192671-72c2634a-fec1-11e7-82ba-a2ed9832a8cb.png)

**Comment by prinzdezibel** [comment] 2018-01-21 09:56
@dmitry-fedyuk   1) Checked off means that the box is checked. Please uncheck it.
 2) Refunding !== De-authorization.

**Comment by zenweasel** [comment] 2018-01-23 05:44
@prinzdezibel I think the idea was that some people might want to disable some methods (refunds) when they possibly don't want to allow people to perform them. But it also makes sense to not allow people to break their own implementations by enabling methods that their payment provider doesn't support. So since no one is asking for the ability to disable methods then probably the best approach is just to not allow users the ability to change these values.

Closing this ticket now as this is not a bug per-se, but we can improve this implementation to make it more failure-proof.

**Closed by zenweasel** 2018-01-23 05:44 UTC
Labels: bug, cannot-reproduce
