### ISSUE TITLE
[1.12.0+] Setting breakpoints in server code doesn't work as expected

### ISSUE THREAD

**Issue by stevaras** [reactioncommerce/reaction#4335] opened 2018-06-18 15:22 UTC
## Issue Description
Unfortunately on release-1.13.0 branch, server debugging seems to be off. I put breakpoints on a specific line and the debugger stops on another. We used to have that issue in the past in some previous version as well.

## Steps to Reproduce
1. Put a breakpoint anywhere server side
2. Do an action or call a method that would trigger that part of the code you set the breakpoint
3. See whether it actually stops on the correct line you've putted the breakpoint

### Versions
Node: 10.2.1
NPM: 6.1.0
Meteor Node: 8.11.2
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.13.0

**Comment by spencern** [comment] 2018-06-18 15:41
@stevaras Are there any additional plugins that you're using when seeing this behavior or will a fresh clone of the `release-1.13.0` branch cause this behavior?

Will you highlight some examples of specific lines that the debugger is failing to stop on?

**Comment by spencern** [comment] 2018-06-18 15:42
Could this issue be related https://github.com/meteor/meteor/issues/9275?

**Comment by spencern** [comment] 2018-06-18 16:44
@stevaras I'm unable to reproduce this issue.

Added a breakpoint here:
https://github.com/reactioncommerce/reaction/blob/release-1.13.0/imports/plugins/core/catalog/server/methods/catalog.js#L964

Then changed the vendor name of a product from the operator view of the PDP. Using the vscode debugger, the execution of the code stopped as expected.

**Comment by prosf** [comment] 2018-06-18 18:23
@spencern  I was able to reproduce it on Webstorm 2017.3(linux) .
 Added breakpoint at line 414 . However WebStorm debugger stopped at line 370!

Then I added a breakpoint at the same line in Chrome's node debugger. Execution of code didn't stop at all there. Another weird thing is that the same code showed up in line 427 instead of 414, in Chrome.
**Webstorm**
![screenshot from 2018-06-18 20-58-16](https://user-images.githubusercontent.com/8209895/41554486-a984a51e-733d-11e8-9d91-fa03aea88209.png)
**Chrome**
![screenshot from 2018-06-18 21-17-24](https://user-images.githubusercontent.com/8209895/41554527-cf6f0e7c-733d-11e8-9509-f177acff3b51.png)

**Comment by spencern** [comment] 2018-06-18 18:55
are you certain that line of code is executing?

**Comment by prosf** [comment] 2018-06-18 19:19
Yes absolutely ! I'm visiting localost/ with the default db.

Now I tried latest version of vs code(1.24.1):
I was not able to put a breakpoint in line 414. Then I tried on 417 ,but the red bullet showed-up on 426.
While the breakpoint was visible in 426 I visited localhost and again the execution point showed-up in line 370:
![image](https://user-images.githubusercontent.com/8209895/41557144-6533e462-7345-11e8-8e48-32d167cb85b7.png)

After giving a glance at https://github.com/meteor/meteor/issues/8611 I did rm -rf ~/.babel-cache but this didn't help at all

**Comment by spencern** [comment] 2018-06-18 19:53
@prosf I see the same issue putting a breakpoint on the lines you specified. I don't think that this is a Reaction issue, but it does appear to be an issue in Meteor and/or V8.

Can you specify which version of Reaction this last worked in? Is it 1.12 or a previous version?

Related Meteor issues to follow: https://github.com/meteor/meteor/issues/9875 or meteor/meteor#9275

I haven't tested any specific workarounds, though setting a breakpoint above or below the desired location and stepping though may work as suggested in one of those Meteor issues. There is an active PR in the chromium V8 tracker that may be worth following: https://chromium-review.googlesource.com/c/v8/v8/+/833260

I'd like to close this issue with your permission unless you're certain this is a bug specific to Reaction.

**Comment by prosf** [comment] 2018-06-19 10:10
@spencern I did a test ,that probably implies that is more of a Reaction specific, bug:
I created a bare app with METEOR@1.7.0.1 using meteor create --bare .
There I threw a test.js in root with some server side code . I put a breakpoint in line 9 and the debugger paused there properly
![bare_test_js](https://user-images.githubusercontent.com/8209895/41591258-e43d9a7e-73c1-11e8-8e0b-65538657c8cb.png)

Then I did the same test in release-1.13.0  , there the debugger paused on a wrong line (7):
![reaction_test_js](https://user-images.githubusercontent.com/8209895/41591321-1191a920-73c2-11e8-981c-62a9a8c26cf6.png)

**Comment by spencern** [comment] 2018-06-19 13:35
@prosf Do you know the most recent version of Reaction that this worked for you?

**Comment by prosf** [comment] 2018-06-19 16:54
@spencern  I can see the same problem in the current master(1.12). The last version without this problem was 1.11 which had METEOR@1.6.1

**Comment by spencern** [comment] 2018-06-19 16:58
Interesting. I'm still not sure how any core Reaction change could have caused this, but we have bumped beta versions for Babel 7 since then, not sure what else might have changed. If you're able to isolate or narrow the problem down any more that would be helpful. As of now I'm not really sure where to start.

**Comment by prosf** [comment] 2018-06-19 17:58
Okay .If I 'll have any news  ,I ll post back.

**Comment by spencern** [comment] 2018-06-19 19:03
Thanks for reporting this, it is something that I'd like to see working.

**Comment by Akarshit** [comment] 2018-06-21 06:10
I am having similar problems, the current line(the get's highlighted)  on UI is not actually where the control is. So it looks like the debugger is jumping between random positions.
Editor - VSC

**Comment by lcampanis** [comment] 2018-06-21 19:22
+1

**Comment by spencern** [comment] 2018-06-22 16:15
This seems to be impacting a number of people and I'd like to be able to get it resolved. In order to do that we need to drill into what could have caused this a little more specifically. 
@prosf has indicated that this issue exists in both 1.12 and 1.13. 

I'm curious if there were any significant changes to node, babel, or other dependencies that could have caused this type of behavior.

**Comment by veered** [comment] 2018-07-06 19:05
When using chrome, try using https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj

**Comment by spencern** [comment] 2018-07-09 13:41
Thanks @veered

**Comment by spencern** [comment] 2018-07-09 13:45
@lcampanis Does the workaround suggested in https://github.com/meteor/meteor/issues/9875#issuecomment-394535661 work for you?

**Comment by lcampanis** [comment] 2018-08-02 19:26
@spencern it doesn't. Debugging is still a massive issue and don't see any progress on Meteor's side either. So somewhere between Webstorm, Node and Meteor debugging is broken.

**Comment by RealHandy** [comment] 2018-08-15 16:55
Yep, still an issue in meteor 1.7 -- `debugger;` works, setting breakpoints in UI doesn't.

**Comment by spencern** [comment] 2018-09-15 05:11
We'll try again in Meteor 1.8 🤞

**Closed** 2019-12-16 01:13 UTC
