### ISSUE TITLE
Default : Create variant bug, collections checking

### ISSUE THREAD

**Issue by psy21d** [reactioncommerce/reaction#328] opened 2015-03-04 01:54 UTC
This problems make me cry.
Not working. This all is new, clean from .git what I get now
https://github.com/reactioncommerce/reaction-core/blob/master/docs/packages.md

http://127.0.0.1:3000/product/new
 "You can make it visible" — click

I20150304-04:43:39.523(3)? Exception while invoking method 'updateProductField' Error: Match error: Expected string, got object
I20150304-04:43:39.524(3)?     at checkSubtree (packages/check/match.js:159:1)
I20150304-04:43:39.524(3)?     at check (packages/check/match.js:32:1)
I20150304-04:43:39.524(3)?     at [object Object].Meteor.methods.updateProductField (packages/reactioncommerce:core/server/methods/products/products.coffee:217:5)
I20150304-04:43:39.524(3)?     at packages/check/match.js:109:1
I20150304-04:43:39.525(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150304-04:43:39.525(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150304-04:43:39.525(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150304-04:43:39.525(3)?     at packages/ddp/livedata_server.js:648:1
I20150304-04:43:39.525(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150304-04:43:39.526(3)?     at packages/ddp/livedata_server.js:647:1
I20150304-04:43:39.526(3)? Sanitized and reported to the client as: Match failed [400]
I20150304-04:43:39.526(3)?
I20150304-04:43:44.791(3)? Exception while invoking method 'updateProductField' Error: Match error: Expected string, got object
I20150304-04:43:44.791(3)?     at checkSubtree (packages/check/match.js:159:1)
I20150304-04:43:44.791(3)?     at check (packages/check/match.js:32:1)
I20150304-04:43:44.791(3)?     at [object Object].Meteor.methods.updateProductField (packages/reactioncommerce:core/server/methods/products/products.coffee:217:5)
I20150304-04:43:44.791(3)?     at packages/check/match.js:109:1
I20150304-04:43:44.793(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150304-04:43:44.793(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150304-04:43:44.794(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150304-04:43:44.794(3)?     at packages/ddp/livedata_server.js:648:1
I20150304-04:43:44.794(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150304-04:43:44.794(3)?     at packages/ddp/livedata_server.js:647:1
I20150304-04:43:44.795(3)? Sanitized and reported to the client as: Match failed [400]
I20150304-04:43:44.795(3)?

http://127.0.0.1:3000/product/new
Create variant — click

I20150304-04:49:27.117(3)? Exception while invoking method 'createVariant' Error: Match error: Expected string, got object
I20150304-04:49:27.117(3)?     at checkSubtree (packages/check/match.js:159:1)
I20150304-04:49:27.124(3)?     at check (packages/check/match.js:32:1)
I20150304-04:49:27.124(3)?     at [object Object].Meteor.methods.createVariant (packages/reactioncommerce:core/server/methods/products/products.coffee:54:5)
I20150304-04:49:27.125(3)?     at packages/check/match.js:109:1
I20150304-04:49:27.125(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150304-04:49:27.125(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150304-04:49:27.125(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150304-04:49:27.125(3)?     at packages/ddp/livedata_server.js:648:1
I20150304-04:49:27.125(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150304-04:49:27.126(3)?     at packages/ddp/livedata_server.js:647:1
I20150304-04:49:27.126(3)? Sanitized and reported to the client as: Match failed [400]
I20150304-04:49:27.126(3)?

Can check collections, functions?
At 1 february that all works fine!

I think there many bugs like that.

**Comment by evliu** [comment] 2015-03-04 19:07
should be fixed under https://github.com/reactioncommerce/reaction-core/commit/3a5656069ba82d6513547ce9469b1564544feb92

**Comment by Gouthamve** [comment] 2015-03-04 19:50
Actually, even updateVariant has a similar problem which is fixed by https://github.com/reactioncommerce/reaction-core/pull/102

**Comment by aaronjudd** [comment] 2015-03-04 20:02
@Gouthamve thanks, I merged reactioncommerce/reaction-core#102

**Comment by psy21d** [comment] 2015-03-04 22:38
When we go to http://127.0.0.1:3000/product/new
Then, make caption, and got this:

I20150305-01:33:16.671(3)? Exception while invoking method 'updateProductField' Error: Match error: Expected string, got object
I20150305-01:33:16.673(3)?     at checkSubtree (packages/check/match.js:159:1)
I20150305-01:33:16.673(3)?     at check (packages/check/match.js:32:1)
I20150305-01:33:16.673(3)?     at [object Object].Meteor.methods.updateProductField (packages/reactioncommerce:core/server/methods/products/products.coffee:217:5)
I20150305-01:33:16.674(3)?     at packages/check/match.js:109:1
I20150305-01:33:16.674(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150305-01:33:16.675(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150305-01:33:16.675(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150305-01:33:16.675(3)?     at packages/ddp/livedata_server.js:648:1
I20150305-01:33:16.675(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150305-01:33:16.676(3)?     at packages/ddp/livedata_server.js:647:1
I20150305-01:33:16.676(3)? Sanitized and reported to the client as: Match failed [400]
I20150305-01:33:16.676(3)?
I20150305-01:33:21.409(3)? Exception while invoking method 'updateProductField' Error: Match error: Expected string, got object
I20150305-01:33:21.409(3)?     at checkSubtree (packages/check/match.js:159:1)
I20150305-01:33:21.410(3)?     at check (packages/check/match.js:32:1)
I20150305-01:33:21.410(3)?     at [object Object].Meteor.methods.updateProductField (packages/reactioncommerce:core/server/methods/products/products.coffee:217:5)
I20150305-01:33:21.410(3)?     at packages/check/match.js:109:1
I20150305-01:33:21.410(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150305-01:33:21.411(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150305-01:33:21.411(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150305-01:33:21.411(3)?     at packages/ddp/livedata_server.js:648:1
I20150305-01:33:21.412(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150305-01:33:21.412(3)?     at packages/ddp/livedata_server.js:647:1
I20150305-01:33:21.412(3)? Sanitized and reported to the client as: Match failed [400]
I20150305-01:33:21.413(3)?

**Comment by psy21d** [comment] 2015-03-04 22:41
I can not understand the meaning of checks. String, Number, Object AND undefuned AND null.

It turns the set of all types and values.
It really needs to be done?
What does it give?

**Comment by Gouthamve** [comment] 2015-03-05 09:19
Hi, @psy21d could you clarify what you mean by making a caption? I am not able to reproduce the error.

**Comment by psy21d** [comment] 2015-03-05 09:26
There are many errors with create new item, publish collection, tags, images publish (not show automatically after upload).
Used new compilation.
I really not understood what is happening, a month ago all work fine.

**Comment by Gouthamve** [comment] 2015-03-05 09:34
I think form validation was introduced using the check package. But not everything was tested. Just report all the bugs with form-validation here and I will try to solve them.

**Comment by psy21d** [comment] 2015-03-05 10:03
Please, test all links, fields, create items, delete.
Variants, options. All.
Cart functions, shipping.
Just click-by click. It takes half a hour, and very effective method.
You can find it randomly.
Thank you very much!

**Comment by Gouthamve** [comment] 2015-03-05 10:20
I am going to test all the implementation of the check package. I fixed another issue, but I will send a PR with all issues fixed.

**Comment by psy21d** [comment] 2015-03-05 11:26
Thank you a lot!

**Comment by aaronjudd** [comment] 2015-03-05 17:05
@psy21d the code in master branch (what you were using a month ago) didn't use the `audit-argument-checks` package.  The goal with the use of `check` is that every argument to a server side method is validated, before processing.  It should not be related to `forms` themselves, but that's where you will see them. There's a lot to check and I didn't catch every use case, which is why we're seeing them now. I think there might be a couple remaining but they'll all be resolved before we merge `development` to master and the next release.

**Comment by psy21d** [comment] 2015-03-05 17:16
Thanks! I need understanding inner core mechanisms for fixing that problems.
Simple unmount audit-argument-checks package not make expected effect.

**Comment by Gouthamve** [comment] 2015-03-05 18:07
@psy21d @aaronjudd Fixed a couple of bugs I found when testing. But no matter how hard I try, I cannot not replicate your updateProductField error.

**Comment by aaronjudd** [comment] 2015-03-05 18:20
@Gouthamve thanks, I merged.

**Comment by aldeed** [comment] 2015-03-11 17:28
See also #338

**Closed** 2015-03-17 17:54 UTC
Labels: bug
