### ISSUE TITLE
Admin account will disappear after register a new account

### ISSUE THREAD

**Issue by cooloney** [reactioncommerce/reaction#494] opened 2015-10-17 23:11 UTC
I met a critical bug recently and I found it's also reporoducible in reaction latest code.
* add an admin info in settings/dev.settings.json
* start reaction, it will create an account admin
* can use admin login into the reaction system
* i logout and register a normal user and login as a normal user then logout
* finally I tried to use admin login, but it says the user is not found
I checked the database and admin account disappeared
looks like very weird. but i believe it's very easy to reproduce

**Comment by seanjsong** [comment] 2015-11-02 04:53
To generalize this problem:

1. Log in with an existing account A
2. Log out.
3. In **the same browser window**, register another account B and log in with account B
4. account A will be deleted from database

The bug is probably caused by server method "cart/mergeCart" in https://github.com/reactioncommerce/reaction-core/blob/development/server/methods/cart.js

`Meteor.users.remove(sessionCart.userId);` is supposed to remove an anonymous guest account because the user has logged in, but inadvertently removes a previously logged-out account.

**Comment by aaronjudd** [comment] 2015-11-02 06:19
The offending line is https://github.com/reactioncommerce/reaction-core/blob/development/server/methods/cart.js#L76, which can be commented out for now. (just prevents session cleanup - which is the dangerous part here that need some work).

**Comment by cooloney** [comment] 2015-11-03 22:05
@aaronjudd should I provide a patch to comment out this Meteor.users.remove() line to fix this issue. or it's just a workaround?

**Comment by aaronjudd** [comment] 2016-01-20 01:35
I believe this is now resolved with #536, #650  - at least indirectly. The comment patch removal of anonymous / user carts remains, but we'll handle that in a new issue.

**Closed by aaronjudd** 2016-01-20 01:35 UTC
Labels: bug, ready
