### ISSUE TITLE
Theme: define LESS/CSS overide priority

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#341] opened 2015-03-12 19:05 UTC
What's the best place to add global style definitions?

The only place I see any existing global definitions is within the `mixins.less` file, but that doesn't seem appropriate. Layout doesn't seem right unless it has to do with layout.

**Comment by aaronjudd** [comment] 2015-03-12 19:15
organizationally, I'd think we could move the "global styles" section of `mixins.less` to `/packages/reaction-core-theme/theme/layout/layout.less`.  I'm not sure if there was any other reason for the placement, the compile order and implementation of the less theme is a little tricky, so that's something to watch for if you want to refactor.

**Comment by mikemurray** [comment] 2015-07-02 05:14
It's easy enough to add a global.less (loaded after variables.less), and maybe even a rest.less (loaded last). Then you could dump anything random you need first, and anything you absolutely need last to make sure it sticks.

**Comment by prinzdezibel** [comment] 2015-07-21 19:30
@mikemurray Not sure I understand it correctly. Please see example in #406. Where would I define the footer CSS. At the moment I do modifications in custom.reaction.import.less because the comment at top of the file says so. But I can't override styles there unless I force with !important.

**Comment by prinzdezibel** [comment] 2015-07-31 13:31
The problem I mentioned above still exists with v0.6.3.

**Comment by aaronjudd** [comment] 2015-08-02 01:00
@prinzdezibel can't you just create another import file?  `mystyle.import.less` and then use @import to it in `/client/themes/bootstrap/custom.reaction.import.less` (as the last line)?

**Comment by mikemurray** [comment] 2015-08-04 03:42
@prinzdezibel you're doing everything right. The issue is the **custom.reaction.import.less** file is being imported at the top of **custom.reaction.less**. Which is perfectly fine if you want to override variables and what not. That file, however, is not suitable for overriding CSS defined later in **custom.reaction.less**.

We will need to add a another user editable file that is loaded dead last to insure your styles have the bast chance of taking affect.

**Comment by mikemurray** [comment] 2015-08-04 04:44
Made some changes to how user overridable files. 

**Override variables / mixins / reset css stuff**
custom.reaction.user-imports.less 

**Add all of your custom css and imports into this file, it is loaded last**
custom.reaction.user-overrides.less

**Comment by aaronjudd** [comment] 2015-08-04 04:49
great!  can you update the docs https://github.com/reactioncommerce/reaction-core/blob/development/docs/themes.md as well, to reflect any changes.

we're going to need to over this soon as well - I'm expecting less handling changes in next couple of meteor updates.

**Comment by aaronjudd** [comment] 2015-08-04 20:33
Merged updated and published reactioncommerce:bootstrap-theme@1.3.0.

If you want to override variables or add custom styles to the top, see 'custom.reaction.user-imports.less'

**Comment by prinzdezibel** [comment] 2015-08-04 20:43
Thx!

**Comment by aaronjudd** [comment] 2015-08-04 22:38
realized there's a flaw here, pushing another version in a few....

**Comment by mikemurray** [comment] 2015-08-04 22:48
Renamed the user editable files so they get processed properly.

**Override variables / mixins / reset css stuff**
custom.reaction.import.less

**Add all of your custom css and imports into this file, it is loaded last**
custom.reaction.overrides.import.less

**Closed** 2015-08-04 22:50 UTC
Labels: UIX
