### ISSUE TITLE
Products more then 24 are not getting loaded in the productContainerCustomer page

### ISSUE THREAD

**Issue by ushadev** [reactioncommerce/reaction#4090] opened 2018-03-29 04:27 UTC
## Issue Description

If we have products more them 24. the first 24 are getting loaded( in the productContainerCustomer page ) and when we scroll down to the bottom of the page we don't find the LoadMoreProducts button and a client console error occurs saying loadProducts is not a function. actually, it is getting undefined and the next 24 products are not being loaded. below is the screenshot of the client console error.

![image](https://user-images.githubusercontent.com/28245872/38069809-053cdfea-3336-11e8-888b-13818cf07ea1.png)

## Steps to Reproduce

1. start the reaction

2. log in as administrator and add products more than 24 say( around 30) and publish them.

3. log out and check the productContainerCustomer page. for the first time after scrolling down beyond the 24 products, you can see the rest of all the 30 products without any error.

4.) now if you revisit the page or restart the reaction and visit the productContainerCustomer page and scroll down to view the products beyond 24 you will get the error as shown in the above screenshot and the rest of the products cannot be loaded.

## Possible reason for the Bug
the this.props.loadProducts is getting undefined.

### Versions

Reaction: 1.10.0

**Comment by ushadev** [comment] 2018-04-16 04:40
Any updates or action taken for the above issue

**Comment by zenweasel** [comment] 2018-05-01 21:35
Bumping this up to critical (which it should have always been).

@Akarshit This issue is going to be a blocker for us so if we can try to fix this quickly we probably should

**Comment by Akarshit** [comment] 2018-05-14 10:12
The issue is still there for some screen sizes. I was able to reproduce this by zooming out the screen and then trying to scroll. Should be fixed by #4243

**Closed** 2018-06-04 15:37 UTC
Labels: bug, impact-critical, verified-reproducible
