### ISSUE TITLE
Emails: Link in invitation email does not bring you to expected page

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5114] opened 2019-04-10 20:00 UTC
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The email sent when you invite an admin user to your shop has a button. When you click that button, it doesn't bring you to a page to accept the invitation or explain how to register and accept.

### Setup
1. Log in as operator.
2. Edit Shop settings and make sure the shop email address is testing@reactioncommerce.com. This address is verified to send emails through the Reaction testing SES account. Other addresses may not work.
3. Go to the operator user profile page and make sure you have a real email address. You can use something like `<yourname>+admin@reactioncommerce.com`.
4. Enter correct email service credentials on Email page. Make sure the indicator is green.

### Reproduce
1. Log in to operator UI
2. Go to Accounts screen
3. On "Add Admin User" card, add a new user with a real email address. For example, `<yourname>+admin2@reactioncommerce.com`
4. Click the button in the "You are invited to join" email.

## Possible Solution
Need to figure out what should happen or what previously happened when this worked, and then make it happen again.

### Versions
2.0.0 RC 11

**Comment by willopez** [comment] 2019-06-28 00:52
Cannot reproduce this error. I was able to invite a new shop manager and set new password. The invitation email contained an email link in this format: `http://localhost:3000/account/enroll/TOKEN` which is correct.

**Comment by willopez** [comment] 2019-06-28 18:37
Verified this issue has been resolved in a previous update.

**Closed by willopez** 2019-06-28 18:37 UTC

**Comment by trojanh** [comment] 2019-09-09 10:40
resolved by https://github.com/reactioncommerce/reaction/pull/5173

Adding this PR for reference
