### ISSUE TITLE
Reset password uses wrong email

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#1061] opened 2016-06-03 22:03 UTC
For bugs, please fill out the three following sections completely

### Expected behavior
Reset password email should be configured from the shop settings

### Actual Behavior
Reset password emails from address are being influenced by launchdock-connect package settings

### Steps to Reproduce the Behavior
1. Change the shop email to something other than `hello@reactioncommerce.com`
2. Reset your password
3. Email will come from `hello@reactioncommerce.com`

Hard-coded in:
https://github.com/reactioncommerce/launchdock-connect/blob/development/server/email.js#L6

**Comment by jshimko** [comment] 2016-08-04 18:30
Fixed by #1241

**Comment by Capt-Slow** [comment] 2016-08-11 17:57
Fix denied. 

Steps to Reproduce:
1) Change 'hello@reactioncommerce.com' to 'howdy@reactioncommerce.com' within email.js .
2) Proceed through reset password flow. Observe user will receive email from initial owner email.
3) Update Shops.emails[0].address in db to 'josh@test.com'.
4) Proceed through reset password flow.

Result:
The user will not receive forgot password email.

Expected Behavior:
User should receive forgot password email.

**Comment by jshimko** [comment] 2016-08-15 19:11
Good catch @Capt-Slow.  Yeah, this is because the shop name and email get set here on startup:

https://github.com/reactioncommerce/reaction/blob/development/server/api/email.js

...and then the Meteor accounts stuff never gets set again when the database values change.  I'm going to be converting the accounts email methods over to using the new email job queue, so that will get addressed at that point.  

Thanks!

**Comment by zenweasel** [comment] 2016-08-15 22:27
So I am unclear on this now. Is this issue fixed or it's going to be fixed at a later date?

**Comment by jshimko** [comment] 2016-08-16 02:10
It's going to be fixed at a later date (soon).  The main problem is the shop name and email are set at startup [here](https://github.com/reactioncommerce/reaction/blob/development/server/api/email.js#L12-L13) and then they never update again.  If the database values change afterward and an email is sent, the original values are used.  Unfortunately, there's no non-hacky way to make those configs dynamic.  Since I'm going to convert the accounts methods to use the new email job queue, I'm going to consolidate that fix into that effort. 

For now, this issue should probably stay open as a reminder, but it can be added to the 0.16.0 milestone instead.

**Closed** 2016-08-18 01:21 UTC
Labels: review
