### ISSUE TITLE
Cart items picture displays placeholder (sometimes) when product has variants

### ISSUE THREAD

**Issue by speedingdeer** [reactioncommerce/reaction#3263] opened 2017-11-09 12:43 UTC
### Expected behavior
Cart displays the selected product variant's picture
### Actual behavior
Cart display nothing (sometimes) instead of selected product variant's picture
### Steps to reproduce the behavior
Create few product variants and add pictures for each of them. Next as user select few and them to cart. Click on the cart image and check if the pictures in cart match the ordered variant pictures.

<img width="1440" alt="screen shot 2017-11-09 at 12 53 34" src="https://user-images.githubusercontent.com/279544/32606005-e6149eb4-c553-11e7-9f6d-39b06ec2a7a5.png">

### Versions
(run `reaction -v` from your reaction directory)
Node: 8.1.4
NPM: 5.0.3
Meteor Node: 4.8.5
Meteor NPM: 4.6.1
Reaction CLI: 0.20.0
Reaction: 1.5.6
Reaction branch: master
Docker: 17.09.0-ce

**Comment by zenweasel** [comment] 2017-11-10 03:22
I'm seeing this as well. It has to do with `ReactionProduct.selectedVariant()` is sometimes returning `null`. Trying to get this solved today.

**Comment by zenweasel** [comment] 2017-11-10 03:25
Which is just caused by the fact that sometimes no variant is selected, and sometimes the top-level variant is selected. If you select a variant, then the image is shown. And refreshing seems to always select the top-level variant.

**Comment by zenweasel** [comment] 2017-11-30 06:11
I believe this was fixed via #3267 but needs to be verified

**Comment by zenweasel** [comment] 2017-12-06 21:59
@codejockie Did you verify that this issue still occurs on `master`?

**Comment by codejockie** [comment] 2017-12-07 06:26
@zenweasel yes I did that. It still occurs on `master`.

**Closed** 2017-12-12 06:22 UTC
Labels: bug, impact-major, needs-to-be-verified-fixed
