### ISSUE TITLE
Localization not working

### ISSUE THREAD

**Issue by transilience** [reactioncommerce/reaction#6272] opened 2020-08-02 08:24 UTC
## Issue Description
When starting up as a fresh server, we tried to change the localization field to meet our country needs, 

Timezone : Asia/ Calcutta
Currency : INR
Base unit of length : Centimeters
Base unit of Measure : Grams
Language : English

## Steps to Reproduce

1. Clone the git repo
2. make
3. setup a new account from localhot:4080
4. create a dummy product
5. go to localization from the menu
6. set the above settings

### Versions
3.8.0

```
08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:497 Form "onSubmit" function error: TypeError: Cannot read property 'weight' of null
    at onSubmit (08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:729)
    at e (08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:497)
    at l (08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:446)
    at Generator.i [as _invoke] (08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:446)
    at Generator.forEach.e.<computed> [as next] (08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:446)
    at r (08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34)
    at s (08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34)
    at 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:1
e @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:497
l @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:446
i @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:446
forEach.e.<computed> @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:446
r @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34
c @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34
(anonymous) @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:1
Promise.then (async)
n.then @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:574
r @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34
s @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34
(anonymous) @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:1
Promise.then (async)
n.then @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:574
r @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34
s @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34
(anonymous) @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34
(anonymous) @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34
Z @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:497
Y @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:497
U @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:729
c @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
h @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
m @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
C @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
T @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
O @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
N @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
zn @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
tc @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
qe @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
Dn @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
(anonymous) @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
n.unstable_runWithPriority @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:358
rc @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322
Rn @ 08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:322

```

----
**Edit**

- our shipping default values were null

```
Form "onSubmit" function error: TypeError: "m.defaultParcelSize is null"
    onSubmit http://localhost:4080/08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:729
    e http://localhost:4080/08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:497
    l http://localhost:4080/08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:446
    i http://localhost:4080/08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:446
    t http://localhost:4080/08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:446
    r http://localhost:4080/08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34
    s http://localhost:4080/08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:34
    bindEnvironment http://localhost:4080/08eda9b3702e26bd409ab3009b7aad16fbe5e744.js?meteor_js_resource=true:1
```

## Possible solution

- Set default height weight etc in the shipping section as 0

**Comment by balibebas** [comment] 2020-08-02 11:15
I'm seeing the same issue with `reactioncommerce/admin:3.0.0-beta.7`. Looks like this may have been introduced in https://github.com/reactioncommerce/reaction-admin/pull/242 refactorings released in `beta.6` (unconfirmed).

@transilience what version of admin are you running?

**Comment by MohanNarayana** [comment] 2021-01-20 01:00
Not reproducable

**Closed as completed by MohanNarayana** 2021-01-20 01:00 UTC
Labels: bug, needs triage
