### ISSUE TITLE
Paypal Button is now shown sometimes.

### ISSUE THREAD

**Issue by lhz516** [reactioncommerce/reaction#534] opened 2015-11-26 00:21 UTC
All API info is set.
Browser console log:

paypal.checkout.setup() more than once. This function can only be called once per page load. Any further calls will be ignored.

**Comment by zenweasel** [comment] 2015-11-26 00:23
Hey @lhz516, this would appear to be a duplicate of https://github.com/reactioncommerce/reaction-paypal/issues/16. Correct?

**Comment by lhz516** [comment] 2015-11-28 07:46
Yes. I think the paypal button only can be shown at the first time. When user go to other page then go back to checkout. The paypal button will no longer exist.

**Comment by zenweasel** [comment] 2015-12-15 22:44
Can't replicate using the current version (0.10.1) Closing for now.

**Closed by zenweasel** 2015-12-15 22:44 UTC
Labels: bug, in progress
