### ISSUE TITLE
Product context menu has too many sections open

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3731] opened 2018-02-13 01:38 UTC
### Expected behavior
When I open a section in the product editor action view within the PDP, other sections should close. When clicking a variant or option to open the editor for that variant or option, all other panels should close.

### Actual behavior
The `Taxable` and `Inventory tracking` panels get stuck open and do not close or roll up when a different variant or option is selected.

<img src="http://g.recordit.co/ciPQTQ0PS9.gif">

### Steps to reproduce the behavior
1. Open the default product
2. Click the variant
3. Click an option
4. Observe that certain panels are stuck open.

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.12.0-ce
```

**Comment by prinzdezibel** [comment] 2018-02-16 17:27
After reading the code, it's clear that this is not a bug fix anymore, but would represent an enhancement of existing UI components. In the screenshot below the current component layout is shown:
![basic_reaction_product_and_2__tmux_](https://user-images.githubusercontent.com/1733229/36320112-61503cde-1345-11e8-8ddf-0feb6b0f66db.jpg)


The idea of the Settings Card is to persist the expanded state of each card individually and independent of other card's state in local storage.

If we'd like to introduce constraints on the card's individual expanded states, we need to transfer the control over the combined state of the cards onto the parent component  (e.g. Components.CardGroup or any other ancestor).

This would require an overhaul of the SettingCard component. Not only would it no longer be responsible for calculating the expanded state itself, but also would need additional changes in the way the header is rendered to allow the first panel (Components.Card) be a member of the whole group.  This is because the first panel has icons in the card header which can't be done with the SettingsComponent yet.

This is certainly doable, but I wouldn't consider this a bug fix. The decision about how to proceed should be @Spencer's call.

**Comment by prinzdezibel** [comment] 2018-02-16 17:27
Removed the bug label, as I would consider this an enhancement of the current functionality.

**Comment by spencer** [comment] 2018-02-16 17:30
I don't think it should be my call, it should be @spencern 's call!

**Comment by prinzdezibel** [comment] 2018-02-16 17:32
Man, this is the second time already, that I got @spencern's nick wrong. sorry!

**Comment by zenweasel** [comment] 2018-02-26 08:19
I spoke with @spencern and we agreed that we still classify this as a bug and we should proceed with it even though it may require more coding. Moving back into unassigned bugs

**Comment by kieckhafer** [comment] 2019-07-10 22:24
Closing this, as 2.0 doesn't have this UI anymore.

**Closed by kieckhafer** 2019-07-10 22:24 UTC
Labels: bug, impact-minor
