### ISSUE TITLE
Docker build fails on OS X Sierra

### ISSUE THREAD

**Issue by Stat1c14** [reactioncommerce/reaction#2149] opened 2017-04-21 21:30 UTC
### Expected behavior

`docker build -t imagename . ` produces a Docker image containing your Reaction fork that can be pushed to DockerHub or deployed and run.

### Actual Behavior

```
Sending build context to Docker daemon 7.647 MB
Step 1/3 : FROM reactioncommerce/base:v1.3.0
# Executing 2 build triggers...
Step 1/1 : COPY . $APP_SOURCE_DIR
Step 1/1 : RUN cd $APP_SOURCE_DIR &&             bash $BUILD_SCRIPTS_DIR/build-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh
 ---> Running in 8afbb3afa7e7
/opt/nodejs/bin/reaction -> /opt/nodejs/lib/node_modules/reaction-cli/dist/main.js
/opt/nodejs/bin/rc -> /opt/nodejs/lib/node_modules/reaction-cli/dist/main.js
reaction-cli@0.8.0 /opt/nodejs/lib/node_modules/reaction-cli
├── semver@5.3.0
...
├── lodash@4.17.4
└── babel-polyfill@6.23.0 (regenerator-runtime@0.10.3, babel-runtime@6.23.0, core-js@2.4.1)

[-] Running Reaction plugin loader...


Setting up plugin imports...

Setting up style imports...

Done!


[-] Running npm install in app directory...

npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global npm@2.15.12 should be installed with -g

> fibers@1.0.15 install /opt/reaction/src/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-46` exists; testing
Binary is fine; exiting

> dtrace-provider@0.8.1 install /opt/reaction/src/node_modules/dtrace-provider
> node scripts/install.js


> bcrypt@1.0.2 install /opt/reaction/src/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.8.1 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/opt/reaction/src/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /opt/reaction/src/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/opt/reaction/src/node_modules/bcrypt/build'

> spawn-sync@1.0.15 postinstall /opt/reaction/src/node_modules/spawn-sync
> node postinstall


> radium@0.18.2 postinstall /opt/reaction/src/node_modules/radium
> cd lib || npm run lib

reaction@1.1.1 /opt/reaction/src
+-- 42-cent-base@1.0.0 
| `-- bluebird@2.11.0  deduped
+-- 42-cent-util@1.0.0 
+-- @reactioncommerce/authorize-net@1.0.8 
| +-- 42-cent-base@1.0.0  deduped
...
+-- yargs-parser@4.2.1 
| `-- camelcase@3.0.0 
`-- zip-stream@1.1.1 
  +-- archiver-utils@1.3.0  deduped
  +-- compress-commons@1.2.0  deduped
  +-- lodash@4.17.4  deduped
  `-- readable-stream@2.2.9  deduped

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[-] Building Meteor application...


Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

cfs:gridfs: updating npm dependencies -- mongodb, gridfs-stream...
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters

[-] Running npm install in the server bundle...


> fibers@1.0.15 install /opt/reaction/dist/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-46` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /opt/reaction/dist/bundle/programs/server
> node npm-rebuild.js


> phantomjs@1.9.16 install /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/phantomjs
> node install.js

PhantomJS detected, but wrong version 2.1.1 @ /usr/local/bin/phantomjs.
Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Extracting tar contents (via spawned process)
Removing /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1492809692358/phantomjs-1.9.8-linux-x86_64 -> /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/phantomjs/lib/phantom/bin/phantomjs
abbrev@1.0.7 /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/abbrev
acorn@1.2.2 /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/acorn
...
async@0.2.10 /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/uglify-js/node_modules/async
uglify-to-browserify@1.0.2 /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/uglify-to-browserify
yargs@3.10.0 /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/uglify-js/node_modules/yargs
window-size@0.1.0 /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/uglify-js/node_modules/window-size
url@0.11.0 /opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/kadira_flow-router-ssr/node_modules/url

> bcrypt@1.0.2 install /opt/reaction/dist/bundle/programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

module.js:327
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/reaction/dist/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp:15:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.meteor/packages/meteor-tool/.1.4.4_1.1t9hste++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-04-21T21_21_37_447Z-debug.log
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.meteor/packages/meteor-tool/.1.4.4_1.1t9hste++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-04-21T21_21_37_478Z-debug.log
The command '/bin/sh -c cd $APP_SOURCE_DIR &&             bash $BUILD_SCRIPTS_DIR/build-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
```

### Steps to Reproduce the Behavior

`reaction init && cd reaction && docker build -t reactionimage . `

### Versions

```
Mac OS X Sierra 10.12.1
Docker version 17.03.1-ce, build c6d412e

Node: 6.2.2
NPM: 4.0.5
Docker: 17.03.1-ce
Reaction CLI: 0.7.13
Reaction: 1.1.1
Reaction Branch: master
```

**Comment by aaronjudd** [comment] 2017-04-26 01:25
Closing, duplicate of #1946

**Closed by aaronjudd** 2017-04-26 01:25 UTC
Labels: deployment
