### ISSUE TITLE
Errors prevented startup

### ISSUE THREAD

**Issue by vdieulesaint** [reactioncommerce/reaction#4887] opened 2018-12-24 14:56 UTC
Hi,

I am unable to start reaction.

OS: Win10
Node: 11.5.0
NPM: 6.4.1
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Docker: 18.09.0

```
Errors prevented startup:

While building for web.browser:
imports/plugins/core/graphql/lib/mutations/updateFulfillmentOptionsForGroup.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/createFlatRateFulfillmentMethod.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/updateFlatRateFulfillmentMethod.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/deleteFlatRateFulfillmentMethod.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/enablePaymentMethodForShop.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/placeOrderWithExampleIOUPayment.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/placeOrderWithStripeCardPayment.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/queries/availablePaymentMethods.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/queries/paymentMethods.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/included/marketplace/client/util/placeMarketplaceOrderWithStripeCardPayment.graphql:1:41: Unterminated string constant (1:41)

While building for web.browser.legacy:
imports/plugins/core/graphql/lib/mutations/updateFulfillmentOptionsForGroup.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/createFlatRateFulfillmentMethod.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/updateFlatRateFulfillmentMethod.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/deleteFlatRateFulfillmentMethod.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/enablePaymentMethodForShop.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/placeOrderWithExampleIOUPayment.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/mutations/placeOrderWithStripeCardPayment.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/queries/availablePaymentMethods.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/graphql/lib/queries/paymentMethods.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/included/marketplace/client/util/placeMarketplaceOrderWithStripeCardPayment.graphql:1:41: Unterminated string constant (1:41)

While building for os.windows.x86_64:
imports/plugins/core/core/server/no-meteor/schemas/address.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/core/server/no-meteor/schemas/base.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/core/server/no-meteor/schemas/currency.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/core/server/no-meteor/schemas/email.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/core/server/no-meteor/schemas/metafield.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/core/server/no-meteor/schemas/node.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/core/server/no-meteor/schemas/shop.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/core/server/no-meteor/schemas/tag.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/accounts/server/no-meteor/schemas/account.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/accounts/server/no-meteor/schemas/group.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/accounts/server/no-meteor/schemas/role.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/cart/server/no-meteor/schemas/cart.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/cart/server/no-meteor/schemas/checkout.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/catalog/server/no-meteor/schemas/schema.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/orders/server/no-meteor/schemas/schema.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/payments/server/no-meteor/schemas/schema.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/product/server/no-meteor/schemas/schema.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/core/shipping/server/no-meteor/schemas/schema.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/included/marketplace/server/no-meteor/schemas/schema.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/included/payments-example/server/no-meteor/schemas/schema.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/included/payments-stripe/server/no-meteor/schemas/schema.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/included/shipping-rates/server/no-meteor/schemas/schema.graphql:1:41: Unterminated string constant (1:41)
imports/plugins/included/sitemap-generator/server/no-meteor/schemas/schema.graphql:1:41: Unterminated string constant (1:41)

Your application has errors. Waiting for file change.
Started MongoDB.
```

**Comment by SergioPolanco** [comment] 2019-01-30 22:03
I have same problem

**Comment by derBretti** [comment] 2019-05-02 07:43
Duplicate of #4779

**Closed** 2019-08-06 19:07 UTC
Labels: windows-only
