### ISSUE TITLE
shipping ui is broken

### ISSUE THREAD

**Issue by medyagh** [reactioncommerce/reaction#2398] opened 2017-06-05 18:51 UTC
### Expected behavior
Shipment methods be toggle-able
### Actual Behavior
the toggle is hidden, unless I click on inspect (in chrome or firefox)

### Versions
I tried both versions
reactioncommerce/prequel:5892
and
reactioncommerce/reaction:latest

**Comment by aaronjudd** [comment] 2017-06-05 23:13
Can you provide a screenshot? that'd be helpful.. we will try to reproduce as well.  prequel 5892 should have the last. Feels like this might be related to #2313 #2224

**Comment by medyagh** [comment] 2017-06-06 02:08
minikube start --kubernetes-version v1.5.1 here is the screenshot, I get same thing both firefox and chrome.
<img width="468" alt="screen shot 2017-06-05 at 9 05 07 pm" src="https://cloud.githubusercontent.com/assets/4564227/26810717/d953758e-4a32-11e7-9eec-5ac721241c05.png">
@aaronjudd 

I dont see any javascript error in the console. and currently I can no longer make the flip button show again by right clicking and doing inspect anymore.

**Comment by hrath2015** [comment] 2017-06-06 02:41
@medyagh  execute `Meteor.call("i18n/flushTranslations");`  from  browser console and see if it fixes

**Comment by nygava** [comment] 2017-06-06 15:17
@hrath2015 i didnt fix it, here is the output in the console

```
Meteor.call("i18n/flushTranslations");
undefined
```

**Comment by medyagh** [comment] 2017-06-06 16:15
same, didnt fix it.

**Comment by hrath2015** [comment] 2017-06-06 16:24
Not sure what is going on then. Do have  this deployed where I can have a look.

**Comment by michael-alade** [comment] 2017-06-06 21:34
@medyagh Could you add the steps to reproduce this error?

**Comment by medyagh** [comment] 2017-06-08 20:42
@michael-alade I did nothing special, created a shop form the scratch using the container. added some products. then I tried to check out a product to test, it yelled at me that I dont have a shipping method, when I tried to go to add a shipment method I fliped one of the methods then it broke after that. never could see the fields.

**Comment by aaronjudd** [comment] 2017-06-12 23:41
Can you retest with v1.2.0 (or latest), from reactioncommerce/reaction.  The version I think you were testing was v1.1.1, which is missing several fixes related to this from the previously linked issues..  due to a problem in our build scripts, 1.2.0 wasn't pushed yet when you reported this..

**Comment by stunjiturner** [comment] 2017-06-15 21:30
i have the same issue running 1.2 on a remote ec2 instance, inside of the docker container

**Comment by kieckhafer** [comment] 2017-06-21 05:03
This is definitely an issue with translations not loading. I ran into it a few times while implementing the new ReactTable. If it's not already fixed (it should be OK if translations load), it will be taken care of when PR #2416 is merged.

**Comment by zenweasel** [comment] 2017-06-21 05:07
I am pretty sure this issue is yet another instance of https://github.com/reactioncommerce/reaction/issues/2313. You can see from the screenshot that both the translations and the shipping methods are missing.

**Comment by kieckhafer** [comment] 2017-06-21 05:26
True, that makes sense... well from a UI perspective, the overflow that pushes everything to the right of the screen should be fixed with #2416 , the underlying cause not so much.

**Comment by zenweasel** [comment] 2017-06-21 05:39
Yeah, the reporting of the issue refers to the UI, but it's really the underlying data that's broken.

**Comment by zenweasel** [comment] 2017-06-30 04:27
Closing this as we believe this was fixed in #2224. Please reopen if not fixed in current builds.

**Closed by zenweasel** 2017-06-30 04:27 UTC
Labels: bug, critical impact, needs-to-be-reproduced
