### ISSUE TITLE
Cannot open Tags admin

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5460] opened 2019-08-15 21:27 UTC
## Issue Description

Cannot view the tags admin panel in the Reaction admin app. I get the following error on http://localhost:3000/operator/tags

```
Uncaught ReferenceError: _objectSpread is not defined
    at control (modules.js:66932)
    at modules.js:44601
    at Control (modules.js:47255)
    at renderWithHooks (modules.js:214457)
    at mountIndeterminateComponent (modules.js:216691)
    at beginWork$1 (modules.js:217835)
    at HTMLUnknownElement.callCallback (modules.js:199696)
    at Object.invokeGuardedCallbackDev (modules.js:199746)
    at invokeGuardedCallback (modules.js:199803)
    at beginWork$$1 (modules.js:222566)
```

This also affests other plugins/pages that use the `<Select>` component from the component library.

## Steps to Reproduce
1. go to http://localhost:3000/operator/tags
2. see a white screen

## Possible Solution

- Seems like a babel issue, so that seems like a good place to start.
- Check the component library for as the problem goes away if the `<Select>` component is not on the page.

**Comment by mikemurray** [comment] 2019-08-15 22:16
|Issue|Page renders|
|--|--|
| Updating babel and various babel-plugins to `7.5.5` | No |
| Updating React to 16.9.0 | No |
| Updating reacto-form to 1.4.0 | No |
| Updating component-library to 0.67.0 | No |
| Removing Select from the page | Yes |
| Copy Select component into Reaction from Component-Library | Yes |
| Using Select component from Component-Library after all these updates | No |

### conclusion
If I use the Select component from the component library then the app breaks in places where it's used. If I use that same exact component copied into Reaction, it works fine. There must be something off in the build process in the `component-library` that's causing this component to be broken in Reaction, but not in it's own documentation site.

**Comment by mikemurray** [comment] 2019-08-19 17:57
To add. If I update the example-storefront to component-library 0.67.0 I also get this error.

![image](https://user-images.githubusercontent.com/42217/63287824-22f33280-c270-11e9-8d8b-d03f9cfd5bfd.png)

**Comment by aldeed** [comment] 2019-08-19 19:41
@mikemurray We may have been including the Babel polyfill with the component library and at some point stopped doing that. I think I made some changes to reacto-form build to not include it. The recommendation is that packages do NOT include polyfills so that just the app using them can do it. Also, using `core-js` directly is recommended instead of `@babel/polyfill` now.

Adding something like `import 'core-js/stable';` somewhere may work, but I'm not sure what magic Meteor may be adding into the mix. More info: https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babel

**Comment by mikemurray** [comment] 2019-08-19 23:11
@aldeed with `core-js` I get the following errors. There's a mismatch between the version I have installed and the one the comp-lib expects. I've tried version `core-js@2` & `core-js@3`. The files it's trying to import are prefixed `es6.`, but in the version I have installed it the files are prefixed with `es.`

```
web_1  | * core-js/modules/es6.array.find in ./node_modules/@reactioncommerce/components/CatalogGridItem/v1/utils/priceByCurrencyCode.mjs, ./node_modules/@reactioncommerce/components/Select/v1/Select.mjs
web_1  | * core-js/modules/es6.array.iterator in ./node_modules/@reactioncommerce/components/AddressForm/v1/AddressForm.mjs, ./node_modules/@reactioncommerce/components/AddressReview/v1/AddressReview.mjs and 1 other
web_1  | * core-js/modules/es6.array.sort in ./node_modules/@reactioncommerce/components/Select/v1/Select.mjs
web_1  | * core-js/modules/es6.function.bind in ./node_modules/react-tracking/build/trackEventMethodDecorator.js, ./node_modules/react-tracking/build/makeClassMemberDecorator.js
web_1  | * core-js/modules/es6.function.name in ./node_modules/@reactioncommerce/components/AddressForm/v1/AddressForm.mjs, ./node_modules/@reactioncommerce/components/ErrorsBlock/v1/ErrorsBlock.mjs and 4 others
web_1  | * core-js/modules/es6.number.constructor in ./node_modules/@reactioncommerce/components/AddressChoice/v1/AddressChoice.mjs, ./node_modules/@reactioncommerce/components/QuantityInput/v1/QuantityInput.mjs and 1 other
web_1  | * core-js/modules/es6.number.is-nan in ./node_modules/@reactioncommerce/components/QuantityInput/v1/QuantityInput.mjs
web_1  | * core-js/modules/es6.object.assign in ./node_modules/react-tracking/build/withTrackingComponentDecorator.js
web_1  | * core-js/modules/es6.object.create in ./node_modules/react-tracking/build/withTrackingComponentDecorator.js
web_1  | * core-js/modules/es6.object.define-property in ./node_modules/react-tracking/build/trackingHoC.js, ./node_modules/react-tracking/build/dispatchTrackingEvent.js and 5 others
web_1  | * core-js/modules/es6.object.keys in ./node_modules/@reactioncommerce/components/AddressForm/v1/AddressForm.mjs, ./node_modules/@reactioncommerce/components/AddressReview/v1/AddressReview.mjs and 1 other
web_1  | * core-js/modules/es6.object.set-prototype-of in ./node_modules/react-tracking/build/withTrackingComponentDecorator.js
web_1  | * core-js/modules/es6.promise in ./node_modules/react-tracking/build/trackEventMethodDecorator.js
web_1  | * core-js/modules/es6.reflect.apply in ./node_modules/react-tracking/build/trackEventMethodDecorator.js, ./node_modules/react-tracking/build/makeClassMemberDecorator.js
web_1  | * core-js/modules/es6.reflect.define-property in ./node_modules/react-tracking/build/makeClassMemberDecorator.js
```

**Comment by janus-reith** [comment] 2019-08-20 06:30
I did not run into issues with the Meteor Backend but the storefront when I dealt with `core-js` so this might be similar:

I can confirm that `core-js@3` on the example-storefront works, but both the example-storefront and the component-library need to have core-js@3 defined in their babel config (and installed).

The default build of the component-library will only work when the storefront is using core-js@2 / not specifing core-js at all. Aliasing all the changed import directories between 2 and 3 single handedly also did not work, I had to rebuild the component-library with `core.js@3`

**Comment by aldeed** [comment] 2019-08-20 19:27
Agree this is probably the same as that 432 issue. I'm not exactly sure why the version of core-js used to build the library package would matter, but perhaps because of the `useBuiltIns` setting. We need to do a build and then examine the output files to see where "core-js" requires are being added.

**Comment by aldeed** [comment] 2019-08-20 20:14
After https://github.com/reactioncommerce/reaction-component-library/pull/433 is merged and published, I'm hopeful that apps will just need either `useBuiltIns: 'entry'` with Babel, or these two imports manually added to the entry point file:

```js
import 'core-js/stable';
import 'regenerator-runtime/runtime';
```

**Closed** 2019-08-22 16:33 UTC
Labels: bug, impact-critical
