### ISSUE TITLE
Getting error while installing Reaction Commerce

### ISSUE THREAD

**Issue by mdiqbalalam** [reactioncommerce/reaction#3350] opened 2017-11-27 13:19 UTC
Hello all, I am trying to install the reaction-shop app.
I have cloned the app from the below url and did the same step and finding following errors that I have attached in image.
https://github.com/reactioncommerce/reaction

Please guide me if I am doing anything wrong with it.

![reaction-shop-error](https://user-images.githubusercontent.com/34030415/33268551-aa58d17a-d3a3-11e7-861c-2fb69a7ed3f1.jpg)

**Comment by jshimko** [comment] 2017-11-27 17:43
Have you installed [Windows build tools](https://github.com/felixrieseberg/windows-build-tools)?

```sh
npm i -g windows-build-tools
```

**Comment by 8enSmith** [comment] 2017-11-27 23:58
I too am getting a "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory" error when trying to run "reaction" in Window 10.

![image](https://user-images.githubusercontent.com/798183/33295583-18a482b2-d3ce-11e7-9836-f730a3ed4362.png)

Note that I have installed the Windows build tools referred to by @jshimko above. Also node and Meteor are using the latest builds.

In the Task Manager, memory usage hovers around ~850MB for around 10 mins (I haven't timed it exactly but this is the ball park figure)

I've noted the warning "npm WARN reaction-connectors-shopify@1.0.0 No repository field." buy I don't think resolving it will fix this critical issue.

Any suggestions on a fix?

**Comment by jshimko** [comment] 2017-11-28 00:05
@8enSmith that is a different issue than the one this was opened for.  See #3023 for the full discussion and current solution for that.

**Comment by mdiqbalalam** [comment] 2017-11-28 07:17
thanks for your reply @jshimko 
I also installed the build tools as suggested by you.
npm i -g windows-build-tools

now I am getting different error. Please have a look on the attached image.

![reaction-installing-error-2](https://user-images.githubusercontent.com/34030415/33306845-338aeda2-d43a-11e7-9fc2-7fcedfbc0795.jpg)

**Comment by jshimko** [comment] 2017-11-28 17:33
@mdiqbalalam that is the same issue I mentioned the previous commenter.  See #3023 and my above response.  

Closing this issue because it appears to have been the missing Windows build tools.  And the next issue was a duplicate of #3023.  Any further discussion on that issue should move to that thread instead.

**Closed by jshimko** 2017-11-28 17:33 UTC

**Comment by jshimko** [comment] 2017-11-28 17:35
Specifically, see this comment for the explanation and solution: https://github.com/reactioncommerce/reaction/issues/3023#issuecomment-342510093

**Comment by 8enSmith** [comment] 2017-11-28 23:25
@jshimko When I saw that @mdiqbalalam changed the title from "Getting FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory while starting the reaction app" I assumed that this post was relevant to my issue, My bad!

I'll check out #3023. Thanks for the quick response, really appreciated.

**Comment by mdiqbalalam** [comment] 2017-11-29 06:43
Thanks for your reply @jshimko. I will look into #3023.
