### ISSUE TITLE
Problem after reaction init

### ISSUE THREAD

**Issue by wrux** [reactioncommerce/reaction#4236] opened 2018-05-09 11:32 UTC
I installed reaction-cli, run `reaction init` then cd into the directory and run `reaction` and I get the following error and it just loops through this and says `Building for web.browser`

```
Error: $MONGO_OPLOG_URL must be set to the 'local' database of a Mongo replica set
    at OplogHandle._startTailing (packages/mongo/oplog_tailing.js:218:13)
    at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
    at new MongoConnection (packages/mongo/mongo_driver.js:214:25)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Collection (packages/mongo/collection.js:97:40)
    at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /Users/callum/Desktop/reaction/reaction/.meteor/local/build/programs/server/packages/accounts-base.js:2010:15
    at /Users/callum/Desktop/reaction/reaction/.meteor/local/build/programs/server/packages/accounts-base.js:2017:3
    at /Users/callum/Desktop/reaction/reaction/.meteor/local/build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /Users/callum/Desktop/reaction/reaction/.meteor/local/build/programs/server/boot.js:220:19
    at /Users/callum/Desktop/reaction/reaction/.meteor/local/build/programs/server/boot.js:471:5
    at Function.run (/Users/callum/Desktop/reaction/reaction/.meteor/local/build/programs/server/profile.js:510:12)
    at /Users/callum/Desktop/reaction/reaction/.meteor/local/build/programs/server/boot.js:470:11
```

What am I missing here? 

Mongo & Meteor versions:
- Mongo: v3.6.4
- Meteor 1.6.1.1

If I look at the [base requirements](https://docs.reactioncommerce.com/reaction-docs/master/requirements) page then it just shows a loading indicator and nothing else.

**Comment by janus-reith** [comment] 2018-05-14 10:44
The issue could be caused by your version of mongoDB.
As far as I know Meteor 1.6 requires mongo v3.4, while support for v3.6 will be introduced in Meteor 1.7.

**Comment by hsiangminyu** [comment] 2018-07-06 09:35
i also got this issue with Mongo: v3.6.5 and Meteor v1.7.0.3. Dying to know if there's any way out?

**Comment by aldeed** [comment] 2019-07-11 03:29
This may happen when `MONGO_OPLOG_URL` is set incorrectly or oplog isn't enabled on the Mongo side, but that shouldn't happen if following the prescribed steps for running the platform.

**Closed by aldeed** 2019-07-11 03:29 UTC
