### ISSUE TITLE
paypal-rest-sdk causing crash on order details

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1124] opened 2016-07-01 07:19 UTC
For bugs, please fill out the three following sections completely

### Expected behavior
Click on order details in `http://localhost:3000/reaction/dashboard/orders` should not load any paypal methods.

### Actual Behavior

Appears to attempt to load paypal-rest-sdk on every order in order dashboard.

Causes Meteor to crash and a repeating crash-restart loop.

```js
/Users/aaronjudd/ongoworks/reaction/node_modules/paypal-rest-sdk/lib/client.js:146
            cb(err, response);
            ^
TypeError: undefined is not a function
    at IncomingMessage.<anonymous> (/Users/aaronjudd/ongoworks/reaction/node_modules/paypal-rest-sdk/lib/client.js:146:13)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)
=> Exited with code: 8
```

### Steps to Reproduce the Behavior

Place a couple of orders, click on them in dashboard for details, observe server logs.

**Comment by zenweasel** [comment] 2016-07-12 02:28
Testing this now I cannot reproduce.

**Comment by zenweasel** [comment] 2016-07-13 22:59
Still can't reproduce. Closing.

**Closed by zenweasel** 2016-07-13 22:59 UTC
Labels: critical, development, in progress, regression

**Comment by aaronjudd** [comment] 2016-07-13 23:33
As noted in #1126 ->`check refund for authorizationId` resolved this.
