### ISSUE TITLE
Disable shipping methods when triggering shipping recalculation

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2863] opened 2017-09-14 19:54 UTC
The user experience in the checkout when shipping changes is a bit disconnected, as it's not always clear when shipping is being recalculated.  Whenever recalculation is triggered,  it'd be good be that the existing shipping methods, selected or not, should become disabled and existing selection reset while the user is informed of this progress.

### Expected behavior
To see that my cart is recalculating shipping rates and see have feedback on the process progress.

### Actual Behavior

Nothing happens until the rate is re-calculated and has been returned. This can be quick, but sometimes rates can take 5-10 second, which is enough time to get bored and click more stuff.

### Steps to Reproduce the Behavior
Add two shipping methods, switch back and forth. Observe, wait, observe...  Even if the rates are returning lightning quick, you'll start seeing the bad user experience quick enough. It's easy enough to mistake this for nothing have happened. 

### Versions
Node: 6.11.1
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: folusho-fix-shipping-methods-not-configured-2265 (marketplace)
Docker: 17.06.1-ce

**Comment by rymorgan** [comment] 2017-09-14 21:20
@aaronjudd Are we talking when an admin adds a shipping method? Or when a user clicks between say, a fedex method and ups method?

**Comment by rymorgan** [comment] 2017-09-14 22:17
Here are my console errors. 
Exception in template helper: TypeError: Cannot read property 'provider' of undefined
    at Object.shippoCarrier (http://localhost:3000/app/app.js?hash=3dc3925f6c11839ccbd726da5a841aac73cb99bf:33289:28)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3051:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1715:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3103:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3102:27
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:172:18)
    at http://localhost:3000/app/app.js?hash=3dc3925f6c11839ccbd726da5a841aac73cb99bf:32864:26
    at wrappedArgFunc (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2960:14)
    at Blaze.View.<anonymous> (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2673:26)

**Comment by aaronjudd** [comment] 2017-09-14 22:25
@rymorgan looks like you have methods, and have multiple addresses, so there's a legit bug there - at the very least in the error capturing.  I've sometimes seen this when logged in as admin, and is a different issue than the one that I hope was just resolved in #2738.  If you go incognito, do you experience the same issue?  (it's like the same issue I was reporting last on #2738, but for admin, not guest).

**Comment by aaronjudd** [comment] 2017-09-18 22:51
This is a blocker because of the undefined variable that are not properly being checked (reported by @rymorgan ), not because of the reported shipping issue.

**Comment by spencern** [comment] 2017-09-25 21:32
Not a blocker because it's not a regression, but high priority for next release.

**Comment by Akarshit** [comment] 2018-02-09 14:05
When changing the shipping method, the user doesn't get feedback that something is changing though the shipping cost and total is updated(almost instantaneously).
The lack of feedback can be seen from the recording below.

![](http://g.recordit.co/fw5o1ZSkTz.gif)

**Comment by zenweasel** [comment] 2018-02-11 23:14
I can't tell from re-reading this ticket whether we are talking about the delay in getting shipping rates or the delay when selecting a shipping rate for recalculating the cart.

**Comment by cassytaylor** [comment] 2018-02-14 00:24
The way I've decided to approach this from an experience standpoint is by showing a loading state in the "Review" box, when the total is being refreshed after selecting a new shipping option-

https://drive.google.com/open?id=13xCOsXEoqDJRXaZ8FM1iIyM30BdA88Iw (video mockup, so it's a gDrive link) 

Showing that the totals are being recalculated with a loading animation should be enough to convey progress, so disabling the shipping options during the refresh probably wouldn't be necessary. If someone were to change shipping options while it totals are being re-calculated, the loading state would just continue until the new total is available.

**Comment by cassytaylor** [comment] 2018-02-14 00:24
<img width="1070" alt="screen shot 2018-02-13 at 5 24 35 pm" src="https://user-images.githubusercontent.com/36006187/36181617-c91545c2-10e2-11e8-9ba3-2a26f007881a.png">
https://drive.google.com/open?id=13xCOsXEoqDJRXaZ8FM1iIyM30BdA88Iw

**Comment by Akarshit** [comment] 2018-02-20 13:56
@zenweasel In my testing, whenever I chose another method the calculation was fast enough that the loader can't be shown in that time. 
I am adding a delay in my PR for the calculation(which I know is the wrong way). Is this what people wanted?

**Comment by rymorgan** [comment] 2018-02-20 17:00
@Akarshit - In this case, a (a super fast) delay is ok. The important thing here is to notify (assure the user that the action they've taken has done what that intended.)

**Comment by rymorgan** [comment] 2018-02-20 17:10
yes, I want @cassytaylor or I to review before it's merged.

**Comment by cassytaylor** [comment] 2018-02-20 17:46
@Akarshit just added an approval in the PR. I agree with @rymorgan that the fast delay + spinner animation works here, because it gives the user feedback that something is happening (even if we have to fake a short loading delay.)

**Closed** 2018-03-14 07:27 UTC
Labels: UIX, bug, design-complete, impact-minor
