### ISSUE TITLE
out off memory

### ISSUE THREAD

**Issue by vshvydky** [reactioncommerce/reaction#1305] opened 2016-08-17 13:58 UTC
Please help.
I install reaction on server (uname -a
Linux 1328 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u2 (2015-07-17) x86_64 GNU/Linux
)
and run:
 reaction

Using settings file at settings/dev.settings.json

Setting up plugin imports...

[[[[[ ~/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.

after the launch of the node consumes 100% of CPU time. The process is killed with excess memory.

### SYSLOG: 
Aug 17 16:37:10 1328 kernel: [  960.882633] Out of memory: Kill process 2260 (node) score 819 or sacrifice child
Aug 17 16:37:10 1328 kernel: [  960.883109] Killed process 2260 (node) total-vm:2191072kB, anon-rss:858776kB, file-rss:0kB

**Comment by jshimko** [comment] 2016-08-17 14:20
How much memory do you have?

**Comment by vshvydky** [comment] 2016-08-17 15:54
vps 1GB

**Comment by jshimko** [comment] 2016-08-17 16:18
1GB _should_ be enough.  We have users that deploy on servers with that much RAM all of the time.  

Since this doesn't appear to be a problem anyone else is having, I'm going to need a little more info.  Can you please share a list of steps to reliably reproduce this with a completely fresh install on a fresh server?

**Comment by jshimko** [comment] 2016-08-17 16:22
Also, I'm going to close this issue because I don't believe there's actually something wrong with the code.  Can you please continue this conversation on the forum instead?  That's where we prefer to handle general usage and support questions.

https://forums.reactioncommerce.com/

**Closed by jshimko** 2016-08-17 16:22 UTC
