### ISSUE TITLE
Search only displays results once 4 or more characters have been typed

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3390] opened 2017-12-11 19:50 UTC
### Expected behavior
Search should be configurable to choose the amount of letters than need to be typed before the results start to show

### Actual behavior
Search only displays results once 4 or more characters have been typed

### Steps to reproduce the behavior
Start typing in search
see that results only show once 4 letters have been typed

### Versions
Node: 9.2.1
NPM: 5.6.0
Meteor Node: 8.8.1
Meteor NPM: 5.4.2
Reaction CLI: 0.24.2
Reaction: 1.6.0
Reaction branch: master
Docker: 17.11.0-ce

**Comment by impactmass** [comment] 2018-01-09 20:25
In my tests, the search is not limited to 4 characters. I looked into the search related code and did not find any part preventing firing search until certain char length is typed.

Here's a screenshot with a search of 3 chars:
![screenshot 2018-01-09 21 08 32](https://user-images.githubusercontent.com/5229321/34740932-5a542c2e-f581-11e7-8143-f318a442e998.jpg)

If this is the case, then we _won't_ also need this to be configurable.

@kieckhafer, please take a moment to confirm if this works for you now. If it works, this can ve closed.
- Ensure you have a product that contains the [< 4 char] word being searched for (e.g A product with red in it's title). 


One thing I noticed is that full word match is required to get product results. I'm not yet sure if this is by design (or a bug)
![screenshot_2018-01-09_21_17_42_and_screenshot_2018-01-09_21_17_54_and_screenshots](https://user-images.githubusercontent.com/5229321/34741617-7f81d314-f583-11e7-960d-822404297f82.jpg)

**Comment by kieckhafer** [comment] 2018-01-09 23:01
@impactmass I think you're correct. Seems like it's a full-word result, not a 4-letter limit.

At the time of my testing, most of my products were on a secondary shop, so while I was searching for 3 letter words, such as `red`, those products were on the secondary shop, which wasn't showing up at all in search. I'm guessing only 4-letter words were showing up because those were what were on the primary shop.

**Comment by zenweasel** [comment] 2018-02-14 00:16
@kieckhafer It was part of the spec at the time that we weren't doing partial word search, definitely not a bug.

**Comment by zenweasel** [comment] 2018-02-14 00:18
Closing this since the "four letter" search constraint is not real. If we want to add partial word search we can open a new ticket for that.

**Closed by zenweasel** 2018-02-14 00:18 UTC
Labels: enhancements
