### ISSUE TITLE
Order Details (product) does not appear when user place an order.

### ISSUE THREAD

**Issue by marceloibanez** [reactioncommerce/reaction#6234] opened 2020-04-28 23:22 UTC
## Issue Description
Order Details (product) is not displayed from order received (admin side)after user place an order.

## Steps to Reproduce

1. shopper select a product from catalog.
2. shopper checkout the order
3. shopper fill all the information name, address, payment method, billing addres etc.
4. shopper place order.
5. everything is Ok in this point
6. vendor go to admin box.
7. vendor go to order received.
8. Order is in the list, 
9. vendor click in order received
10. vendor does not see all order detail. missing payment information, Product etc

### Versions
trunk

**Comment by MohanNarayana** [comment] 2021-01-20 19:09
Following the repro steps the order shows blank. Navigate to products immediately and console throws a graphQL error (access denied). GraphQL playground runs without any issue.

**Comment by loan-laux** [comment] 2021-02-22 12:30
@nnnnat This is fixed now. Can't reproduce anymore. See https://github.com/reactioncommerce/reaction-admin/pull/337.

**Closed as completed** 2021-02-23 15:26 UTC
Labels: verified reproducible, bug, core work
