### ISSUE TITLE
Shipping rates are not loaded for succeeding checkouts

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction#4503] opened 2018-08-06 06:57 UTC
## Issue Description
Shipping rates are not loaded after first checkout.

## Steps to Reproduce
1. As admin, setup a payment method and enable a flat shipping rate.
2. As a consumer, add a product to your cart. Sign in or register to an existing account. Checkout and pay.
3. Create another order using the same account. Checkout. Address is loaded but the shipping rates will not be loaded.

## Possible Solution
None

### Versions
```
Node: 8.11.2
NPM: 5.6.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: release-1.14.0
Docker: 18.03.1-ce
```

**Comment by willmoss1000** [comment] 2018-08-25 00:10
Patched this locally - perhaps not optimal by:
```

**Comment by willmoss1000** [comment] 2018-08-25 00:16
Patched this locally - far from optimal, but may be helpful for other users who need this fixed urgently:

i) in `createCart.js`  pushing workflow for carts for known users one step further to `coreCheckoutShipping`
```
  Meteor.call(
      "workflow/pushCartWorkflow", "coreCartWorkflow",
      "coreCheckoutShipping", cart._id
    );
```
i) in `checkout.js` - if the workflow is `coreCheckoutShipping` update the shipping methods :
Under `Template.cartCheckout.onCreated(function onCreated() {` 
```
if (cart && cart.workflow && cart.workflow.status === "coreCheckoutShipping") {
      Meteor.call("shipping/updateShipmentQuotes", cart._id);
    }
```

**Comment by willmoss1000** [comment] 2018-08-27 22:56
Patched locally - hope this is of some help:

- `getDefaultAddress` uses `userId` still instead of `accountId`

- On adding items to cart for logged in users I push the workflow to `coreCheckoutShipping`

**Comment by willmoss1000** [comment] 2018-08-30 11:05
In addition:
`getDefaultAddress` takes `accountId` from the cart - which doesn't exist for anonymous users. This section should be replaced with:
```
  const userId = Meteor.userId();
  const account = Accounts.findOne({ userId });
```

**Comment by aldeed** [comment] 2019-07-11 03:48
I believe this was referring to the old checkout UI and can probably be closed now if confirmed fixed.

**Comment by mpaktiti** [comment] 2019-07-12 08:52
@zenweasel I cannot reproduce this, the flat shipping rate is loaded both times. So it looks like this has been fixed.

Before I close this, confirm something for me please. Step 3 says:
> Create another order using the same account. Checkout. Address is loaded but the shipping rates will not be loaded.

The "Address is loaded" part did not work for me, I had to re-enter my address. Was it supposed to be auto-populated? I had a look at the DB and I can see the address info as part of the `Orders` collection, not the `Accounts`.

**Comment by ajporlante** [comment] 2019-07-12 09:09
Hello @mpaktiti . Back then, we didn't have the starter kit yet - shop and checkout run within Reaction. If I remember it correctly, this issue is for that old checkout page within Reaction which is no longer supported so we can close this issue.

**Comment by mpaktiti** [comment] 2019-07-12 12:47
Closing, cannot reproduce.

**Closed by mpaktiti** 2019-07-12 12:47 UTC
Labels: bug, impact-major, regression
