### ISSUE TITLE
Audit permissions for accounts in user accounts dashboard

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1651] opened 2016-12-20 01:42 UTC
1) Go through all account permissions and make sure toggling is correctly granting admin and client control / access
2) Fix all labels to make sure permissions show an appropriate title / label
3) Add "Groups", which allow you to select a type of user (i.e. Admin, Accounts, Products, etc), and automatically grants you the appropriate access

**Comment by aaronjudd** [comment] 2016-12-20 04:14
Also see related permissions issues, covering changes in permissions being made now for marketplace #1591 #1622.  A recent bug reported as well with #1641 (which this issue covers), and   a legacy issue #797, which also covers testing.

**Comment by aaronjudd** [comment] 2017-02-07 19:00
Related to #1642

**Comment by impactmass** [comment] 2017-03-07 18:37
I'm testing this out on `wip-release-0.20.0`. What I see is when I add more permissions to a new account, and I go to that account, the extended privileges don't kick-in. It still behaves as a normal account without the extra permissions (which I believe is #1 point mentioned above)  
That's what I'm taking a look into first.

**Comment by impactmass** [comment] 2017-04-04 01:56
An update on step 1 mentioned on this ticket:
> One case where granted permissions are not currently working as I think it should is being able to access to menu items on nav dropdown, after the right permission is given to an account. That is:

**Expected behavior:** After giving an account the access to "Accounts", "Dashboard" etc [(screenshot)](https://cloud.githubusercontent.com/assets/5229321/24638154/407bd93a-18de-11e7-8242-bb3091c1cdbe.jpg). The account should be able to see these options when the nav [dropdown is clicked](https://cloud.githubusercontent.com/assets/5229321/24638346/8d144178-18df-11e7-9f6c-d00ba7b9b1c4.jpg).

**Actual Behavior**: The new access doesn't reflect in the options [as shown](https://cloud.githubusercontent.com/assets/5229321/24638302/4817f240-18df-11e7-8c67-49c1b62f5eef.jpg)

**Steps to Reproduce the Behavior:** Follow as shown in the first screenshot.

I've traced this to the fact that the [filter used when querying](https://github.com/reactioncommerce/reaction/blob/master/client/modules/core/helpers/apps.js#L93) for matching Packaging e.g
```
{
  "registry.provides": "shortcut",
  "enabled": true,
  "registry.audience": {
    "$in": [
      "account/profile",
      "guest",
      "product",
      "tag",
      ...
    ]
  },
  "shopId": "xxxxxx"
}
```
does not match the way the data is stored. I currently haven't seen a Package with a registry array that has "audience" on it.

**Comment by impactmass** [comment] 2017-04-20 08:12
Current status:
* After digging into inconsistencies around the use of `audience` and `permissions` for registry entries, I'm now able to selectively show items in settings/accounts section of the admin dashboard. It's no more an all (for admin) or nothing (for other accounts).
* TODO: Check that appropriate items show in the dashboard based on permission/access. There are still some inconsistencies.
* [Current diff](https://github.com/reactioncommerce/reaction/compare/development...seun-audit-package-access)
* Looking forward to getting to a WIP PR today. 🤞

**Comment by impactmass** [comment] 2017-04-25 08:16
Status is being tracked on WIP PR here #2145

**Comment by impactmass** [comment] 2017-04-25 17:50
Status on the different parts of this:

1. The first issue: Granting access to admin dashboard immediately opens all packages/settings to a non-admin. This should be fixed after (WIP) #2145 passes review and gets merged. It's still WIP because there are some parts needing clarification (see PR).

2. While working on *1 above, I started an audit of all dashboard permissions toggling. Current status is reported on #2145 as well. Issues discovered can be split to another issue.

3. Ensuring appropriate label for all permissions. All the labels seem fine at the moment.

4. "Groups" (mentioned in this issue's description). Yet to be started.

**Comment by impactmass** [comment] 2017-04-25 21:52
Audit status (see *2 in comment above)

**Confirming Top-Level & Sub-level Toggling of permissions**
(Checked items works. Unchecked items - yet to confirm. Other comments are for issues spotted)
- [x] Accounts ("reaction-accounts")
- [x] Accounts ("accounts") [Access to the whole accounts sidebar]
- [ ] Account Settings ("reaction-accounts/accountsSettings") [can't figure out what this should do]
- [ ] Accounts ("dashboard/accounts")  [can't figure out what this should do]
- [x] Profile ("account/profile")
- [x] Catalog (gives access to catalog section of dashboard)
- [x] Checkout ("reaction-checkout")
- [x] Checkout ("cart/checkout")
- [ ] /Cart/Completed/:_id? ("cart/completed") [Able to see the page without access given]
- [x] Dashboard ("reaction-dashboard")
- [x] Dashboard ("dashboard")
- [ ] Shop Settings ("shopSettings") [Doesn't show/hide shop settings] (Should we even have this? The "Accounts" counterpart doesn't)
- [ ] Discounts ("reaction-discounts") [Has access to "Codes" under Payments tab; regardless of access level. Gets access denied when creating code every time]
- [x] Email
- [x] I18n
- [ ] Layout ("reaction-layout") [Haven't figure out what this does]
- [ ] Logging ("reaction-logging") [This is a mostly server-side pkg. Should probably not show up in the list?]
- [x] Orders ("reaction-orders")
- [x] Orders ("orders") [Issue: When with access to the Orders panel...the count (new, processing, completed) shows 0, but Orders are shown in the sections if available... possibly caused by the publication]
- [x] Orders ("dashboard/orders") 
- [x] /Dashboard/Pdf/Orders/:Id ("dashboard/pdf/orders") [Not working. User gets access to this page regardless if it's on/off]
- [x] Payments ("reaction-payments")
- [x] Revisions ("reaction-revisions")
- [x] Shipping ("reaction-shipping")
- [x] Shipping ("shipping") 
- [x] Tax ("reaction-taxes")
- [x] Templates
- [ ] Ui ("reaction-ui"), Themes ("reaction-ui/uiDashboard"), /Dashboard/Ui/:Id ("dashboard/uiThemeDetails"), Ui Grid, Ui Navbar, Ui Tagnav, Ui Search & Migrations. All these don't have admin functions?
- [x] Analytics ("reaction-analytics") 
- [ ] Analytics Settings ("reaction-analytics/reactionAnalyticsSettings") Confirm difference between this and above
- [x] Discount Codes

Other questions:
- [x] Confirm this behavior: Removing access to `Profile` under `Accounts`, still shows the profile shortcut icon. Although when it is clicked, a `You don't have permission to view this content` message is shown. 
- [ ] Should removing access to `Accounts` (or more specifically `Profile` under `Accounts`) also takes away username beside avatar?

**Comment by aaronjudd** [comment] 2017-04-25 23:46
- Account Settings ("reaction-accounts/accountsSettings") [can't figure out what this should do]

-  Accounts ("dashboard/accounts") [can't figure out what this should do]

- Shop Settings ("shopSettings") [Doesn't show/hide shop settings] (Should we even have this? The "Accounts" counterpart doesn't)

Yes, shop settings is the default screen that all shop admins should configure (name,etc).  This should be visible.

-  Discounts ("reaction-discounts") [Has access to "Codes" under Payments tab; regardless of access level. Gets access denied when creating code every time]

If "Codes" is enabled, they should always be visible (to all users). I think that I made a special case for this (but not sure).  ie, you would always want users to be able to input codes, but not create them.

-  Layout ("reaction-layout") [Haven't figure out what this does]

I think this can be removed from the registry.  We were going to build a UI to allow selection of layouts/themes.  On hold for a bit...

-  Logging ("reaction-logging") [This is a mostly server-side pkg. Should probably not show up in the list?]
 
Feel like this was supposed to be for loggly configuration @jshimko?  The credentials have to be configured as ENV variables, but this should have settings.( this was mentioned / implemented in  #1574. I created #2165 to track the UI component.

- Ui ("reaction-ui"), Themes ("reaction-ui/uiDashboard"), /Dashboard/Ui/:Id ("dashboard/uiThemeDetails"), Ui Grid, Ui Navbar, Ui Tagnav, Ui Search & Migrations. All these don't have admin functions?

These are all components @mikemurray .. some of these should respect permissions I would think. however.. maybe these should be ignored for now as well?

-  Analytics Settings ("reaction-analytics/reactionAnalyticsSettings") Confirm difference between this and above

Hmmm.. I don't see analytics in admin or guest view.  I'll have to dig in there.

**Comment by aaronjudd** [comment] 2017-04-25 23:53
![basic_reaction_product_and_reaction_and_issues_ _reactioncommerce_reaction](https://cloud.githubusercontent.com/assets/439959/25412459/b41c7a3e-29d7-11e7-8c18-73059ad90387.png)

**Comment by impactmass** [comment] 2017-05-02 08:30
Status: PR review in progress (#2145)

**Comment by kieckhafer** [comment] 2017-10-10 18:10
@impactmass do you think all your permissions updates took care of this?

**Comment by impactmass** [comment] 2017-10-11 13:44
The permissions epic took care of mostly point 2 and 3 mentioned on the description of this ticket. There is more work to be done around  point 1. I'll go through the issues and write up a new ticket that will take over (and close this off).

**Comment by spencern** [comment] 2017-10-12 00:04
@mikemurray and I discovered today during our final review of 1.5 that the dashboard does does not take permissions into account when determining which modules are available to the user. It appears that the dashboard permission is the only one that mattered.

**Comment by aaronjudd** [comment] 2018-02-01 16:14
@impactmass @spencern please update status on this issue.

**Comment by impactmass** [comment] 2018-02-02 12:23
Point 1 and part of 2 was covered in #2145 #2235. Point 3 (Groups) was completed as part of #2183.
There is now a UI/UX epic issue for accounts admin, and that can cover the labels display. It's better to work on them there because the labels at the time this issue was created is different from what it is now. 

@spencern re: your last comment.... please confirm if the issue you mentioned  is still happening. I currently don't see it. (also after the fix done in #2183 and more recently #3505). 
I think we can close this ticket it that is working correctly.

**Comment by spencern** [comment] 2018-02-02 15:20
@impactmass as that comment is from October and you're not seeing it, I think we can close.

**Comment by aaronjudd** [comment] 2018-02-02 16:20
I was seeing issues while testing master (1.7.0) - needs a comprehensive review, and most likely a new issue created.  Specifically some changes did not appear to take affect. Some gave errors, and I  also "changed owner" and hit the "cancel" and the owner changed regardless of cancel, etc.  these could all be new issues -> but am suggesting another review is necessary.

**Comment by impactmass** [comment] 2018-02-05 20:31
Went through as mentioned by @aaronjudd. I found and create issues: #3648 and #3649.
Both related to the group permissions setup in #2183 and #2184 (more recent tickets than this one). We can close this in favor of those.

**Comment by zenweasel** [comment] 2018-02-14 00:02
@impactmass So is this ready to close?

**Comment by impactmass** [comment] 2018-02-14 13:14
yes can be closed, in favor of the new issues created above, plus the UI epic (#2922)

**Closed by impactmass** 2018-02-14 13:14 UTC
Labels: UIX
