### ISSUE TITLE
publishProductToCatalog is using fixed variant fields

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#4430] opened 2018-07-13 13:30 UTC
## Prerequisites
* [ x ] Are you running the latest version?
* [ x ] Are you able to consistently reproduce the issue?
* [ x ] Did you search the issue queue for existing issue? 

## Issue Description
When the ProductVariant schema is extended, all custom fields get lost when the product containing the variant is published to Catalog.

## Steps to Reproduce
1. Extend the ProductVariant schema
2. Create and publish a product with a variant that is using these custom fields.
3. Notice how the published variant in the Catalog is missing these fields.

## Possible Solution
`publishProductToCatalog` in `/imports/plugins/core/catalog/server/no-meteor/utils/publishToCatalog.js` prepares the new variants to be inserted into Catalog with a function `xformVariant`
This function copies over all default variant fields one by one.

It should be modified to make use of the ProductVariant Schema
or
It maps all fields of the original variant and recreates them, as the field names are the same.
Fields that need to be reformed could still be queried and altered in the mapping.

### Versions
1.13.1

**Comment by zenweasel** [comment] 2018-07-15 22:52
@janus-reith I believe this is a duplicate of https://github.com/reactioncommerce/reaction/issues/4373 ?

**Comment by janus-reith** [comment] 2018-07-16 15:05
You are right, missed that one

**Closed** 2018-07-16 15:08 UTC
