### ISSUE TITLE
Add address validation

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1625] opened 2016-12-13 18:51 UTC
Add address validation to checkout steps. Maybe use google dropdown to verify address with form fields as a fall back for addresses that don't show up.

**Comment by aaronjudd** [comment] 2017-01-11 01:09
@zenweasel this maybe be required for #1704, Avalara should be performing address validation before order tax submission, at least.

**Comment by zenweasel** [comment] 2017-01-24 00:57
I think this is probably mislabeled a UX ticket, because most of the address validation needs to be done on the backend. And as @aaronjudd mentioned, this is required for Avalara (and any tax package for that matter) to work correctly.

**Comment by zenweasel** [comment] 2017-01-24 01:55
This ticket is actually a duplicate of #1021. Closing.

**Closed by zenweasel** 2017-01-24 01:55 UTC
Labels: in progress
