### ISSUE TITLE
Create integration tests for order methods

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2095] opened 2017-04-07 15:46 UTC
Except for the ones that Micheal created for cancel order, there currently are no tests for the order methods. Each method should have at least two tests and probably more.

This will probably also require some rewriting of the current order fixtures.

**Comment by michael-alade** [comment] 2017-04-12 10:05
I understand how this issue should be implemented. I discovered that a few of the order methods were not used in the reaction codebase, so I would be taking them away.

**Comment by michael-alade** [comment] 2017-04-19 09:07
The issue is currently stalled because I need to complete the cancel order issue. I would be getting back to after the cancel order issue has been resolved

**Comment by michael-alade** [comment] 2017-04-24 08:22
I am currently writing more test for the order methods. I would push for a PR later on today.

**Comment by michael-alade** [comment] 2017-04-28 08:22
I am 95% done with the test for the order methods. I'm just left with a minor blocker on testing a failed meteor method call that expects a result from a callback.

**Comment by michael-alade** [comment] 2017-05-01 23:59
I am currently done with test. I am awaiting it to be reviewed.

**Comment by michael-alade** [comment] 2017-05-02 13:38
The Issue has been closed by #2159

**Closed by michael-alade** 2017-05-02 13:38 UTC
Labels: in progress, review, testing
