### ISSUE TITLE
Should be able to add images to a base product

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3728] opened 2018-02-12 22:37 UTC
### Expected behavior
As an administrator, I should be able to upload images to the base product from the PDP. I should be able to deselect the default variant, or we could consider not having a default selected variant for users with ~`product-variant` roles. After deselecting from any active variant, I should be able to upload or remove images from the base product.

### Actual behavior
![image](https://user-images.githubusercontent.com/1203639/36123005-9a1a1502-1008-11e8-9dd0-f359006da201.png)

I cannot upload images to a base product because there is a default variant selected and there is no way to deselect.

### Steps to reproduce the behavior
1. Create a product or visit the PDP page for the default product
2. Attempt to add a product image to the base product.
3. Observe that all product images are added to the selected variant or option.

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.12.0-ce
```

**Comment by aldeed** [comment] 2019-07-11 03:04
Duplicate of https://github.com/reactioncommerce/reaction-feature-requests/issues/103

**Closed by aldeed** 2019-07-11 03:04 UTC
Labels: bug, design, impact-minor
