### ISSUE TITLE
Stripe connect guest checkout email form needs client validation

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3733] opened 2018-02-13 01:56 UTC
### Expected behavior
When an email address is required before continuing past the first step of the checkout process, we should validate the submitted email address against some type of email regex to ensure it's at least in the right format

### Actual behavior
On the first step of the checkout when email addresses are required (Stripe Connect), a user can skip past the email input form by submitting it without entering any email address. There isn't any client-side validation done.

<img src="http://g.recordit.co/hlGPryCgNE.gif">

### Steps to reproduce the behavior
1. Setup a shop using Stripe as the payment provider
2. Add a product to your cart and start a checkout as a guest user.
3. On the first step of the checkout, click "Continue as guest", 
4. When prompted, submit the email form by clicking "Add email" without entering anything into the input field.

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.12.0-ce
```

For enhancements or other issues, please describe, in as much detail as
possible, how the app should be changed, and how this would benefit other users and developers.

**Comment by zenweasel** [comment] 2018-03-05 02:45
I believe this issue is a duplicate of #3500 but keeping this one because it has more detail. Also bumping this up to major since since this affects checkout.

**Closed** 2018-03-08 18:05 UTC
Labels: bug, impact-major
