### ISSUE TITLE
Translation missing on toast alert when sending marketplace invitation to owner

### ISSUE THREAD

**Issue by sophiehe** [reactioncommerce/reaction#3696] opened 2018-02-09 01:28 UTC
### Expected behavior
After sending a marketplace invitation to owner, toast alert should display 'Invitation sent' type message.

### Actual behavior
![image](https://user-images.githubusercontent.com/20484811/36007034-5c5b7140-0cf5-11e8-87c7-f4e8e92d3b28.png)

### Steps to reproduce the behavior
1. Click on Shop.
2. Click on Marketplace to open invite panel.
3. Fill in fields to invite owner. 
4. Click 'Send invitation.' 

### Versions
Node: 6.5.0
NPM: 3.10.3
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.19.0
Reaction: 1.8.0
Reaction branch: release-1.8.0

For enhancements or other issues, please describe, in as much detail as
possible, how the app should be changed, and how this would benefit other users and developers.

**Comment by prinzdezibel** [comment] 2018-02-12 18:26
This is most probably a duplicate of: https://github.com/reactioncommerce/reaction/issues/3694

**Comment by aldeed** [comment] 2018-09-28 21:01
Closing as assumed fixed by https://github.com/reactioncommerce/reaction/pull/3724

**Closed by aldeed** 2018-09-28 21:01 UTC
Labels: bug, i18n + l10n, impact-minor
