### ISSUE TITLE
Research + present on React component re-rendering

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#3236] opened 2017-11-03 20:09 UTC
## Answer these questions  
 - Are the actions that are slow also the actions w/ re-rendering React components?
 - Which components re-render the most in the app?
 - What are the areas of the app where the components re-render multiple times? Specifically the side panel in Admin.

## Part of 
https://github.com/reactioncommerce/reaction/issues/3233

**Comment by aaronjudd** [comment] 2018-01-22 23:18
@aldeed since you've already been looking at this, it might make the most sense for you to take this and make a recommendation on the patterns we should use moving forward.

**Comment by machikoyasuda** [comment] 2018-01-24 16:31
https://github.com/reactioncommerce/reaction/issues/3477 w/ @Akarshit

**Comment by aldeed** [comment] 2018-02-06 02:58
@aaronjudd I spent a little time poking around various components, but I didn't find any smoking guns. It might be that someone more familiar with the slowness issues can do this better. However, since we are already planning component changes that will address some of this, and I will be trying to keep a better eye on reactivity issues and teaching others to do so, my vote is to close this issue in favor of more specific issues with reproductions, or focusing on a specific route, such as the linked #3477

**Comment by spencern** [comment] 2018-02-06 22:06
Closing, we'll create specific issues as we are able to surface specific issues with React or UI slowness.

**Closed by spencern** 2018-02-06 22:06 UTC
Labels: performance
