### ISSUE TITLE
Roles error: Can't mix grouped and non-grouped roles for same user

### ISSUE THREAD

**Issue by jujes** [reactioncommerce/reaction#1119] opened 2016-06-30 17:00 UTC
## image: reactioncommerce/prequel

Someone know why my container is exited: **Exited** (8) 6 minutes ago

### Actual Behavior

```
/var/www/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						      ^
Error: Roles error: Can't mix grouped and non-grouped roles for same user
    at Object._.extend._updateUserRoles (packages/alanning_roles/roles_common.js:687:1)
    at Object._.extend.setUserRoles (packages/alanning_roles/roles_common.js:174:1)
    at Object.createDefaultAdminUser (server/api/core/core.js:313:11)
    at Object.init (server/api/core/core.js:24:10)
    at module.export.exports.default (server/startup/init.js:8:12)
    at module.export.exports.default (server/startup/index.js:16:3)
    at server/main.js:13:22
    at /var/www/bundle/programs/server/boot.js:304:5
```

### Steps to Reproduce the Behavior

docker-compose:

```
mongo.reaction:
  restart: always
  image: mongo:latest
  command: mongod --smallfiles
  container_name: mongo.reaction

reaction:
  image: reactioncommerce/prequel
  links:
    - mongo.reaction
  container_name: reaction
  environment:
    - VIRTUAL_HOST=reaction.dev
    - ROOT_URL=http://reaction.dev
    - MONGO_URL=mongodb://mongo.reaction:27017/reaction
    - REACTION_EMAIL=admin@reaction.dev
    - REACTION_USER=admin
    - REACTION_AUTH=password
```

**docker logs reaction.dev**
```
16:52:35.788Z  INFO Reaction: Load default data from /private/data/
16:52:36.189Z  INFO Reaction: Modified 2 documents while importing 2 to Shops
16:52:36.273Z  INFO Reaction: JobServer started
16:52:36.276Z  INFO Reaction: Modified 1 document while importing 1 to Shipping
16:52:36.276Z  WARN Reaction: Skipped loading settings from reaction.json.
16:52:36.277Z  INFO Reaction: Modified 4 documents while importing 4 to Products
16:52:36.277Z  INFO Reaction: Modified 2 documents while importing 2 to Tags
16:52:36.278Z  INFO Reaction: Modified 9 documents while importing 9 to Translations
16:52:36.371Z  INFO Reaction: Initializing REACTION reaction-checkout
16:52:36.431Z  INFO Reaction: Initializing <blank site> reaction-checkout
16:52:36.464Z  INFO Reaction: Initializing REACTION reaction-dashboard
16:52:36.494Z  INFO Reaction: Initializing <blank site> reaction-dashboard
16:52:36.514Z  INFO Reaction: Initializing REACTION reaction-layout
16:52:36.526Z  INFO Reaction: Initializing <blank site> reaction-layout
16:52:36.628Z  INFO Reaction: Initializing REACTION reaction-orders
16:52:36.725Z  INFO Reaction: Initializing <blank site> reaction-orders
16:52:36.757Z  INFO Reaction: Initializing REACTION reaction-ui
16:52:36.778Z  INFO Reaction: Initializing <blank site> reaction-ui
16:52:36.804Z  INFO Reaction: Initializing REACTION reaction-analytics
16:52:36.819Z  INFO Reaction: Initializing <blank site> reaction-analytics
16:52:36.845Z  INFO Reaction: Initializing REACTION reaction-inventory
16:52:36.863Z  INFO Reaction: Initializing <blank site> reaction-inventory
16:52:36.892Z  INFO Reaction: Initializing REACTION reaction-paypal
16:52:36.912Z  INFO Reaction: Initializing <blank site> reaction-paypal
16:52:36.950Z  INFO Reaction: Initializing REACTION reaction-product-variant
16:52:36.977Z  INFO Reaction: Initializing <blank site> reaction-product-variant
16:52:37.002Z  INFO Reaction: Initializing REACTION reaction-shipping
16:52:37.018Z  INFO Reaction: Initializing <blank site> reaction-shipping
16:52:37.045Z  INFO Reaction: Initializing REACTION reaction-social
16:52:37.061Z  INFO Reaction: Initializing <blank site> reaction-social
16:52:37.087Z  INFO Reaction: Initializing REACTION reaction-stripe
16:52:37.101Z  INFO Reaction: Initializing <blank site> reaction-stripe
16:52:37.140Z  INFO Reaction: Initializing REACTION reaction-accounts
16:52:37.169Z  INFO Reaction: Initializing <blank site> reaction-accounts
16:52:37.191Z  INFO Reaction: Initializing REACTION reaction-catalog
16:52:37.202Z  INFO Reaction: Initializing <blank site> reaction-catalog
16:52:37.225Z  INFO Reaction: Initializing REACTION core
16:52:37.241Z  INFO Reaction: Initializing <blank site> core
16:52:37.259Z  INFO Reaction: Initializing REACTION reaction-email-templates
16:52:37.270Z  INFO Reaction: Initializing <blank site> reaction-email-templates
16:52:37.292Z  INFO Reaction: Initializing REACTION reaction-i18n
16:52:37.305Z  INFO Reaction: Initializing <blank site> reaction-i18n
16:52:37.327Z  INFO Reaction: Initializing REACTION reaction-router
16:52:37.338Z  INFO Reaction: Initializing <blank site> reaction-router
16:52:37.581Z  INFO Reaction: Starting createDefaultAdminUser
16:52:37.582Z  INFO Reaction: Modified 2 documents while importing 2 to Shops
16:52:37.585Z  INFO Reaction: Modified 14 documents while importing 14 to Translations
16:52:37.586Z  INFO Reaction: Modified 36 documents while importing 36 to Packages
16:52:37.622Z  INFO Reaction: Updating domain to reaction.dev
====== BEGIN MAIL #0 ======
(Mail not sent; to enable sending, set the MAIL_URL environment variable.)
MIME-Version: 1.0
Date: Thu, 30 Jun 2016 16:52:37 +0000
From: "Meteor Accounts" <no-reply@meteor.com>
To: admin@reaction.dev
Subject: How to verify email address on reaction.dev
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hello,

To verify your account email, simply click the link below.

http://reaction.dev/#/verify-email/7GYHYCX40TzgRBLmW4A843LgUV91R2MoXDitaSX0xmD

Thanks.

====== END MAIL #0 ======

/var/www/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						      ^
Error: Roles error: Can't mix grouped and non-grouped roles for same user
    at Object._.extend._updateUserRoles (packages/alanning_roles/roles_common.js:687:1)
    at Object._.extend.setUserRoles (packages/alanning_roles/roles_common.js:174:1)
    at Object.createDefaultAdminUser (server/api/core/core.js:313:11)
    at Object.init (server/api/core/core.js:24:10)
    at module.export.exports.default (server/startup/init.js:8:12)
    at module.export.exports.default (server/startup/index.js:16:3)
    at server/main.js:13:22
    at /var/www/bundle/programs/server/boot.js:304:5
```

**Comment by jshimko** [comment] 2016-07-06 04:56
Likely a duplicate of #960.  The issue seemed to arise when a new shop gets created and a then a query for that shop happens milliseconds later and returns null.  This is presumably because mongo doesn't return it when a query happens so close to the insert.  It also appears to be more common when the database is on another server (although sometimes happens on the same server, but different Docker container). 
That particular spot [should be fixed now](https://github.com/reactioncommerce/reaction/blob/development/server/api/core/core.js#L218-L221) on the development branch, but I'm working on a more general fix for the null shopId issue because there's clearly still a race condition happening.  I hope to have that sorted out asap.

Closing this in favor of the original issue.  Try the latest development branch and let me know if it still happens for you (but please respond over at #960)

**Closed by jshimko** 2016-07-06 04:56 UTC
