### ISSUE TITLE
Make Dashboard Icon List (Vertical ShortcutBar) show/hide based on needed permission

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#3091] opened 2017-10-12 16:25 UTC
### Expected behavior
Icons showing on the Vertical ShortcutBar should be based on if the logged-in user has required permission for that function e.g a user without `orders` role should not see the Orders shortcut icon. This is leading to clicking the icon and seeing a blank Order dashboard.

### Actual behavior
All the icons show up.

### Steps to reproduce the behavior
* Add a user to Shop Manager group. Check that the user can see all shortcutBar icons
* Toggle off the following permissions from the shop manager group: `Orders`, `Email`, `Tax`, `Shipping`
* Check that the user can still see all the shortcutBar icons

### Versions
Node: 7.10.0
NPM: 5.4.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.15.5
Reaction: 1.5.0
Reaction branch: master

**Comment by zenweasel** [comment] 2017-11-30 06:34
@impactmass Does this issue still have the same status? I feel like a lot of work has been done around the dashboard and permissions and I want to make sure we aren't on a wild goose chase if we start on this.

**Comment by impactmass** [comment] 2017-11-30 14:35
@zenweasel This actually came up while working on a project recently (in that specific case, it was the shipping panel that was available even when the logged in user wasn;t expected to have access to it).

We'll need to check our current master to see the how many of the dashboard icons and panels are still affected by this.

**Comment by Akarshit** [comment] 2018-01-17 15:44
The cause of the issue is that the `Shop Manager` has `admin` access. 
And [here](https://github.com/reactioncommerce/reaction/blob/master/server/publications/collections/packages.js#L21) we say that `admin` can see all the packages. So even if some permission is not given to the `Shop Manager`, he still has the `admin` permission and thus would be able to see everything.

In a discussion with @impactmass we came to the conclusion that it would be best to remove the `admin` access from the `Shop-Manager` group.

**Comment by Akarshit** [comment] 2018-01-22 16:29
Closing in favour of #3541

**Closed by Akarshit** 2018-01-22 16:29 UTC
Labels: bug, impact-major
