### ISSUE TITLE
Current "marketplace" code shows white screen

### ISSUE THREAD

**Issue by andrew-mikhailov-videal** [reactioncommerce/reaction#2849] opened 2017-09-13 21:32 UTC
On an fresh installation the system shows just an empty screen.
The HTML tree is rendered. No errors shown in the console. But nothing is rendered.

### Expected behavior
The usual installation shop should be shown.

### Actual Behavior
The white screen is shown.

### Steps to Reproduce the Behavior
1. Download the latest code from the "marketplace" branch.
2. Install everything.
3. Navigate to the site.

### Versions
1.5.0

**Comment by zenweasel** [comment] 2017-09-13 22:10
@andrew-mikhailov-videal I just tested this again from a fresh install and everything appears to be working fine for me. Can you test it again from a fresh install to verify?

**Comment by zenweasel** [comment] 2017-09-15 22:50
I can't reproduce this error. Closing. Please feel free to reopen if you have any additional information.

**Comment by zenweasel** [comment] 2017-09-15 22:52
Actually closing.

**Closed by zenweasel** 2017-09-15 22:52 UTC
Labels: cannot-reproduce
