### ISSUE TITLE
Label requirement unsatisfied with 1st label being archived on creation

### ISSUE THREAD

**Issue by janat08** [reactioncommerce/reaction#2689] opened 2017-08-16 19:29 UTC
### Expected behavior
first label unfilled and archived, 2nd created and filled, publish available

### Actual Behavior
publish produces error

### Steps to Reproduce the Behavior
Login as admin
Create a product
Leave the label for an option blank
Make another label
Archive first label
You can't publish despite having valid item

### Versions
Node: 6.11.2
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.1
Reaction branch: master

**Comment by zenweasel** [comment] 2017-08-22 00:26
@janat08 We really need these issues to have complete descriptions and reproduction steps. Also, how does this ticket differ from #2274?

**Comment by janat08** [comment] 2017-08-22 05:32
It appeared to work when you just first create item, and then proceed to archive first label, and try use 2nd one.

**Comment by zenweasel** [comment] 2017-08-22 06:45
I don't want to be pedantic but we really need step by step reproduction steps. These would look something like.

1. Login as admin
1. Create a product
1. Leave the label for an option blank
1. Another step you took
1. Observe `<some behavior that you think is wrong>`

If you want to see examples you can see any of the tickets I have created for bugs.

Also if you could explain how this differs from issue #2274? Thanks.

**Comment by janat08** [comment] 2017-08-22 12:30
Archived first label prevents from publishing item.

**Comment by kieckhafer** [comment] 2017-09-29 23:40
I think #2893 fixes this, but I don't 100% understand the issue, so @zenweasel if you could take a look and see, and close if it does, that'd be great!

**Comment by zenweasel** [comment] 2018-01-03 03:38
Cannot reproduce with current version, closing

**Closed by zenweasel** 2018-01-03 03:38 UTC
