### ISSUE TITLE
Error when inviting new marketplace seller on localhost

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#3747] opened 2018-02-14 12:36 UTC
### Expected behavior

1. Invite new seller by email from the shops tab on the right.
2. They open in email and accept
3. They set password on prompt
4. Goes to profile

### Actual behavior

4. Blank reaction page
5. Try to login as newly registered user and receive the following console log:

`TypeError: Cannot read property 'name' of undefined at TagNav.renderShopSelect (app.js:108464) at TagNav.render (app.js:108503) at modules.js:141552 at measureLifeCyclePerf (modules.js:140832) at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (modules.js:141551) at ReactCompositeComponentWrapper._renderValidatedComponent (modules.js:141578) at ReactCompositeComponentWrapper.performInitialMount (modules.js:141118) at ReactCompositeComponentWrapper.mountComponent (modules.js:141014) at Object.mountComponent (modules.js:133869) at ReactDOMComponent.mountChildren (modules.js:140140)`

### Steps to reproduce the behavior

Described above. Note: only tested on localhost.

### Versions

1.7.0

**Comment by zenweasel** [comment] 2018-02-14 13:18
Duplicate of https://github.com/reactioncommerce/reaction/issues/3652. Fixed in `release-1.8.0`.

**Closed by zenweasel** 2018-02-14 13:18 UTC
