### ISSUE TITLE
Add "cancel order" option

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1238] opened 2016-08-03 01:08 UTC
As an order admin I would like the option to choose "cancel order" and have the authorization or capture cancelled (or refunded depending on status) and the stock released.

**Comment by andela-akolawole** [comment] 2017-03-15 11:11
I understand the issue, and I am on the verge of fixing it. 
### Scenarios 
If a payment method supports cancelling a transaction then
- An order can be cancelled after an authorised method has been called, the admin should be able to cancel the transaction before capturing a payment.
- If the payment has been captured, then a refund method would be called to refund the money to the buyer.

If a payment provider does not support a transaction then.
- An error message should be sent to the admin, stating that the method does not support cancelling a transaction.

**Comment by andela-akolawole** [comment] 2017-03-21 20:33
After looking at payment providers that are already available on reaction, I noticed only stripe supported cancelling a payment in between an authorise and capture method. The next step would be direct the admin to a refund page if the order is cancelled after the payment has been captured or the payment of the order hasn't been captured.

**Comment by andela-akolawole** [comment] 2017-03-22 11:18
@rymorgan would be making changes to the design for the cancel order issue.

**Comment by mikemurray** [comment] 2017-03-28 20:59
The popover component might be useful: https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/ui/client/components/popover/popover.js#L73

**Comment by rymorgan** [comment] 2017-03-28 22:16
Note: the multifunction button should only show before approval, after that they will have to use the refund field which shows up after approval/capture. 
If specific payment providers don’t allow for canceling a payment then don’t show the multifunction button. 

**Remove canceled from card and header.** 
![cart_completed](https://cloud.githubusercontent.com/assets/20409254/24429672/e5ff01f0-13c7-11e7-8a18-e86bbd48a4b4.png)

**Button changes.** 

- Make type in dropdown bolder
- Remove refund
- Add rollover effect. (#f5f5f5 bg like with lists) 

![cart_completed-type](https://cloud.githubusercontent.com/assets/20409254/24429695/02520dc0-13c8-11e7-96d7-71343b20d4f8.png)


The button should only show one option for now. When you are on approve you can toggle to cancel. When the cancel button shows, you can toggle to approve and when you are in approve, you can toggle to cancel. 

![multi-function button](https://cloud.githubusercontent.com/assets/20409254/24429922/04c82fac-13c9-11e7-9d33-740974baab52.png)

Rollover effect on button should show the face on the border as well as the button fill. 

![cancel order - rollover effect](https://cloud.githubusercontent.com/assets/20409254/24429950/2589bf26-13c9-11e7-9918-46de26822037.png)

**Modal changes changes**
Add x to close out popover 
Change copy 

Title
Do you want to cancel this order? 

Subtitle
This will refund the order total of $ordertotal

Button left
Yes, but no restocking

Button right
Yes, and restock 

Make buttons standard button color. 

![cancel_order_popover](https://cloud.githubusercontent.com/assets/20409254/24430036/9138c2bc-13c9-11e7-82e8-05927edd8d01.png)

**Comment by rymorgan** [comment] 2017-04-03 21:18
See notes below. 

![invoice-refund-button](https://cloud.githubusercontent.com/assets/20409254/24632225/3ecd6dd0-1878-11e7-8265-c4a6c0db9fc6.png)
![popover edits](https://cloud.githubusercontent.com/assets/20409254/24632227/3ecf1324-1878-11e7-83da-d0687ccac9df.png)
![button](https://cloud.githubusercontent.com/assets/20409254/24632226/3ece46f6-1878-11e7-9103-ae29c650001f.png)

**After approval:** 

![cancel button for refund](https://cloud.githubusercontent.com/assets/20409254/24632239/464a36ec-1878-11e7-8ca5-c604614d2004.png)

After capture it should look like the following mockup. 
![refund](https://cloud.githubusercontent.com/assets/20409254/24632285/6c00ffba-1878-11e7-8066-9909b5331d64.png)

**Comment by michael-alade** [comment] 2017-04-13 09:30
The paypal express payment provider seems to fail due to the unavailability of the transaction ID gotten when a capture has been done.

*Fix*
Add flags to all payment provider to check if they support
- [ ] Authorize
- [ ] De-authorize
- [ ] Capture
- [ ] Refund

**Comment by michael-alade** [comment] 2017-04-19 09:06
I have created the flags for the payment providers and refunds are working properly now. I just have to fix failing test.

**Comment by michael-alade** [comment] 2017-04-22 00:48
The test are fixed and the PR #2022 is ready to be reviewed again.

**Comment by michael-alade** [comment] 2017-04-26 12:03
The issue is closed by #2022 PR

**Closed by michael-alade** 2017-04-26 12:03 UTC
Labels: enhancement, orders
