### ISSUE TITLE
Convert variant options card on PDP to react. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2851] opened 2017-09-13 22:59 UTC
Convert variant options card on PDP to react.

**Comment by aaronjudd** [comment] 2017-09-18 22:33
@kieckhafer This seems to be a duplicate of #1905, which got closed in favor of #1647. #1647 doesn't quite cover this and is an epic with a few remaining items that need to be resolved.

**Comment by kieckhafer** [comment] 2017-09-19 04:39
Yes, seems to be a duplicate of part of that ticket. I'm working on this now, as it will be a huge help to a client project. Have a (currently WIP) PR #2893 which I hope to close out in the next 24 hours. 
Doesn't matter to me how we track, close whichever ticket you'd like, or we can keep them open until 2893 is pulled in.

**Comment by spencern** [comment] 2017-09-30 00:56
Resolved by #2893

**Closed by spencern** 2017-09-30 00:56 UTC
Labels: UIX
