### ISSUE TITLE
Can't add to cart as an anonymous user

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4573] opened 2018-08-23 23:58 UTC
## Issue Description
When attempting to add to cart as an anonymous user, it appears to add to cart but when you go to checkout it says "looks like your cart is empty"

![cant_add_to_cart](https://user-images.githubusercontent.com/72819/44557841-3c53c280-a773-11e8-9bd0-4a8770efdfa2.gif)

## Steps to Reproduce
1. Fully reset Reaction
1. Don't log in
1. Visit the site in an incognito window
1. Add an item to cart
1. Click on "Checkout"
1. Observe that your cart is still empty

### Versions
Reaction: `release-1.15.0`

**Comment by zenweasel** [comment] 2018-08-24 00:01
It looks like every time I add something to cart, a new cart is being created, but the app cannot find it.

**Comment by zenweasel** [comment] 2018-08-24 00:03
If I log in and out, that seems to make it work.

**Comment by spencern** [comment] 2018-08-24 02:04
Maybe related? https://github.com/reactioncommerce/reaction/issues/4570

**Comment by spencern** [comment] 2018-08-24 05:08
Removing the `Release Blocker` issue as we've determined that this is not a regression.

**Comment by spencern** [comment] 2018-08-24 05:10
Added `needs-to-be-reproduced` mostly because we need to get a more readily reproducible set of steps. This is reproducible for certain people, and we've seen at least 3 reports. It's not readily reproducible for everyone with the steps provided.

**Comment by willmoss1000** [comment] 2018-09-04 16:19
Spent a while trying to understand how to reproduce this. The only way I **cannot** reproduce this error is by opening in a new incognito tab. 

Steps:
- Clone 1.4.1
- Login as admin & create a new product
- Hit add to cart as admin & click on your cart to see that it has worked
- Log out whilst still on the product page and click add to cart -> get the empty cart warning

Potentially related -> when I hit "go back" to go the previous page in the browser the "Sign In" button disappears until the page is refreshed.

**Comment by willmoss1000** [comment] 2018-09-05 10:43
Further findings:
- I found that some of the `carts` within `store` did not have an `_id` ; just a`token` and `shopId`
- By changing my `storageKey` in `anonymousCarts.js` to a new value the issue is no longer present

**Comment by aldeed** [comment] 2018-11-19 23:08
Believed to be fixed in latest 2.0 RCs

**Closed by aldeed** 2018-11-19 23:08 UTC
Labels: bug, impact-critical, needs-to-be-reproduced
