### ISSUE TITLE
Untranslated text shows up in Account manager

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4530] opened 2018-08-09 06:16 UTC
## Issue Description
When making changes to an account, when successful the message shows up as
`admin.groups.addUserSuccess` rather than the user text string

## Steps to Reproduce
1. Login as admin
1. Add an account
1. Observe the toast displays `admin.groups.addUserSuccess`

### Versions
reaction 1.14.0

**Comment by nadaa** [comment] 2018-08-16 09:44
Hi, 
I am new here, I would like to start with this issue, is it ok?
Thanks

**Comment by Akarshit** [comment] 2018-08-16 09:47
@nadaa Sure, please go ahead.

**Comment by nadaa** [comment] 2018-08-16 10:37
@Akarshit , Thanks. I will.

**Comment by nadaa** [comment] 2018-08-16 14:57
Hi,
I tried to reproduce the bug. I have a problem with setting the email when I changed the email provider, I get an error!. 
I am working in windows 7

**Comment by nadaa** [comment] 2018-08-17 04:40
Thanks @spencern ,  I will recheck the problem, if it still exists, I will open a new detailed issue. For this bug I will send a pull request now.

**Comment by aguscha333** [comment] 2018-11-20 21:36
still open?

**Comment by spencern** [comment] 2018-11-20 23:42
@aguscha333 I believe it is, thanks!

**Comment by mpaktiti** [comment] 2019-07-09 07:24
@zenweasel I have some trouble reproducing this, but I do see some other errors. 

This is what I see when I log as `admin@localhost`. 
When I click the `admin.dashboard.manageGroups` the menu on the right pops up. 

![image](https://user-images.githubusercontent.com/11715799/60867363-55524e80-a233-11e9-9075-02ee5a047c31.png)

If I fill the info and click "Add Admin User" the "Invitation Sent" toast is displayed. 

However, if I fill in the info of a user I already have invited, I get this:

![image](https://user-images.githubusercontent.com/11715799/60867438-85015680-a233-11e9-81e0-25f7baa47627.png)


Is it normal that I can only add Admin accounts? Is this issue obsolete?
Should I open a new issue for the other missing translations?

**Comment by zenweasel** [comment] 2019-07-09 22:15
@mpaktiti what you are showing me in the screenshot is untranslated text so I am confused when you say you are not able to reproduce it. What you are seeing there are the translation keys rather than the actual text that's supposed to be displayed to the consumer.

**Comment by mpaktiti** [comment] 2019-07-10 08:44
@zenweasel I'm not saying there is no issue, but that I cannot reproduce the initial scenario but found another one instead (when you re-invite someone, rather than adding a user). 

I'll assume the initially reported issue is obsolete now, and I'll go ahead fixing the re-invite one, using this github issue.

**Comment by zenweasel** [comment] 2019-07-11 02:39
Okay, reread this again and now understand. I think we could expand this to include any untranslated text in the Accounts UI you find. I think what I noted was just one example.

**Comment by mpaktiti** [comment] 2019-07-15 09:21
@zenweasel The issue has been resolved. I just retested to resume troubleshooting and I can see the translations correctly. I'm closing it.

![image](https://user-images.githubusercontent.com/11715799/61206300-e8d7c380-a6fa-11e9-98c1-fc78264e563b.png)

![image](https://user-images.githubusercontent.com/11715799/61206365-0c027300-a6fb-11e9-9e91-666b4ed49dec.png)

**Closed by mpaktiti** 2019-07-15 09:21 UTC
Labels: Hacktoberfest, bug, good first issue, impact-minor
