### ISSUE TITLE
Support multiple products/tags with same title/name

### ISSUE THREAD

**Issue by katiebvogel** [reactioncommerce/reaction#1873] opened 2017-02-21 19:40 UTC
We need to be able to import and display multiple products with the same title.
We also need to be able to import and display multiple tags with the same name.

**Comment by aaronjudd** [comment] 2017-02-28 20:53
to recap offline conversation about this, the imports accept a "key" parameter. The product itself is fine with duplicated title, but the import should not use "title" alone in the key in this case.

**Comment by aaronjudd** [comment] 2017-04-25 23:19
This is a duplicate of #2061

**Closed by aaronjudd** 2017-04-25 23:19 UTC
Labels: in progress
