### ISSUE TITLE
Issue with gridfs killing nodes

### ISSUE THREAD

**Issue by callmephilip** [reactioncommerce/reaction#2071] opened 2017-04-01 20:23 UTC
As we are uploading and processing images in bulk, some of the nodes get killed every once in a while due to what looks like an issue with the gridfs adapter:

```
/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:98 process.nextTick(function() { throw err; });
MongoError: no chunks found for file, possibly corrupt at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb-core/lib/error.js:31:11)
/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:825:29
/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:1201:5 at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/collection.js:1401:5
at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/cursor.js:675:5
at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb-core/lib/cursor.js:172:5)
at setCursorNotified (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb-core/lib/cursor.js:517:3)
at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb-core/lib/cursor.js:590:16
at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb-core/lib/cursor.js:233:18)
at /app/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb-core/lib/connection/pool.js:436:18
at nextTickCallbackWith0Args (node.js:489:9)
at process._tickDomainCallback (node.js:459:13)
```
I am wondering if there's a way to wrap a try catch around parts of this to prevent nodes from being killed completely or something along these lines

**Comment by aaronjudd** [comment] 2017-04-04 20:54
Can you give steps to reproduce?   10, 25, 50,images? Production bundle, or local dev? etc..

**Comment by spencern** [comment] 2017-04-05 18:28
From the chat on 04/05/2017

> Carlos Olivera Terrazas @carlos-olivera 10:22
Hi! I had a very high CPU peaks with product photos stored in Fs.Collection and GridFS, (by default in reactioncommerce), I had to move to filesystem and the problem was gone, someone with similar experience?

> Lorenzo Campanis @lcampanis 10:59
This is interesting, as we are working on exactly the same problem at the moment. Server crashes when photos are uploaded fast. We do have a few custom implementations of image processing on top, but managed to crash RC's v1.0 as well. Is there something you can share as we were just discussing moving towards https://github.com/vsivsi/meteor-file-collection. Any input would be appreciated

> Spencer Norman @spencern 11:00
How many photos are you uploading at a time when this is happening?

> Lorenzo Campanis @lcampanis 11:01
we only allow 1 upload at a time per user, we multiplied this by a few concurrent users and down it went..
problem is with collectionFS not RC

> Spencer Norman @spencern 11:02
Multiple instances of the app or a single instance?

> Lorenzo Campanis @lcampanis 11:03
single instance of the app. It seems that collectionFS is sleeping on fixes for quite a long time. So new modules for storing files have come out which solve the problem with readstream locking

> Spencer Norman @spencern 11:09
hmm, so does it look like using a forked version of collectionFS with fixes pulled in solves this?

> Lorenzo Campanis @lcampanis 11:12
vsivsi isn't exactly a fork, is this what you mean? What GridFS isn't implementing is a lock on read/write, everything else is fine. So uploading or downloading is inevitably crushing the container

> Spencer Norman @spencern 11:15
yeah, that’s what I was asking about. So CPU spikes on upload and too many concurrent crashes container because of GridFS readstream lock?

> Lorenzo Campanis @lcampanis 11:22 
it will crush in various ways but they all lead to GridFS not handling either its deletes from _tempstore correctly, the one you sent or a band new one we just got now
```bash
-----------FINISH STREAM _tempstore
---SA REMOVE
/opt/reaction/dist/bundle/programs/server/node_modules/fibers/future.js:280
                        throw(ex);
                        ^

TypeError: Cannot read property 'keys' of undefined
    at packages/cfs_tempstore.js:326:63
    at runWithEnvironment (packages/meteor.js:1176:24)
```

> Lorenzo Campanis @lcampanis 11:25
No probs.. We investigated and hacked GridFS and tempstore but found no way for GridFS to handle concurrent uploads correctly. It will pass 1/10 times
And after reading everything we could find and attempting to work it directly from collectionFS with a custom implementation, the outcome is simply that GridFS is unable to handle concurrent uploads correctly

>Aaron Judd @aaronjudd 11:28
we were testing the S3 plugin, I’m wondering if you only used S3 and not GridFS, does collectionFS still do the chunking/uploads -> I’m assuming that’s not the case, that’d it’d alleviate the GridGS issue (while still writing metadata to the Media collection)

**Comment by aaronjudd** [comment] 2017-04-05 19:27
In @lcampanis case it's crashing on multiple uploads from multiple users (correct?). @callmephilip is this also how you are experiencing the issue?

**Comment by lcampanis** [comment] 2017-04-05 19:35
@aaronjudd It can happen with multiple uploads from one user as well, all you need two concurrent uploads to get it.

**Comment by lcampanis** [comment] 2017-04-06 09:37
@aaronjudd In addition to my email, we are attempting to fix CFS one last time, until we see what the outcome from RC is. 

Clearly CFS isn't supported anymore. So based on the following tickets we will be trying to bring in https://github.com/vsivsi/gridfs-locking-stream. 
It has been attempted before in GridFS https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/gridfs/gridfs.server.js#L5, but probably abandoned. We got far enough though, so we'll keep trying to make it work. 
See the related lock-stream ticket from back in history https://github.com/CollectionFS/Meteor-CollectionFS/issues/236. Applying a lock will most probably work as expected.

Let us know your thoughts. Thanks!

**Comment by lcampanis** [comment] 2017-04-07 17:26
@callmephilip see if this does the job for you as it seems it solved it for us.
https://github.com/reactioncommerce/reaction/pull/2096
Any questions you have, @prosf and I are happy to help.

@aaronjudd We will continue our talks with @spencern on new solutions, but please go ahead and test this solution as much as possible. A new one will surely take us all a while to implement. 
Have a good weekend ;)

**Comment by aaronjudd** [comment] 2017-04-07 18:14
@lcampanis nice, testing now.  We will continue the replacement/fix discussion for CFS in #1221

**Comment by spencern** [comment] 2017-04-10 18:36
I was able to get reproduce a similar error - but haven't been able to get the exact error to show up.

My reproduction is as follows

1. Create an off-machine MongoDB instance
2. Run reaction and set off-machine MONGO_URL - `MONGO_URL="mongodb://..." reaction run`
3. Upload multiple images in at least 3 windows to separate products. I used files ranging in size from 4MB to 10MB.

This caused the server to crash with the following error.

Stack Trace
```
/Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^
MongoError: file with id 58ebcf0c911fbe31fffa175e not opened for writing
    at Function.MongoError.create (/Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
    at handleCallback (/Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb/lib/collection.js:1401:5
    at handleCallback (/Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb/lib/cursor.js:675:5
    at handleCallback (/Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb-core/lib/cursor.js:172:5)
    at setCursorNotified (/Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb-core/lib/cursor.js:517:3)
    at /Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb-core/lib/cursor.js:590:16
    at queryCallback (/Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb-core/lib/cursor.js:233:18)
    at /Users/sn/dev/reaction/.meteor/local/isopacks/cfs_gridfs/npm/node_modules/mongodb-core/lib/connection/pool.js:436:18
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
=> Exited with code: 1
```

**Comment by lcampanis** [comment] 2017-04-10 19:03
@spencern I suppose that's on an instance including the cfs fixes in the PR? Most probably missed  a try/catch somewhere, but this error rings bells for locking. We'll get some time next week to test gridfs-locking-stream as we've managed to integrate it correctly in gridfs, just needs more testing after we launch..

**Comment by spencern** [comment] 2017-04-10 19:12
@lcampanis
I was unclear here.
This error was on the `development` branch and was more of a confirmation that there are issues with concurrent file uploads, as well as listing a new error message that was not identical, but seemingly related.

**Comment by aaronjudd** [comment] 2018-01-23 16:32
Closing as we work on related performance / updates to CFS @aldeed

**Closed by aaronjudd** 2018-01-23 16:32 UTC
Labels: performance, verified-reproducible
