### ISSUE TITLE
Custom payment methods template configuration issue

### ISSUE THREAD

**Issue by srikanthkolli** [reactioncommerce/reaction#4893] opened 2019-01-02 12:18 UTC
## Issue Description
Custom payment method templates require the change in core files to make payment visible in the checkout screen .
## Steps to Reproduce
Please refer to this line https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/payments/client/checkout/payment/methods.js#L11
when i create new plugin for payment method i need to change this file to include its template name, then only i can see the payment option in the checkout page.
## Possible Solution
Can we change the flow of this template rendering in the checkout. Even though i can build a custom plugin i still need to make change in core to make it work. This kills the true plugin concept.

### Versions
RC v2

**Comment by janus-reith** [comment] 2019-01-03 15:47
This is a duplicate of [#4841](https://github.com/reactioncommerce/reaction/issues/4841).
I think @aldeed is currently [restructuring this again](https://github.com/reactioncommerce/reaction/issues/4860#issuecomment-447991681), not sure if there will be a fix for the current concept.

**Comment by aldeed** [comment] 2019-01-09 18:52
- That's the old UI, which is no longer supported in 2.0 and will be removed sometime in the next few months.
- The new UI is https://github.com/reactioncommerce/reaction-next-starterkit
- In the new UI it's still hard-coded, but that won't change. The new UI is intended as a starting point to fork and modify, and updating the payment methods config is one change we expect everyone will make. There is no plugin system for the new UI.
- I'll be merging changes to the NextJS starterkit `develop` branch later this week, which make it much simpler to swap out payment method components (but still a code change).

**Closed by aldeed** 2019-01-09 18:52 UTC
