### ISSUE TITLE
Translation for Default Payment Method dropdown missing

### ISSUE THREAD

**Issue by sophiehe** [reactioncommerce/reaction#3717] opened 2018-02-09 18:45 UTC
### Expected behavior
Dropdown should translate from app.auto to designated message.

### Actual behavior
![image](https://user-images.githubusercontent.com/20484811/36044041-3069084a-0d86-11e8-9144-b293844f6814.png)

### Steps to reproduce the behavior
1. Click on 'Payment'
2. See 'app.auto' in the dropdown 

### Versions
Node: 6.5.0
NPM: 3.10.3
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.19.0
Reaction: 1.8.0
Reaction branch: release-1.8.0

**Comment by prinzdezibel** [comment] 2018-02-12 18:30
This is most probably a duplicate of: #3694

**Comment by aldeed** [comment] 2018-09-28 21:01
Closing as assumed fixed by https://github.com/reactioncommerce/reaction/pull/3724

**Closed by aldeed** 2018-09-28 21:01 UTC
Labels: bug, i18n + l10n, impact-minor
