### ISSUE TITLE
Cannot update order status

### ISSUE THREAD

**Issue by vwadher** [reactioncommerce/reaction#4621] opened 2018-09-12 18:32 UTC
## Issue Description
Cannot update order status or capture.

![image](https://user-images.githubusercontent.com/35978747/45445263-982caf80-b67e-11e8-8ee9-827d8307e2d8.png)

## Steps to Reproduce
Running v1.16, as an admin, on the orders section when I try to update an order status (or capture), I get an error message on the bottom left corner with a "Match Failed [400]" 

1. Log in as an admin 
2. Navigate to "orders" 
3. Select an order using the checkbox on the customer name.
4. Click "Bulk actions" and update the status to anything.  Or capture.  
5. Note that the order did not get updated and there was an error message on the bottom left. 

### Versions
1.16

**Comment by jeffcorpuz** [comment] 2018-09-12 20:48
Hi @vwadher,
 
Thanks so much for the bug report and reproduction steps, it's clear you have put time into helping us resolve this issue and we appreciate that.

We are investigating said issue and will keep you posted.

**Comment by zenweasel** [comment] 2018-09-13 04:00
Assigning to @Akarshit as this looks like an incompatibility between the current code and the data-loader

**Comment by Akarshit** [comment] 2018-09-17 08:52
Yes this was a issue with data-loader.
I fixed that in this PR reactioncommerce/reaction-data-loader#7

**Closed** 2019-04-25 10:03 UTC
Labels: bug
