### ISSUE TITLE
Product Grid tag views are sometimes inconsistent

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2213] opened 2017-05-04 20:52 UTC
### Expected behavior

When viewing a product grid filtered by a `tag`, there will sometimes be products visible in that tag that don't belong.

### Actual Behavior

Sometimes products show up on tag pages that should not be there

### Steps to Reproduce the Behavior

With a fresh install
1. Add a new product ( add title, update variants, etc)
2. Publish
3. Edit product and add a new tag
4. Add tag to navbar
5. observe that on shop / <your tag> ( there are products that don't belong )

This doesn't always happen, and with some fiddling, you can fix it by juggling tags on products that are showing up incorrectly.

### Versions

Node: 7.2.0
NPM: 4.0.5
Docker: 17.03.1-ce
Reaction CLI: 0.8.0
Reaction: 1.1.1
Reaction Branch: master

**Comment by Stat1c14** [comment] 2017-05-04 22:32
I've had this issue as well. Adding more tags/changing tags seems to make more random products appear.

**Comment by abdulsemiu-atanda** [comment] 2017-05-24 10:12
This Issue seems to be fixed by Reaction Commerce latest release (release 1.2.0) but should be reopened if it reoccurs
http://g.recordit.co/gsu8rFVjka.gif

**Comment by vigyano** [comment] 2017-06-16 07:55
Need to reopen this bug. I found this bugs occurs in 1.2.0. Products with unpublished changes appears in all tags. Once it is published that product disappear and shows in appropriate tags.

**Comment by vigyano** [comment] 2017-06-16 09:37
I am able to reproduce this bug using reaction-example-plugin)
Note: 
- The issue is not in reaction-example-plugin but is in reaction itself.
- Also, this occurs only when a user is logged in

1) Setup reaction-example-plugin(https://github.com/reactioncommerce/reaction-example-plugin.git) in reaction
2) Login as Admin
2) Click TODDLER tag which should display only "Baby Yoga Outfit"
3) Goto NEWBORN tag and change any field in ONESIE product (just click any fields and click anywhere else, no need to even change data). **DO NOT PUBLISH THE CHANGE**
4) That product will be listed in TODDLER tag as "Sold Out"

![image](https://user-images.githubusercontent.com/12378687/27221227-aa4a53b8-523c-11e7-8063-af8cf8d20667.png)

**Comment by aaronjudd** [comment] 2017-06-20 00:43
@abdulsemiu-atanda can you re-examine this? If not reproducible, include version information so we know...

**Comment by abdulsemiu-atanda** [comment] 2017-06-20 19:14
I've been able to reproduce this behavior with the steps provided by @vigyano and I'll look into resolving it

**Comment by zenweasel** [comment] 2017-06-20 23:51
@abdulsemiu-atanda Have we verified that this is still happening in the rewritten product grid? If it is, let's assign this to @kieha

**Comment by abdulsemiu-atanda** [comment] 2017-06-21 14:35
It seems partially fixed in `product grid` as it displays products that have selected tag other than `Shop` tag where all unpublished products gets displayed alongside products that have the `Shop` tag

**Comment by kieha** [comment] 2017-06-30 02:39
Update:
- In the rewritten product grid, only unpublished products show up under the `Shop` and any other tags available. On publishing, they don't show up unless they have the tag themselves.

**Comment by zenweasel** [comment] 2017-07-07 00:12
@kieha So it seems like that was the original issue, that products were showing up under the wrong tag when they are unpublished?

**Comment by aaronjudd** [comment] 2017-07-19 23:47
@awadesmoline any update or progress on this issue? should we unassign?

**Comment by awadesmoline** [comment] 2017-07-20 10:10
@aaronjudd sorry I should have updated this issue instead of the PR (#2534) I raised.

**Update**

I figured this is caused by the before hook on Products in Revisions [here](https://github.com/reactioncommerce/reaction/blob/development/imports/plugins/core/revisions/server/hooks.js#L602-L603). Because of this, we can't add a tag to a product in the database (which means the product will not display under any specific tag) when it's unpublished, unless we remove this restriction on updating unpublished products.

Yeah, please you can unassign as I am working on some other issues currently.

**Comment by zenweasel** [comment] 2017-08-04 01:37
The issue here is that when Revision control is on we are building a new selector and that selector is grabbing all products, even ones without the correct tag. Probably some sort of `$and/$or` mixup

**Comment by zenweasel** [comment] 2017-08-04 23:17
Closed via #2639

**Closed by zenweasel** 2017-08-04 23:17 UTC
Labels: bug, critical impact, verified-reproducible
