### ISSUE TITLE
Issue with the ReactionImport class

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#646] opened 2016-01-05 20:55 UTC
Hi,

I am testing the new version with multiple shops added, this worked correctly in the previous version but now the packages are multiplied but no to the correct shop. The main ReactionCore.getShopId() will be added to every registered entry in the Packages collection instead of each shop's id therefore one package will be registered several times with the same id causing multiple items in the user dropdown and other issues like this.
Let me know if I can help with a PR, I am debugging the issue too and trying to find a solution.
So far I know that the `ReactionRegistry.loadPackages` function runs correctly through every shop and the  `ReactionImport.package({
          name: pkgName,
          icon: config.icon,
          enabled: !!config.autoEnable,
          settings: config.settings,
          registry: config.registry,
          layout: config.layout
        }, shopId);` function is called with the correct shopId so not sure yet where thing go wrong.

**Comment by aaronjudd** [comment] 2016-01-05 20:59
a PR would be appreciated.  It'd also be great if you could give us an overview on how you implemented  the multiple shops for https://github.com/reactioncommerce/reaction/issues/357.  I'd like to get some tests going so we don't keep breaking your implementation, and also see how closely your strategy aligns to what we were planning.  There's quite a few people interested ;-)

**Comment by tdecaluwe** [comment] 2016-01-05 23:29
@boboci9 Do you have some json import files to test with? Or a walkthrough to reproduce the problem?

**Comment by boboci9** [comment] 2016-01-06 10:04
Hi, All you need to do is add a new entry in the Shops collection, in this case you should have in the DB packages registered with the new shopId but all the registry entries are for the same shopId.

**Comment by boboci9** [comment] 2016-01-06 15:00
@aaronjudd I will go over the changes you added to #357, we have previously discussed some details regarding what you have been planning and I kept our implementations to those.

**Comment by boboci9** [comment] 2016-01-06 15:17
Finally found the issue, it is not coming from the ReactionImport class, it is coming from the reaction-schemas package, Packages schema. The autovalue is set to the main shopId so no mater what shopId you send it will be ignored.
```
 "shopId": {
    type: String,
    index: 1,
    autoValue: ReactionCore.shopIdAutoValue,
    label: "PackageConfig ShopId",
    optional: true
  },
```
I commented out the autovalue and the packages are registered correctly but I didn't send a PR with this as I am not sure what you would like to have instead.

**Comment by boboci9** [comment] 2016-01-06 18:45
Same issue happens when a seller tries to add a new product, the product is inserted to the right shop and then automatically moved to the main shopId when you try to edit it. The products collection has the autoValue set the same way and when I comment it out I can edit the product without switching it to the main shop.

**Comment by stabenfeldt** [comment] 2016-01-08 06:04
> I am testing the new version with multiple shops added

Is the multi tendant marketplace feature completed? I thought I saw it listed on the roadmap page. Great news if it's done! :-) Is it production ready?

**Comment by aaronjudd** [comment] 2016-01-08 07:38
@boboci9 

```
  shopIdAutoValue: function () {
    // we should always have a shopId
    if (ReactionCore.getShopId()) {
      if (this.isSet && Meteor.isServer) {
        return this.value;
      } else if (Meteor.isServer || Meteor.isClient && this.isInsert) {
        return ReactionCore.getShopId();
      }
      return this.unset();
    }
  },
```
I think this is (by design), preventing shop inserts from the **client**.   However, it looks like it should allow you to set provide a shopId and insert server side.  (or with the `shop/createShop` method). I need to dig in a little more I guess and see what if that's not working on the server side.

 to test, maybe:
```
if (this.isSet) {
 return this.value;
```

But I'm not sure about the ramifications.

**Comment by aaronjudd** [comment] 2016-01-08 07:46
@stabenfeldt it's still a work in progress.  Mostly the work remaining is UI / management related. You could make modifications right now to use as a marketplace (single tenant, multiple shops), and we keep moving towards providing that feature in the future. We do try to keep the schema and collections designed for these use cases though

**Comment by boboci9** [comment] 2016-01-08 07:47
@aaronjudd I will add your suggestion in my version and start testing it out so I can help you out with any unexpected ramification.
Regarding my overview on the multiple shops I am discussing them on gitter so we can have a real conversation about them.

**Comment by boboci9** [comment] 2016-01-08 10:45
@aaronjudd: The issue with this will be for example for the Products collection you are calling the products/updateProductField from the client. When this is done by a certain seller in his own shop the shopId will jump back to the main shopId instead of staying holding the seller's shopId as created through the insert.

**Comment by boboci9** [comment] 2016-01-08 19:38
@aaronjudd Also when an order is viewed by a seller of a separate shop the order's shopId will jump to the mainShopId instead of keeping the value it has been created with because the move to next workflow step is called from the client side.

**Comment by woakes070048** [comment] 2016-03-30 15:58
@aaronjudd what is the state of this?

**Comment by aaronjudd** [comment] 2016-03-30 16:13
@woakes070048 I'm not sure if this is an issue any more, needs testing.

**Comment by woakes070048** [comment] 2016-03-30 16:39
@aaronjudd i guess i will install it and do some testing. i was reading somewhere and it mentioned that it was private and called reaction-drive

**Closed** 2017-02-15 00:44 UTC
Labels: marketplace, needs-to-be-reproduced
