### ISSUE TITLE
Shop owners can't setup shop

### ISSUE THREAD

**Issue by munroe7** [reactioncommerce/reaction#3485] opened 2018-01-15 11:41 UTC
Shop users are not able to setup their shops because the 'Base' dropdowns are missing their options. 

Steps:
Enable Marketplace from admin account
Check off 'Allow merchant signup' and sign out
Create a new user, login, and enable the shop for this user
Click on the users name on the navbar and select 'Shop Setttings' from the dropdown menu
Once the Shop settings window appears, try to select 'Base Currency'
Dropdown should be empty (this prevents the form from being submitted)

I can "edit" (sorta) the shop settings if I select the shop option from the right sidebar but no changes are ever saved even though a dialog popup tells me that everything has been saved.

Reaction commerce v1.6.4

λ reaction -v

Node: 6.11.2
NPM: 3.10.7
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Docker: 17.12.0-ce

**Comment by prinzdezibel** [comment] 2018-01-15 18:24
This issue is a dupe of #3336

**Comment by prinzdezibel** [comment] 2018-01-15 18:30
Talked to @Akarshit. First we've been thinking the right approach would be to display the primary shop's currencies and units. After a while we figured out that the right solution probably would be to just hide the menu item completely as mentioned in #3336

**Comment by prinzdezibel** [comment] 2018-01-15 18:44
@Akarshit @zenweasel  Should we consider to close this issue, because it's already addressed through #3336?

**Comment by zenweasel** [comment] 2018-01-15 21:44
Closed. Duplicate of #3336

**Closed by zenweasel** 2018-01-15 21:44 UTC
Labels: bug, duplicate, impact-major, verified-reproducible
