### ISSUE TITLE
GraphQl Error: No currency definition found..

### ISSUE THREAD

**Issue by NuruddinBadawi** [reactioncommerce/reaction#5175] opened 2019-05-13 04:33 UTC
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
I add new currency in `Shops.json` like this
```
 "TRY": {
      "enabled": true,
      "format": "%s%v",
      "symbol": "₺"
    }
```
when I query `primaryShop` in graphQL, I get this error

`"No currency definition found for TRY"`

I check the Open Exchange Rates service if I add correct code, I see it's correct
https://docs.openexchangerates.org/docs/supported-currencies

 so where is the problem ?

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. add the TRY currency in Shops.json
2. reaction reset && reaction
3. open graphQL and query primaryShop with currency

### Versions
Node: 10.15.3
NPM: 6.9.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Docker: 18.09.2

**Comment by chrispotter** [comment] 2019-06-20 18:36
Looks like the only usage of this file is in [this file](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/core/server/startup/load-data.js) which represents fixture data if that collection hasn't been loaded into Reaction's mongodb instance yet. 

Searching through the code, there doesn't look to be a way to add additional currencies through the Operator UI except to directly query the database.

**Comment by zenweasel** [comment] 2019-06-21 09:22
@chrispotter It's going to be pretty rare that a new currency needs to be added after a shop is launched (when a new country appears or they switch currency) so I don't think there is going to be need for adding a currency through the operator UI. But if loading it in `Shops.json` doesn't work, then that's a problem as that has worked in the past.

**Comment by chrispotter** [comment] 2019-06-21 13:09
Upon further investigation, there are two things that need to occur according to the [load-data file](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/core/server/startup/load-data.js#L14-L22) provided. 
1. Ensure that there is no env variable called `process.env.SKIP_FIXTURES`. This will cause the entire file to be skipped. 
2. (This is most important but could be difficult depending on the data stored) Locally I needed to delete my Shop collection within MongoDB. (I was also able to delete the only document within the collection and restart my reaction) This rebuilt my shop collection with the `TRY` currency included.

Ultimately @zenweasel this file works as it was intended, so that's good news.

**Comment by aldeed** [comment] 2019-09-10 19:19
I'm closing this. The workaround is to modify currencies array directly in each shop in Mongo. I think we are moving away from grabbing currency list from the shop and instead using the `CurrencyDefinitions.js` file everywhere. That is the true fix. Anyone who sees any currency missing from that file should submit a PR to add it.

**Closed by aldeed** 2019-09-10 19:19 UTC
Labels: bug, impact-major
