### ISSUE TITLE
Changing languages from English to Romanian and back again only changes some labels

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1476] opened 2016-10-06 06:29 UTC
### Expected behavior
All labels for which there is a translation should show Romanian when that language is selected and go back to English when English is selected

### Actual Behavior
Some labels switch back, some do not.

### Steps to Reproduce the Behavior
1. Login to edit product
1. Switch language to Romanian
1. Observe that most labels have switched to Romanian
1. Switch language back to English
1. Observe that some labels do not switch back to English
1. Refresh page and observe that all labels switch back to English

This is an edge case since I don't know how often people would need to change languages while editing products and even then you can just refresh to fix it, but just documenting it here.

**Comment by aaronjudd** [comment] 2016-10-20 22:52
This is usually caused by:
1 - missing translations phrases
2 - missing i18n implementations

and is not generally language specific.  

I am closing, as we've now translated most missing phrases for all our top languages.  

I'm not able to replicate behaviour specific to switching languages or login/logout. All that is persistent for me.

**Closed by aaronjudd** 2016-10-20 22:52 UTC
