### ISSUE TITLE
Can't cleanly override CSS in custom.reaction.import.less

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#406] opened 2015-07-10 08:23 UTC
The header of the file says that this file is for the user to modify. But overriding CSS selectors in that file e.g. 

    footer {
      height: 70px;
    }

does not work, because the value (with the same css precendence value) in custom.reaction.less (originating from reaction-core-theme/theme/layout/footer/footer.less) is sourced later and therefore wins.

(see also custom.reaction.less.css in browser console)

**Comment by mikemurray** [comment] 2015-07-10 19:29
I'm currently in the process of tweaking how the custom / default css is loaded.

**Comment by aaronjudd** [comment] 2015-07-21 19:23
This is a duplicate of #341. moving to that issue.

**Closed by aaronjudd** 2015-07-21 19:23 UTC
Labels: discussion, in progress

**Comment by prinzdezibel** [comment] 2015-07-31 13:32
This problem still exists with v0.6.3.
