### ISSUE TITLE
Error on product image add - impossible to add images.

### ISSUE THREAD

**Issue by dominik-myszkowski** [reactioncommerce/reaction#5840] opened 2019-11-29 15:10 UTC
## Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you able to consistently reproduce the issue?
* [x ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
There is an error each time I try to add an image (or many) to a product. There is a red popup in the bottom left stating:

Network error: Response not successful: Received status code 400

## Steps to Reproduce
1. Create new product
2. Try to add an image (or several)

### Versions
2.9.0

**Comment by aldeed** [comment] 2019-12-14 22:14
@manueldelreal Can you see whether you can reproduce?

**Comment by manueldelreal** [comment] 2019-12-16 00:35
@aldeed I can't reproduce it on 2.9 but I do on the 3.0.0 branch and current alpha, this came up as one of the current items on the pending to-do a couple of days ago.

These are examples from 2.9
![Screenshot from 2019-12-15 18-19-50](https://user-images.githubusercontent.com/13787861/70871877-389c0e80-1f69-11ea-93b5-ad96f5cd86c6.png)
![Screenshot from 2019-12-15 18-30-21](https://user-images.githubusercontent.com/13787861/70871879-389c0e80-1f69-11ea-82a5-7be17b78b0c4.png)


@dominik-myszkowski do you still have a running 2.9 install where you are seeing this issue?

**Comment by zaibacu** [comment] 2019-12-16 07:11
I'm getting same error on versions: latest, 2.9.0, 2.8.1 and 2.5.0

Screenshot of error:
![image_upload_error](https://user-images.githubusercontent.com/606346/70886398-1693a200-1fe4-11ea-87bd-0fec6e676d7d.png)

**Comment by aldeed** [comment] 2019-12-16 22:38
@zaibacu That is an issue I'm aware of that only affects Firefox as far as I know. It has another issue here: https://github.com/reactioncommerce/reaction-file-collections/issues/35

Is everybody in this thread seeing it on Firefox, or are there multiple 2.x problems here? The bug in 3.0 is likely slightly different.

**Comment by willopez** [comment] 2019-12-16 23:38
I can verify this only affects Firefox, this will be addressed in the Reaction file collections repo.

**Comment by aldeed** [comment] 2019-12-17 19:24
@willopez It's released. You can try updating both `file-collections` packages to fix in Reaction.

**Comment by willopez** [comment] 2020-01-30 17:48
resolved in #5939

**Closed by willopez** 2020-01-30 17:48 UTC
Labels: bug, impact-major, p2
