### ISSUE TITLE
Plugin loader does not handle removing plugins

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1199] opened 2016-07-25 05:35 UTC
### Expected behavior
If a custom plugin is removed it's imports should be removed as well

### Actual Behavior
Imports remain and project fails.

### Steps to Reproduce the Behavior
1. Clone `beesknees` into the `custom` directory.
2. Start Reaction
3. Stop Reaction and delete the `beesknees` directory
4. Start Reaction again
5. Observe the error

```
Unable to resolve some modules:

  "/imports/plugins/custom/beesknees/client" in
/Users/brenthoover/Projects/js/reaction/client/plugins.js (web.browser)
```

**Comment by jshimko** [comment] 2016-07-25 19:25
Reaction CLI >=0.3.10 has a fix for this.  It will now generate fresh plugin import files before every app start.  As far as I can see, the only other way around this would be manual plugins.js file edits or a complicated Meteor build plugin because Meteor is evaluating the entire folder tree before running the development plugin loader (which is why it hits that broken import _before_ regenerating the file)

**Comment by jshimko** [comment] 2016-08-03 20:19
This issue was fixed here (v0.4.0):
https://github.com/reactioncommerce/reaction-cli/commit/4df088d9c7c490ab150ab8e7238e30292fd0e669

**Comment by Capt-Slow** [comment] 2016-08-11 20:46
Fix denied.

Steps to Reproduce:
1) Started reaction.
2) `cd` into `/imports/plugins/custom/` git clone `git@github.com:reactioncommerce/reaction-example-plugin.git`
3) Observe Reaction restarted without errors.
4) `rm -rf reaction-example-plugin`

Result:
The user will receive the following error
Unable to resolve some modules:

  "/imports/plugins/custom/reaction-example-plugin/client" in
/Users/corvus/reaction/client/plugins.js (web.browser)


Unable to resolve some modules:

  "/imports/plugins/custom/reaction-example-plugin/server" in
/Users/corvus/reaction/server/plugins.js (os.osx.x86_64)
  "/imports/plugins/custom/reaction-example-plugin/register.js" in
/Users/corvus/reaction/server/plugins.js (os.osx.x86_64)

**Comment by jshimko** [comment] 2016-08-11 21:13
Are you using `reaction-cli`?  If you are, that result should be impossible.  The CLI clears those files before even trying to start the app.  It's currently the only cross-platform way to ensure those files are reset before Meteor tries to evaluate them.  Short of hacking Meteor's build plugin, that's our only option.

**Comment by jshimko** [comment] 2016-08-11 21:21
If you _are_ using `reaction-cli`, I assume you deleted that plugin while the app was running,  which means Meteor seews the change and restarts, but the CLI doesn't reset the plugin files and Meteor tries to rebuild the least amount of changes possible.  Stopping and restarting the app will fix that every time because `reaction-cli` resets every time.  Other than that, we have a huge complicated Meteor build tool standing in the way of a simpler fix there.

**Closed** 2016-08-11 22:10 UTC

**Comment by Capt-Slow** [comment] 2016-08-11 22:14
Had a discussion with @jshimko and my issue is expected behavior, since there isn't currently way to remove plugins while Reaction is running. The user would need to restart the service for changes to go into effect.
