### ISSUE TITLE
sweetAlert2 depreciation warning

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3680] opened 2018-02-08 23:43 UTC
SweetAlert2 throws the following warning on modals
`SweetAlert2: The parament "useRejections" is depreciated and will be removed in the next major release`

### Versions

```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 18.01.0-ce
```

### QA

QA by @kieckhafer + @cassytaylor

**Comment by zenweasel** [comment] 2018-02-09 00:45
This is a duplicate of https://github.com/reactioncommerce/reaction/issues/3498. Closing. Reopen if you disagree.

**Closed by zenweasel** 2018-02-09 00:45 UTC
Labels: bug, impact-minor
