### ISSUE TITLE
[Marketplace] Product disappears after publishing changes for the first time if product is not visible

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2179] opened 2017-04-28 23:31 UTC
When creating a product as a shop admin for a marketplace, clicking "Publish" before making a product visible will cause the page to refresh and the product to be hidden from it's creator.

### Expected behavior
When I create a new product as a shop owner, I should be able to publish changes before making the product visible.

### Actual Behavior
When I click publish the page refreshes and I am shown the Product Not Found template.
![image](https://cloud.githubusercontent.com/assets/1203639/25550658/2ae3e78a-2c38-11e7-8ab0-96d5c0294a7b.png)

### Steps to Reproduce the Behavior
1. Checkout the `marketplace` branch
2. Create a second user from incognito window.
3. Create a shop by clicking the "Become a seller" button in the user profile
4. Create a product by clicking the `+` button in the top right.
5. Add a title and subtitle to the product and click "Publish"

### Versions
```
Node: 7.8.0
NPM: 4.5.0
Docker: 17.03.1-ce
Reaction CLI: 0.8.0
Reaction: 1.1.1
Reaction Branch: marketplace
```

**Comment by terrelltechsup** [comment] 2017-04-30 16:03
I can confirm this occurs for me as well.

**Comment by aaronjudd** [comment] 2017-05-24 23:50
@michael-alade status update on this issue?

**Comment by Akarshit** [comment] 2018-02-15 10:13
Not reproducible in `release-1.8.0`

**Comment by zenweasel** [comment] 2018-02-15 21:36
I wonder if this was because the Shop was not active? This particular weirdness about marketplace shops bites me all the time. Closing. Please reopen if this reoccurs.

**Closed by zenweasel** 2018-02-15 21:36 UTC
Labels: bug, impact-minor, needs-to-be-reproduced
