### ISSUE TITLE
localization tab is broken on latest marketplace branch

### ISSUE THREAD

**Issue by tdmoneybanks** [reactioncommerce/reaction#2965] opened 2017-09-27 21:47 UTC
### Expected behavior
Open localization from the admin shortcut bar and see an action panel with the localization options
### Actual Behavior
clicking the icon does nothing, breaks several other action panels. 
in console:
`Cannot read property 'getHostNode' of null`
### Steps to Reproduce the Behavior
checkout reaction marketplace branch and run it. log in as admin and click localization from admin toolbar. 
### Versions

Node: 4.2.6
NPM: 3.10.10
Docker: 17.06.2-ce
Reaction CLI: 0.6.4
Reaction: 1.5.0

**Comment by spencern** [comment] 2017-10-03 00:14
@tdmoneybanks Is this for a merchant shop or the primary shop?

I was not able to reproduce this on `marketplace` branch for the primary shop

**Comment by impactmass** [comment] 2017-10-04 10:33
I think this is related to the errors mentioned on [2938](https://github.com/reactioncommerce/reaction/issues/2938#issuecomment-333249832), so might be getting fixed in #3020

**Comment by spencern** [comment] 2017-10-09 21:46
Resolved by #3020

**Closed by spencern** 2017-10-09 21:46 UTC
