### ISSUE TITLE
"Shipped" button on orders panel returns blank panel

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#2136] opened 2017-04-18 09:59 UTC
When I click on "Shipped" I get an empty panel.

### Actual Behavior
![bad_shipping](https://cloud.githubusercontent.com/assets/72819/25033017/251d0962-210c-11e7-83b5-c8857096f74f.gif)

**Comment by aaronjudd** [comment] 2017-05-02 00:02
This is duplicated (with some error reporting) in #2142. Closing that issue.

**Comment by aaronjudd** [comment] 2017-05-02 00:03
From @spencern 


Steps to reproduce

1. Clone `release-1.1.1`
2. reaction reset
3. meteor npm install
4. reaction run
5. setup stripe & enable all three default Flat Rate shipping options
6. Place Order from incognito window
7. Click into order from notifications panel
8. Attempt to fulfill order

No console errors were shown when attempting to fulfill order, but dashboard action panel appears empty and when clicking the `<-` back arrow throws the following error.

```
main.js:354 Uncaught TypeError: Cannot read property 'pop' of undefined
    at Object.popActionView (http://localhost:3000/app/app.js?hash=cefcfaa4796cc18f5ea7d77d168df51176564e34:66581:20)
    at Object.handleActionViewBack [as onClick] (http://localhost:3000/app/app.js?hash=cefcfaa4796cc18f5ea7d77d168df51176564e34:30053:12)
    at Button._this.handleClick (http://localhost:3000/app/app.js?hash=cefcfaa4796cc18f5ea7d77d168df51176564e34:39219:21)
    at Object.ReactErrorUtils.js.ReactErrorUtils.invokeGuardedCallback (http://localhost:3000/packages/modules.js?hash=f8877f8ddab1183cef2c3299adca352ccd2d7707:119400:16)
    at executeDispatch (http://localhost:3000/packages/modules.js?hash=f8877f8ddab1183cef2c3299adca352ccd2d7707:119180:21)
    at Object.executeDispatchesInOrder (http://localhost:3000/packages/modules.js?hash=f8877f8ddab1183cef2c3299adca352ccd2d7707:119203:5)
    at executeDispatchesAndRelease (http://localhost:3000/packages/modules.js?hash=f8877f8ddab1183cef2c3299adca352ccd2d7707:118587:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3000/packages/modules.js?hash=f8877f8ddab1183cef2c3299adca352ccd2d7707:118598:10)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:3000/packages/modules.js?hash=f8877f8ddab1183cef2c3299adca352ccd2d7707:119507:9)
```
Which is throwing an error from here:
```
 popActionView: function () {                                                                                         //
    var actionViewStack = Session.get("admin/actionView");                                                             //
    actionViewStack.pop();                                                                                             // 354
    Session.set("admin/actionView", actionViewStack);                                                                  //
    this.setActionViewDetail({}, {                                                                                     //
      open: false                                                                                                      // 358
    });                                                                                                                //
  },     
```


![image](https://cloud.githubusercontent.com/assets/1203639/25160260/e17c0ae4-2469-11e7-8064-6ef864109eab.png)

**Comment by aaronjudd** [comment] 2017-05-16 01:55
@kieckhafer not closed, not resolved in several weeks, open back up to the team? (unless you want to take it back on)

**Comment by kieckhafer** [comment] 2017-05-16 21:13
@aaronjudd I am unable to reproduce... on the `release-1.2` branch
![shipping mov](https://cloud.githubusercontent.com/assets/4482263/26128603/cc966dac-3a41-11e7-8cfd-823937add4a5.gif)

**Closed** 2017-05-16 21:34 UTC
Labels: bug, ready

**Comment by spencern** [comment] 2017-05-17 00:09
@aaronjudd and @zenweasel I propose that we open #2142 back up if it's still not fixed so there is a more specific issue to fix.
