### ISSUE TITLE
No way to change language or currency on mobile

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2298] opened 2017-05-17 09:45 UTC
### Expected behavior
There should be a way to change my currency when on a mobile device (especially since it seems to have auto-detected my currency?)

### Actual Behavior
I can't see a way to change it.
![glass](https://cloud.githubusercontent.com/assets/72819/26148196/6f19fcd8-3b28-11e7-8b91-2b075f3d8bab.png)

### Steps to Reproduce the Behavior
1. View the site on the iPhone simulator

### Versions
```
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.2
Reaction: 1.2.0
Reaction branch: development
Docker: 17.03.1-ce
```

**Comment by aaronjudd** [comment] 2017-06-20 01:00
@rymorgan you might want to review this, seems that this may be a responsive issue..

**Comment by rymorgan** [comment] 2017-06-20 21:29
I'm not totally following what the issue is here. I see a way to change it but I'm probably missing something. 

![internationalization](https://user-images.githubusercontent.com/20409254/27356732-85fd34cc-55c4-11e7-8fa1-23fec5f5d029.png)

**Comment by zenweasel** [comment] 2017-06-20 22:13
@rymorgan That's for admin, but for consumers. In my example, currency is being auto-detected but I have no way to change to the shop currency. I know these selectors are being hidden on purpose but there should probably still be some way for a consumer to switch currency, especially when we are forcing it to a non-shop-default.

**Comment by rymorgan** [comment] 2017-06-20 22:32
@zenweasel gotcha.

**Comment by Akarshit** [comment] 2018-02-20 05:01
@rymorgan Would it be ok if the dropdown to select the currency is added next to the search button?

**Comment by rymorgan** [comment] 2018-02-20 18:52
It should instead be added to the hamburger menu w/ the other items. Only the most important user actions should be "main" mobile nav. 

<img width="319" alt="screen shot 2018-02-20 at 10 52 19 am" src="https://user-images.githubusercontent.com/20409254/36442937-2c8e3bb0-162c-11e8-9f15-874324fa5f00.png">

**Comment by rymorgan** [comment] 2018-02-20 20:21
I just remembered that a currency selector is already there on mobile. So, you might be able to just close this out if that meets all of @zenweasel criteria on this issue. 

![screen shot 2018-02-20 at 12 19 43 pm](https://user-images.githubusercontent.com/20409254/36447230-8e9c6dca-1638-11e8-9918-e5a25086cb37.png)

**Closed** 2018-02-21 04:45 UTC
Labels: UIX, bug, design-complete, impact-minor
